#+title: The Art of Argumentation

* notes
+ the purpose of the debate as determining the strategy---are you interested in convincing your interlocutor or not?
+ types of debate have different strategic considerations
  + bloodsports
    + pummel your opponent with their failings---rub their noses in it and do not let up for a single second. Immediately and prominently embarrass them for any tiny slip up---give them not a moment to correct it, instead highlight this slip up as a way to slip away from the point.
      + in the arena of bloodsports you do not need to take your time to carefully unravel the various errors going on in, say, a socialist's theory of economics. Rather you can simply hold up the fact that they want to use violence to force other people to work for them---that they are incompetent and second hand, that they are a parasite who wishes to suck upon the most productive men in society.
  + dialectic
+ the importance of having a strong philosophical foundation to engage in effective debate
  + https://www.youtube.com/watch?v=Ys0Sgicnjz4 in his opening statement the world champion uses nonsense arguments that can be easily destroyed by an experienced philosopher.
