#+title: What Debate Is, and What Debate Is Not. | The Purpose and Standard of Debate

* Debate is not About Persuasion
Consider the following proposal: I wish to host a chess tournament, but I don't know the rules of chess! So, I decide that the standard I will use to determine the winner of each match is whoever the audience thinks has won, where the audience themselves /also/ do not know the rules of chess.

This is how most people think debate works. That the man who won the debate is he who has most fully appealed to the masses, that the yardstick of truth in a dialogue is the average, the uninformed, the audience. This is true only of the sort of "debate" which most people are acquainted with: the sort of debate that is held between presidential candidates and party officials. The standard of victory here is literally getting more people to vote for you, so it is no surprise that participants conduct themselves in a way that appeals to the lowest common denominator.

This is not how /true/ debate works. In debate the standard of victory is set by reality. Namely: if we were to map out the logical "flow" of the arguments and counter-arguments on some point, which party has shown the point to be correct? To borrow an example from Michael Moreno,[fn:1] if the debate is about whether immigration is good, you opponent makes the argument that bringing more immigrants to the US would force them to participate in capitalism, but you make the argument that capitalism is good, then you have won on that point. This is called "flowing through." That is, the laws of logic, those rules that you must follow for correct cognition, are also the standard of correct debate.

There are a few problems with the "persuasion" model of debate, the first of which is that if the standard of debate is to persuade the judge (or the audience), rather than prove to him that you are correct, then debaters will tend towards espousing whatever ideology is already held by the judge. If he is a leftist, in order to win rounds, the debaters will adopt and promote leftism---whomever is most vociferous in their adherence to the judges ideology will be deemed to have won. But then this debate community is tending towards becoming an echo-chamber. Echo chambers remove the precondition of debates to happen in the first place, namely: intellectual diversity. Thus, the persuasion model of debate leads to a situation where no debate can take place; there is no need or possibility to persuade anybody of anything where everyone is already in total lock-step agreement with the judge. That is, the persuasion model of debate, that one adopted by every ideological salesman and word sorcerer, necessitates its own obsolescence. Debate just cannot have persuasion as its standard, as that standard eliminates the thing it is supposed to be a standard for.[fn:2]

The persuasion model also doesn't work even on the inter-personal level---trying to /convince/ your friend of some point. This is first of all, simply a bad way to think about debate in terms of your own self-interest. Consider the situation where you accept some incorrect point, and you are really good at persuading people (which would be the ideal on this model). If you can persuade anybody you meet of this falsehood, then you have stunted your own intellectual development---nobody will ever be able to show to you how you have erred, and you have thus lost the great resource that is learning from other people. It is only in framing debate as a battle of logic, not of persuasion, that avoids this point. The ideal logician is the one who can prove the truth in every instance---this is certainly not pulling him away from truth!

The persuasion model is also bad on a strategic level for anybody who holds a true philosophy. Any person who is worth convincing and having join your ranks would accordingly be a person who takes reality as his guide, and would be convinced by the logic model of debate. On the other hand, one who can be reached only by non-logical appeals is one who should not be reached in the first place.

At best, such individuals form ideological chaff---great wads of cotton filling your meeting places and slowing down discourse within your movement. After all, if 50% of people whom I spend time discussing philosophy with are completely useless and will never understand, then I still have to bear the opportunity cost of speaking to them, rather than someone worthwhile. This great cost goes down as the number of these irrelevants goes down.

At worst, these individuals will take with them their moronic and/or brutish creeds. Your previously libertarian meeting will become filled with a cabal claiming that true liberty requires the emancipation of the workers, and that as such you must embrace socialism. The leader of such a cabal would, of course, not be one of the chaff, but a double-agent, seeking only to undermine and subvert your movement.

The ideological salesman, who attempts to downplay the radicalism, and open up the tent to as many as can fit, is therefore poisoning the very movement that he is hoping to promote. The standard of successful libertarian strategy is not that more people call themselves libertarians---it's that they /adopt/ libertarianism. To get them to adopt libertarian you must prove to them that it is correct, not convince them of it without any requirements on their ideas to line up to rigorous logical standards. Wishing to the genie that everyone in the world becomes a libertarian would surely be subverted in the way that everyone calls themselves a libertarian, but nobody actually changes their ideas. This would not be neutral, it would be deadly---suddenly all of the work required to build the movement in the first place would have to be done anew under some alternative label. One would have to wade through a great ocean of chaff to re-discover the radicals, half of which could very well have been dissuaded from ever bothering with praxis ever again.


* Footnotes

[fn:1]He has unlisted all of his videos, so a full citation is not possible. The video was: Michael Moreno, /Debate Is Not About Persuasion/.

[fn:2]I borrow this argument from Michael Moreno.
