#+title: Do Not Give Into Evil

[Do not give into evil, but proceed ever more boldly against it.] These are the words that would bolster the greatest economist to ever live, Ludwig von Mises, during his struggle against totalitarianism.

True liberalism was on death's door by the time he started his work, and Mises had all the knowledge necessary to save it for future generations---but unfortunately war broke out and he was sent off by the Austrian government to die on the front lines. Luckily he would survive the war, but he correctly predicted that Germany could easily turn sour in the aftermath, so he set his efforts towards converting German scholars towards liberalism to prevent this, fighting against his enemies in the Socialists of the Chair.

Unfortunately, the socialists would win with the rise of their idol, Adolf Hitler. Mises was barely able to escape to the United States, where he was able to meet like-minded individuals and keep liberalism alive. He was surrounded by some of the greatest evils mankind has ever faced, and yet he persisted, so you should always remember: do not give into evil, but proceed ever more boldly against it.
