#+TITLE: A Challenge to Minarchists
#+AUTHOR: LiquidZulu

* The Challenge
I present a challenge to all minarchists, of all shapes and sizes that I think highlights a fatal flaw in their ideology. First I clarify the three main types of minarchists I see, which shall receive tailored, but related queries. We have:
+ The Randian Minarchist
+ The Nozickian Minarchist
+ The Utilitarian Minarchist

** The Randian Minarchist
When I speak of the Randian Minarchist, I specifically do not make a mention of Objectivism, because I am speaking of the superset that many Objectivists do find themselves in, but that is not defined by Objectivism. To me, the Randian Minarchist is any minarchist who accepts non-aggression to the core of their being and all in all doesnt have any true contention with anarchism, but they cling to the idea that there ought to be some large non-aggressive quasi-state that will provide rights enforcement to all, whether a person can pay for it or not. I ask of the Randian Minarchists two things:
1. How much rights enforcement does this quasi-state provide to each individual?
2. How do you expect such an entity to form and to maintain itself?

For the first question I note that rights enforcement is not an industry that does not suffer the problem of scarcity, it is still true that man faces scarce means in the world that he inhabits, means that he must economise toward the attainment of his varied and numerous ends. This means that rights enforcement, like all other goods, can be over-supplied. Imagine the reductio-case of 100% of GDP being allocated to enforcing peoples rights, great you may think, right up until you realise that nobody is farming any food and you all starve to death. So the correct allocation is something less than 100% of GDP it would seem, but how much less? Does the quasi-state provide everyone with a tank and three armed guards? How about it just gives you a pistol --- and how good of a pistol does it give? These are seemingly unanswerable from the perspective of a minarchist society.

As for the second question, I cite Hayek's knowledge problem,[fn:1] wherein he points out the importance of price mechanisms in communicating subjective knowledge held by individuals, namely without price mechanisms you are unable to solve the actual problem of economics, that is, the problem of how to communicate this knowledge to society writ large such that means may be allocated towards solving those problems that plague every day people. Without a price mechanism in the enforcement of rights you cannot know how best to allocate means, which is the link between these two quandaries --- it is only in solving the knowledge problem that you can solve question 1, and it is only through prices that you can hope to solve the knowledge problem.

** The Nozickian Minarchist
The Nozickian Minarchist that I attack here doesn't necessarily say that the state is just or moral, but that it would arise naturally from the anarchy present in the state of nature, thus making the point moot. The argument goes as follows:

In a state of nature men may come into conflict over scarce means. Individuals, if they wish to engage in a division of labour to the greatest extent, would therefore have to seek a way to resolve these conflicts. Due to some individuals being better suited at the various tasks involved in conflict resolution, we should expect to see groups forming that provide protection --- rights enforcement agencies and rights enforcement coops. Between these various groups norms would develop that make it easier to deal with and to avoid future conflicts. Courts would form to provide impartial judgement on disputes between groups. But what happens if two of the groups have a dispute and cannot agree to arbitrate with a neutral court? They are left with two options:
1. deal with the conflict through violence.
2. ignore the conflict in a pacifist fashion.

Nozick argues that the larger a protection agency is the better able it is to protect the rights of its members, a dominant agency would thus emerge that is simply superior to others, and its territory would spread leading to a local monopoly and thus a state.

This argument is fine, right up until the final paragraph. Its as if I stated a priori that the larger a restaurant is the more food it can make, thus everyone will go to the biggest restaurant and there will be no small restaurants left. This is an obviously absurd concept, yet its exactly what the Nozickian Minarchist relies on. Why is it that we dont see restaurant monopolisation yet we should suddenly expect that the largest rights enforcement agency necessarily provides the best product? What if I want a very specific type of protection that is provided for only by niche firms? What if I fund my own private militia that can better protect me than any package any firm is selling? The Nozickian ignores these obvious counterexamples.

** The Utilitarian Minarchist
The Utilitarian Minarchist is a general category for those who acknowledge the superior ethics of anarchism, but say that we still need a state for x, y, or z. Often these minarchists will have a single hanging points that needs to be ironed out before they finish their 6 month wait time prior to advancement into full anarchists. As this category is the broadest, my questioning will take on a more shotgun approach, providing a spring-board with which one may interrogate individual Utilitarian Minarchists:
1. How does one measure utility, is such a thing even possible?
2. Can you have inter-personal comparisons of utility --- i.e. can I say that John will enjoy a hotdog /more/ or /less/ than Paul?
3. What makes the set of industries that the minarchist state ought to monopolise distinct from those that it ought not?
4. If your minarchy engages in taxation, how does it overcome the necessary de-civilising effect that taxation has?[fn:2]
5. Can you prove that your minarchist state will have superior outcomes to a total free-market.

* Call to action
If you are a minarchist or know of any minarchists who you think could meet this challenge, please send them my way, and if you want to see more videos that open a dialogue please hit the like button. Also if you are interested in my critique of pragmatists within our ranks, this video is for you.

* Footnotes

[fn:1]Freidrich A. Hayek, "[[https://mises.org/library/use-knowledge-society][The Use of Knowledge in Society]]," ([[https://archive.ph/9LbZz][archived]]).

[fn:2]See, Hans-Hermann Hoppe, "[[https://portalconservador.com/livros/Hans-Hermann-Hoppe-Democracy-The-God-That-Failed.pdf][Democracy: The God That Failed]]," /Ninth paperback printing 2007/ (ISBN: 978-0-7658-0088-6), pp. 1--15.
