#+TITLE: Shapes And Ladders

* Movement Shapes
We apply our knowledge that connected stones are safer than unconnected stones to determine how we can most efficiently move across the board whilst keeping our stones safe. Remember, we don't want to be placing entirely connected stones all of the time, this would be far too slow, rather we want to place stones that gain territory whilst being trivial to connect.

** n-Point Jumps
First we consider the one point jump, here black has two stones, A and B, that he wants to keep connected, he achieves this with the one point jump. This move is safe because white has no effective ways of cutting, if he tries black can easily prevent the cut and keep his stones connected. Let's try and extend this out into a two point jump, and see if black is in a similarly secure situation. Wargaming this, we see that black remains able to prevent any attempt to cut from white, two point jumps are also secure. But notice what happens when black makes a three point jump---white is able to cut these stones apart, the three point jump is not secure, at least not on its own. We conclude that the maximum safe jump is two points.

** Diagonal
But what if you dont want to just go in a line? Just going in lines is boring and doesn't necessarily get you the most territory, so we now need to incorporate two dimensional movement. The most simple 2D move is the diagonal, this is very secure as no matter which side white cuts, black can trivially connect up on the other side, so there is absolutely no way for white to prevent these stones from getting connected. But this is a very slow move, sometimes you might want to go a little further, so what about a diagonal /with/ a one point jump? You will recognise this as a small knight's move.

** Knight's Moves
Knight's moves are cuttable shapes, but whether you can cut them depends on the context, in general playing a knights move near the edge will be safe but playing it in the middle will not. Take this example of a knights move forming a corner enclosure, white can cut these stones, but what can he do now? Black can just kill the white group and thereby get his stones connected. This is not always the case however, here we see black attempting a small knight but with white stones flanking. Black can try the same tricks he did in the corner but we can see that white is able to sever the two stones that black wanted to connect up---we conclude that knights moves may or may not be secure depending on the context. The same applies to the large knights move, here too white requires support in order to effectively cut.

* Fighting Shapes
The next shape to consider is the ladder, in this arrangement of stones there is a guaranteed way for black to capture the white, all black must do is place a stone here, which if white escapes, black can recursively chase down the white stone in a formation known as a ladder. Notice also how the base of this ladder looks very much like our short knights move from before, for this reason we should expect ladders to show up relatively often in our games. There are two main reasons why a ladder wouldn't work, the first is if you force white to connect with one of his stones, this gives white far too many liberties to contend with and allows him to start putting the walls of the ladder into double atari, ruining your plan. Another possibility is that the ladder scrapes by a nearby white stone, directly putting the black walls into atari, allowing white to survive.

Another attack shape is the net, here you can see a white stone in the base of what will become our net, if black places a stone here he has completed the net and has prevented white from escaping. The net becomes useful when we see that we can apply it on top of a large knights move. Here, if black completes the net, white has no escape, he is trapped. Similarly to our talk of knights moves being cuttable with sufficient white support, the net does not work if white has sufficient stones to support his netted stones. Of note here is that the net is very effective, because it forms for black what is called a mouth-shape, which is very easy to turn into an eye, thus providing the potential to make life for black.

* CTA
Next, to further develop your knowledge of shapes in Go, you have to watch this video where I go over more shapes and their merits.
