#+title: Failure Mises Caucus | How The Mises Caucus Died - Split Personalities [thumbnail concept includes some split personality imagery, secession of AZ, the return of pragmatism]

* notes
** Dave Smith human action podcast
+ https://www.youtube.com/watch?v=1EZ6-Pn9j88
+ 4:10 the open borders types are "too married to ideology"
+ 22:10 "the real world"
+ he keeps coming in with this notion that open borders means "owned by everyone"---it doesn't, it means owned by nobody.
** dave smith biblical anarchy podcast
+ 14:00 says that he would reject libertarian theory if it lead to things that make him feel icky
+ 15:50 "if there is government property it should be handled this way"
  + the question of what colour of uniform we should dress jews in as we gas them to death simply does not come up, the question of what brand of knife we should use to stab someone to death does not come up---these things should not occur in the first place, you have already crossed Rothbard's razor
  + its a question of property rights, does the government have property in those possessions? If not they have no right to exclude anybody from them and it is proper to oppose their forestalling of these goods
    + its all well and good to say that you would prefer the streets to be sweeped and the grass to be mowed, but that is not the question that law answers
+ 17:00 is the homeless drug addict a reductio case, or the expected outcome? Unclear.
  + the reductios can go both ways---on restricted immigration, prevent the children from ever leaving the school and prevent parents from retrieving them, turn it into a work camp.
+ The framing of "while government property exists it should be restricted" is dishonest---we are the ones advocating that the government not restrict those possessions, that it be left open to homesteading
  + the implicit premise is that open borders means that the government will let anyone in and that they will stop you from preventing people from coming in, but this is completely false.
    + it's the idea that open borders means everyone owns public property---this is a complete inversion of the actual stance, which is that it is not owned by anyone so it is liable for homesteading
+ 28:40 "there is this thing called government property, it is not a given that there should be no restrictions on it or that nobody owns it"
  + but who owns it?
+ 33:10 can't deduce the property owner---he calls this mental gymnastics, the proper position is that it is owned
  + but BY WHO? WHO OWNS IT?
+ 34:50 claims universal teleology is correct
+ 38:00 says he will address my argument, but instead just makes the nonsense claim that theft means you have retroactively enslaved the person
+ 44:00 says "yeah, ok" to the fact that there is no title transfer chain linking "the taxpayers" to the goods in question
  + says its not the case that its unowned---then who owns it?
+ 46:30 just states my case that the homeless man has homesteaded a slide by sleeping on it, but what is the counterargument?
+ 47:10 his question which apparently nobody would answer: two ways that we can privatise something, one way is that everyone on the block gets the piece of the street that extends beyond their house. The other proposal is that the road is given to a private company in swizerland.
  + the proposal I am giving is that it be homesteaded, not "given away" because the government doesn't have the right to give it away
+ 50:00 says that Ace is wrong that if you rob someone and buy something with the money that you only have a claim to the money, not what they buy
  + but why? At what point do you start owning the thing they buy?
    + misrepresents Ace as saying that the thing is therefore unowned---no, it is owned by the guy who sold it
+ 1:11:40 says its a win to put the entire military on the border---what happens to the Mexicans who cross?
  + let's be realistic! What plan would a state have when they are placing their entire military on the border? Could it perhaps be that they want to invade?
+ He doesn't address the domestic migration point---why not ban migration between states within the union as well?
+ 1:15:40 claims I will never have an impact on the culture---we shall see.
+ 1:16:40 says we are "missing virtue"
  + at no point did I claim that legal theory is the entirety of ethics
+ 1:30:10 says that we should approximate how it would be privately operated, but how? The ECP stands in the way
+ 1:32:10 says that the net taxpayers don't own the property---but then who does?
