#+TITLE: Taxing Disney is Evil
#+STARTUP: entitiespretty

* SEO Checklist :noexport:
** Points to hit [4/16]
+ [ ] who's the character?
  + [ ] their want?
  + [ ] their need?
  + [ ] their flaw?
  + [ ] how do they grow?
  + what story/journey could the above create?
+ [ ] what's the desire/motivation of the story?
+ [ ] what's the obstacle?
+ [ ] what're the stakes --- why is it important?
+ [ ] make them care
  + [ ] show what you have so the audience feels the loss when you lose it
+ [ ] what's the resolution --- the one core idea that is the final message of the video that wraps everything up?
  + deliver on the title and thumbnail
+ [ ] storyboard it [0/3]
  + [ ] storylines you have
  + [ ] hook for each
  + [ ] different things that can happen
+ [ ] attach a story to every point I make and tell the story before I make that point
+ [ ] answer questions using spectacle
+ [ ] if things go static stories die, because life is never static.
+ [ ] drama is anticipation mingled with uncertainty
+ [X] make comment goals (2 or 3)
  + "It's good that someone is calling out these people"
+ [X] cater to the archetypal viewer
+ [X] reference popular media
  + title cards?
+ [X] Make an audience proxy (state things the viewer is thinking)
+ [ ] Problem every 2 minutes
** Intro [2/3]
+ [X] 8 words right at the start explaining the concept
+ [ ] Personal (character) motivation
+ [X] Create an enemy
  + DeSantis? Seems weak
** Questions to ask [4/10]
+ [X] is there incentive to watch until the end?
  + kinda, but really wordy
+ [X] can I add something?
+ [ ] what are the different loops that I can open?
+ [ ] what are the different questions that the viewer could ask themselves?
+ [X] what's the hook?
+ [X] what do viewers need to see in the first few seconds based on the title and thumbnail so that they feel like their click is worth it?
+ [ ] is there a way to make the viewer laugh or feel surprised or feel something in the first 10 seconds?
+ [ ] is there a way to have two storylines?
  + [ ] surface level story, and hidden stories (finding nemo is ostensably about finding nemo, but really about marlon addressing his insecurities as a father)
  + [ ] is there a way to build surface level and underlying tension in each story?
    + short term: will dory's short term memory make her forget what marlon told her, long term: will we find nemo?
+ [ ] am I giving them 4 or 2+2?
  + https://www.youtube.com/watch?v=KxDwieKpawg
+ [ ] in doing X big thing [0/3]
  + [ ] what do I want?
  + [ ] what happens if I dont get what I want?
  + [ ] what will I do to get what I want?
** Editing [0/5]
+ [ ] Show where possible
+ [ ] if theres a bit of information where you can delete what is before and after it and it flows just as well, cut it
+ [ ] tell stories with B-roll
+ [ ] Keep pace as fast as humanely possible, without impacting the pacing
+ [ ] add breather moments to allow for the pace to not feel too fast https://www.youtube.com/watch?v=o8ZbGnwXjj4
** How to keep people watching [6/20]
+ [X] deliver on title and thumbnail (video "I ate 100 bananas" shouldnt start with people eating apples or you buying bananas)
+ [ ] /exceed/ the expectations made by the thumbnail
+ [X] instantly explain the payoff
+ [X] tell them why to watch
+ [X] get right into content after delivering
+ [ ] remove every dull moment
+ [ ] find 10 most critical people you know to roast your video
+ [ ] payoff at the end
+ [ ] you can make anything work but it has to be interesting to the audience, original, and good
+ [ ] big stunts
+ [X] the title should be "bananas are the best food on the planet" rather than "I like bananas"
+ [X] consider what the experience will be for people in the video, if they liked it they might want to watch more of your videos.
+ [ ] viewers can tell when you are half-assing
+ [ ] (storyline) have an objective
+ [ ] stay on topic
+ [ ] no filler, only content that is neccesary to the narrative and meets the expectations
+ [ ] for payoff have the clear goal that is teased throughout the video
+ [ ] build anticipation to the payoff
+ [ ] wait until the very end to give the payoff
+ [ ] watchtime is not created equal, engagement and viewer surveys will differentiate between a good 25min video and a great one
** Thumbnail
+ concept more important than aestethics
+ borrow from other successful videos (yoink and twist)
+ make the dominant subject someone people know (so not me when starting off)
+ provide action
+ portray the story of the video
+ other parts of the image shouldnt take focus away from the important, clickable, elements
+ confusion doesnt make people want to click, curiosity \ne confusion
+ should be accurate in the most visually applealing way
+ should be simple and clear
+ colourful and bright
+ have 2-3 different versions of the thumbnail to A/B test
+ check how they look across youtube (thumbsup.tv)
+ recognisable figures improve CTR
+ you probably only want 1 person in your thumbnail (obviously just a rule of thumb)
+ spike their curiosity so much that they will wonder what happened if they dont click
** Title
+ "and this happened" is better than "what happens next will shock you"
+ a good title says what it needs to say in as few characters as possible
** End Screen
+ Next logical step
+ What do the avatars care about?
+ Make people want to know what happens next.
+ be persuasive
  + mention the avatars desire
  + point out what more there is for them to do
    + use "have to"
  + describe the result of them doing that.
+ be confident that the linked video is good
* Disneyistan
Ron DeSantis' recent move to revoke Disney's tax-exemption is criminal and evil, stick around and I will explain point-by-point why every counterargument to this fails. This attack came about as the result of a feud over the company's opposition to his "Parental Rights in Education" bill.[fn:1] The resort, housed within its own self-governing pseudo-covenant called the "Reedy Creek Improvement District," or (RCID) covers over 100 km^2, acting with the same authority as a county government.

The Disney corporation provides emergency services,[fn:2][fn:3][fn:4] utilities,[fn:5] roads, mass-transit,[fn:6] several solar plants[fn:7] and even had plans to build its own damn nuclear reactor.[fn:8] All of this done privately, which is scarcely different from our vision of future covenant communities, we should be celebrating such an achievement, not calling for its downfall out of a desire to virtue-signal over how much we hate the woke's.

This pseudo-covenant decided to stand in defiance of a state law, which prompted the state to respond by robbing it en masse, no supporter of DeSantis here can be reasonably framed as a secessionist.

* Fairness is not a Libertarian Value
The neo-prag DeSantis supporters here make as their argument, that it is unfair that Disney get the supposed "privilege" of not having to pay taxes, and this unfair situation may be justly ironed out by revokation of said "privilege." This is a framing of taxation that is completely ignorant of the law, however. Taxation itself is a criminal action done unto people, the solution to unequal taxation is not to bring in equal taxation, its to not tax anyone at all.[fn:9]

After all, the libertarian solution to a serial killer who specialises in killing white women, is not to confront this butcher and have him kill men and people of other races in equal quantities. Its certainly not fair to the women who are slaughtered by him, but fairness is not the highest libertarian virtue, we want fairness insofar as we want adherence to natural law, which is fair by its nature. But there are plenty of other fair systems that are absolutely anti-liberty, it is liberty which matters here, not fairness.

Heck, if DeSantis really wanted to stick it to the Mouse, and be entirely fair in the process, why didn't he revoke IP protection, or extend Disney's special status to its competitors such that they can maneuver without state interference? This would not only satisfy the missplaced urge some libertarians feel for fairness, but it would be entirely consistent with natural law.

* Disney as an Organ of the State
An alternative approach the neo-prags may wish to take is to say that the Disney corporation is an arm of the state, and that its therefore fine to tax them as this is simply the state moving funds from one part of itself to another. This thesis is to be analysed in two parts, first I shall go over what it takes for a group to be considered as an arm of the state, and second I shall look at whether the taxation of such an entity really is just moving funds around.

To understand the first half of the thesis, Austrian, or more precisely Hoppean, class theory must be elucidated. Under this theory, the two classes consist on the one hand of producers, homesteaders, and traders, this is called the productive class, and on the other hand of those who expropriate the wealth of producers, homesteaders, and traders, this class is the anti-productive class.[fn:10] It is those organisations that are anti-productive that are called the state, as Franz Oppenheimer puts it, these entities make their wealth through the political as opposed to the economic means. Of particular import here is that to be truly anti-productive, simply receiving some benefits from the state is not enough, you must actually be petitioning for the expropriation of others, similarly to how it is not a crime to say "gee, I wish someone would do something about Jeremy," but it is a crime to order one of your henchmen to kill Jeremy.

From this, we could say that lobbying politicians to expropriate ones competition in order to get a subsidy is a crime, but simply minding your business and accepting a subsidy that comes along is not. After all, if the latter was criminal, every person who received a stimulus cheque is now a state-actor who may now be justly taxed.

So to the extent that Disney lobbies[fn:11] for expropriation they are committing a crime, a crime that demands retribution, but in what form is this retribution? Giving money to the state? That hardly seems right---the state wasn't the victim after all. But surely Disney's anti-productive lobbying makes them part of the state though, right?

This has two issues, first Disney is hardly /characterised/ by anti-productive income, their anti-productive activities do exist and are legally relevant, but they do not sit around taxing people all day without bringing anything to the fold. Disney produce many products that evidently consumers enjoy to a great extent---granted their market share is undoubtebly warped by their constant pushes for aggressive intellectual property protections, but not warped from 0. The state on the other hand is warped from 0, it does not engage in productive activities which you are allowed to not take part in.

Second, even if we classify Disney as a part of the state, we have the larger state, namely the US federal government, attempting a destruction of this smaller state through a policy of taxing it into submission. Having Disney as a state implies that its actions are state-secessionary, secession being something that is to be supported by libertarians as it is a truncation of a larger state into two smaller ones. This puts DeSantis in the position of Lincoln during the War of Southern Secession, a fact which I am sure makes neo-prags very queasy.

* CTA
If you have enjoyed this response to the anti-Disney-pro-DeSantis-neo-prag wave, you have to watch this video where I point out the core flaws of neo-pragmatism as such, this will allow you to more effectively understand the flaws in their reasoning so that you will already know what missteps they are making in the future.

* Footnotes

[fn:1]Giulia Heyward, "Why Did DeSantis Revoke Disney’s Special Tax Status? What We Know." ([[https://archive.ph/dImkm][archived]])

[fn:2]https://disneyworld.disney.go.com/guest-services/park-security/

[fn:3]https://www.firerescue1.com/fire-careers/articles/reedy-creek-the-happiest-fire-department-on-earth-2hhZHnFvOF73Mevr/

[fn:4]https://disneythemeparks.fandom.com/wiki/Reedy_Creek_Emergency_Services

[fn:5]https://en.wikipedia.org/wiki/Reedy_Creek_Energy_Services

[fn:6]https://en.wikipedia.org/wiki/Disney_Transport

[fn:7]Hiller, Jake (January 28, 2019). [[https://www.forbes.com/sites/edfenergyexchange/2019/01/28/why-disney-world-is-betting-on-clean-energy/#41dcfc7c6722]["Why Disney World Is Betting On Clean Energy"]]. /Forbes/. Retrieved March 7, 2019.

[fn:8]James Conca, "Disney World Could Have Gone Nuclear." ([[https://archive.ph/EfqNy][archived]])

[fn:9]For this see Ryan McMaken, "[[https://mises.org/wire/answer-unfair-tax-breaks-more-tax-breaks][The Answer to "Unfair" Tax Breaks Is More Tax Breaks]]," ([[https://archive.ph/NTj06][archived]]), debunking Ryan McMaken, "[[https://mises.org/wire/disneys-corporate-welfare-modern-mercantilism][Disney's Corporate Welfare Is Modern Mercantilism]]," ([[https://archive.ph/hHite][archived]]).

[fn:10]See on this, Hoppe, Hans-Hermann. "Marxist and Austrian Class Analysis." /Journal of Libertarian Studies/ 9, No. 2 (1990): 79–93.

[fn:11]https://www.opensecrets.org/federal-lobbying/clients/summary?cycle=2021&id=d000000128, https://archive.ph/3VkOM
