#+title: The Death of Liberalism

[The welfare state killed liberalism.] Liberal philosopher Herbert Spencer traces the origins of this ideology back to the Whigs of the English Restoration period---they challenged the popular notion at the time of the absolute power of the king to rule as he pleased, advocating instead that the people be allowed to manage their own lives as they saw fit.

The enlightenment with its massive boost to human welfare and flourishing would be the result of the liberalism that the whigs would foster and provide philosophical ammunition for, but this would unfortunately also lead to their downfall. Slowly, liberals lost sight of their natural rights roots, moving instead to focusing on the prosperity that adherence to the rights of people made possible. Thus instead of fighting for a reduction in government absolutism, the new liberals sought to use the violent powers of the state to secure the results that were only borne by the negation of that very same power.

Ultimately, any deviations from the core natural rights principles of the original liberalism on pragmatic grounds can only ever lead to death and misery---and that is how the welfare state killed liberalism.
