#+title: You Might Already be an Anarchist (TIK Response) | Are You Already an Anarchist? | Are you a good person? Then you are probably an anarchist. | Why You Should Be An Anarchist | Anarcho-Capitalism: Responding to the Critics

* Animations [6/45]
+ [X] reasons people aren't anarchists:
  1. means total chaos
     + go up and have "in an anarchist society there would be no centralised government to enforce the law, so there would be total chaos" come out
  2. rejects human nature
  3. immoral
+ [X] substituting the /result/ that the claimant expects would come from anarchy for the /definition/ of anarchy.
+ [X] anarchism definition: rejection of legal authoritarianism
  + legal authoritarianism definition comes out
+ [ ] Robinson crusoe on the island, finds a stick poking out of a tree, imagines that it could be used to spearfish, fashions a point into it, runs to the ocean to give it a go, friday sees the stick and thinks it would allow him to stoke his fire, runs up to crusoe to try and take it off of him
  + they try to justify their conduct:
    + Crusoe: its his stick because he found it first and was already using it before friday came over and tried to take it from him
    + Friday: he wants the stick, villaige elder said Friday is the stick-keeper, etc.
+ [X] legal anarchism \ne no laws
+ [X] venn diagram with anarchism as such only telling you what anarchism isn't, anarcho-capitalism tells you what it is
+ [ ] Crusoe spearfishing with the stick as mutually-exclusive with Friday using the stick to stoke his fire
  + pic of stick = scarce could be up top with two arrows coming out pointing to each of the actions, where they can't both be highlighted at the same time
+ [ ] Tik's definition of anarchism: an ideology that is opposed to the state
  + the state = any "public" hierarchy
+ [ ] standard for "public" vs "private" is size
+ [ ] private and public as package deals (have the words "private" and "public" on screen and then the package terms come out of them to beneath)
  + private: small, individual, collective
  + public: large, collective
+ [ ] bigness vs smallness as the incorrect criterion; collective vs individual is the correct one
+ [ ] private: belonging to or for the use of one particular person *or group of people* only---turn the text red as it is infected with collectivism
  + choice isn't between individualism or collectivism, its between small- or big-collectivism
+ [ ] The collective as the really real thing.
  + have a circled set of circles. With the individual as the real thing, the dots are highlighted and the circle is greyed out, and vice versa
  + could have the outline circle slowly waving around and the internal circles could be floating about
+ [ ] abstraction of a concept from particulars
  + have a number of particulars that slightly vary, and then the general concept is drawn out. Perhaps simple shapes or dogs
+ [ ] The Platonists telling hobbes that the mind is supernatural, Hobbes then rejecting the mind
+ [ ] materialist metaphysics
  + [ ] title Materialism comes up, with examples coming up below it: [0/3]
    + [ ] particles studdied by the physicists
    + [ ] chemicals studied by the chemists
    + [ ] no such thing as purpose
+ [ ] billiard ball metaphysics
+ [ ] sensualist account of sense perception
  + "His idea, in basic terms, is that external matter strikes our body in specific locations which then sets of a chain of various oscillations and motions towards the brain according to the laws of mechanics---and sensation is the way in which we experience motions in the brain. What it means to "experience" anything if there is no such thing as a mind, nor why we only experience these motions in the brain but not elsewhere is left entirely unclear, which is a bit of a problem."
+ [ ] primary/secondary quality distinction
  + "that our senses only pick up distorted impressions of what is "really" out there, such that the real world is not remotely what it appears to be. In actual fact, this position has it, the real world is colourless, soundless, temperatureless, odourless, etc. All that really exists is quantity and motion."
  + table becoming distorted---the phenomenal table vs the noumenal table, splitting off into different headings as described below
  + maybe have two headings listing off the properties of the "fake" world and the "real" world or have rays coming off a table listing colour, sound, etc
+ [ ] senses as invalid on the grounds of thought
  + "senses are invalid"
  + "we know this because of our thoughts"
  + "our thoughts are based on our senses"
  + thoughts based on senses; have arrow come from each pointing at the other with "invalidates" label
+ [ ] state as a monopoly on the use of force (+ a monopoly on the justification of the use of force)
  + "It is my view that Murray Rothbard correctly identified what it is that people mean when they say "state," namely a monopoly on the use of force. They then combine this with legal positivism which almost everyone adopts, and thus conclude that the state is also a monopoly on the justification of the use of force. Such that aggression done by the state or by the state's order is justified, whereas other aggression is not."
+ [ ] "it is wrong to /define/ the state as being coercive or aggressive because the dictionary definitions do not mention coercion, and that I myself appeal to dictionary definitions when it comes to socialism, so it would be improper for me to drop the dictionary all-together on this issue"
  1. It is wrong to /define/ the state as being coercive, because the dictionary definitions do not mention coercion;
  2. I use dictionary definitions to define socialism, so I can't discard the dictionary entirely
+ [ ] epilology as { praxeology, thymology }
  + thymology: the study of particular instances of man-made facts
  + praxeology: the study of general facts about the man-made as such
+ [ ] false alternatives vs proper alternatives:
  + FALSE: a priori vs a posteriori
  + FALSE: reason vs empirical
  + TRUE: conceptual vs perceptual
  + TRUE: general vs particular
+ [ ] determinism as a self defeat
  + "If determinism is true:"
    + "facts of reality -> the determinist accepts this"
      + facts of reality also -> other people don't accept it
+ [X] hierarchy of philosophy animation
  + metaphysics as fundamental, epistemology as dependent upon metaphysics, etc until politics is reached way far up
  + euler diagram
+ [ ] legal authority justifying his rule by having the biggest stick in the land
+ [ ] capitalism <-> anarchism
  + This is why anarcho-capitalism is the only proper variant of anarchist thought. The capitalism implies the anarchism and vice versa. Capitalism implies anarchism because the recognition of full private property rights implies there can be no legal authorities that may flout or change those rights; and anarchism implies capitalism because with no authorities to appeal to, we are left with the non-aggression principle, which implies full private property rights.
+ [ ] Hobbes' state of nature
  + have a bunch of warring men doing anything in their power to expropriate from and invade others; then have "permanent underproduction of security" text come up to label this situation---each individual spends too little on his own defense
+ [ ] collective myth syllogism:
  1. Men are brutes who must necessarily be at war with each other.
  2. Make one of those men a sovereign.
  3. ???
  4. No more war! :)
+ [ ] Animate this: "A rights-protecting violator of rights is simply a contradiction in terms."
+ [ ] "Furthermore, so long as multiple states, $S_1, \cdots, S_n$, exist, just as there is supposed to be constant warfare between $A$ and $B$ in the state of anarchy, so too must there be constant warfare between these different states."
+ [ ] Men are naturally brutish -/-> we need collective security.
  + "...but let's go further and examine this premise [that men are naturally brutish]."
+ [ ] The threat of aggression is a risk, there are two ways to deal with risk on the market:
  1. through your own privately controlled means;
  2. through the use of an insurance agency
     + underline this; "so we must analyse whether defense is an insurable good"
+ [ ] hierarchy of philosophy law as a subset of ethics
  + "Law is the subset of ethics which specifically tells man what he should do with respect to conflicts---should they be avoided or not? When should they be avoided or not? Are they ethically relevant or not? This is the area that law tackles and it obviously depends in the first case on ethics itself."
+ [ ] Objectivism is the philosophy of the primacy of existence with annotated genus and differentia
  + highlight the genus and differentia different colours or something
  + "So, for my definition, that Objectivism is the philosophy of the primacy of existence, the /genus/--the common denominator--is philosophy. Objectivism is a philosophy, like everything else which is a philosophy. What makes Objectivism different to all other philosophies--the /differentia/--is that Objectivism explicitly identifies and applies the primacy of existence to every philosophical issue."
+ [ ] Title: "Objectivism: the philosophy of the primacy of existence."
  + have the stuff after the colon fade in
+ [ ] murderology: "how should men act, including what are the proper methods of murder? Murder is a value to men only if it is the right kind of murder, after all!"
+ [ ] "Metaphysics isn't "what is there, and also what is the world stuff?," epistemology isn't "how do I know and also why are the senses invalid?," and ethics isn't "what should I do about it, and what are therefore my duties?""
+ [ ] the three answers to law:
  1. the law of the jungle---initiate conflicts at your whim;
  2. mixed law---sometimes initiate conflicts, and;
  3. the non-aggression principle---don't initiate conflicts.
     + "first let's consider the law of the jungle---what would a universal acceptance of conflict-engendering norms look like?"
+ [ ] "the property right would rather travel from person to person always being attached to the item itself"
+ [ ] Title: ownership \ne possession; follow with other stuff
  + "The issue with this view is that ownership--which we can define as the /right/ to possess a given scarce good--is necessarily distinct from possession. If there is some dispute between $A$ and $B$ over who should be the one to control a given property, then /both/ $A$ and $B$ must pre-suppose this to be the case. $A$ is asserting that though $B$ might be able to actually obtain control, it would nevertheless be the case that $A$ /should/ be the one to control it, and similarly $B$ is asserting that though $A$ might be able to actually obtain control, it would nevertheless be the case that $\textit{\textbf{B}}$ should be the one to actually control it."
+ [ ] "the instant a man tries to defend his conduct by asserting that conflicts should not be avoided and that rights are illusory he necessarily asserts that conflicts should be avoided (when initiated against him) and that rights are real (when the thief is facing a counter-attack)."
+ [ ] different mixed-law systems
+ [ ] "if Crusoe and Friday have a disagreement over how to use a spear, then each party sitting down and giving arguments as to why their use should go forth is quite distinct to each party launching missiles and trying to stab the other to death in order that their use may go forth unimpeded."
* Why People Aren't Anarchists
You probably do not consider yourself to be an anarchist---in fact almost everybody considers anarchism to be an ideology which is completely insane. You might have minor disagreements here and there with other people, but anarchism is surely a whole different level of wrongness.

I am here to tell you that you have been mislead. There are a few different reasons why I think someone might reject anarchism and I will be addressing them all.

#+begin_comment
EN: Have this list show up on screen with motion-canvas:
1. anarchism means total chaos;
2. anarchism rejects human nature;
3. anarchism is immoral.
#+end_comment

* Anarchism as Chaos
** Anarchism Defined as Chaos
On this first point, a typical claim might go like: "in an anarchist society there would be no centralised government to enforce the law, so there would be total chaos." The first error made by this sort of claim is that it is substituting the /result/ that the claimant expects would come from anarchy for the /definition/ of anarchy.

This is an inversion of the correct order of operations: we need to first establish what anarchism actually is before we can determine what results we expect to come about from adhering to it.

Anarchism is a general term that applies to any philosophy that rejects legal authoritarianism.[fn:1] Allow me to break that down; legal authoritarianism is the thesis that the law comes from some authority, or in other words that actions are justified on the grounds that the preferred authority says they are. As an example, say Robinson Crusoe is on the desert island and finds a stick poking out of a tree. He expects that this stick would allow him to begin spearfishing, so he fashions a point onto the end and then runs off to the ocean to give it a go. At this point another man, Friday, sees this stick and thinks that it would be great to stoke his fire; so he runs up to Crusoe and attempts to wrestle it off of him.

If these men were so inclined to attempt to justify their respective conduct pertaining to the stick, let's think about what they might say. Crusoe could argue that it is his stick because he found it first and was already using it before Friday came over and tried to take it from him. Friday then says that this is irrelevant, because he wants the stick and so is justified in taking it from Crusoe. Or perhaps Friday appeals to a villiage elder who said that Friday is the stick-keeper for the whole island, and so that is why he is justified. You can think of any number of different authorities that Friday might appeal to, whether it be himself, that villiage elder, or even some sort of deity that bestowed this power unto him---but the point is that Friday is justifying his conduct by reference to the sayso of an authority. This means that Friday is a legal authoritarian, with Crusoe being the legal anarchist.

It is worth noting on this point that legal anarchism doesn't mean that there are no laws, Crusoe is not asserting that anything goes, rather he is asserting that the law does not come from some authority figure's arbitrary decrees, that it is objective, that it is inherent in nature. Accordingly, anarchism is called a theory of natural law.

Now, which man strikes you as being the more peaceful individual? Surely it is Crusoe. Crusoe was minding his business and then Friday physically attacked him and attempted to deprive him of his means of bettering his own life. This is an important observation: anarchism is peaceful, it is the non-anarchists who bring about chaos.

Anarchism as such does not provide a positive case for what the law is; all it says is that it is non-authoritarian. This does not give us much; it is often entirely unclear which party in any given conflict is appealing to authority, or if either of them are. Thus, we need to turn to a specific subset of anarchism, called anarcho-capitlaism, for our positive case.

Anarcho-capitalism starts by recognising the fundamental problem that law tackles: namely, scarcity. It is only because the stick is scarce that Crusoe and Friday can come into conflict over its use. This requires a specific understanding of the terminology---to say that a given entity is scarce is to say that men can come into conflicts over its use, where a conflict is defined as mutually-exclusive actions. Crusoe cannot use the stick to spearfish at the same time that Friday uses it to stoke his fire---one action excludes the other, i.e. they are mutually-exclusive.

Thus, anarcho-capitalism holds the non-aggression principle as the fundamental starting point for all legal analysis---where aggression means the initiation of conflict. So for the case of the stick, we no longer have to imagine what sort of justification Friday might bring, we can simply see that he is the one who has initiated the conflict, and thus his action is not justified.

** TIKhistory on the Definition of Anarchism
*** TIK's Definitions as Package Deals
It will be shown later on why any claim contrary to the non-aggression principle must devolve into legal authoritarianism and why legal authoritarianism is false. For now, I must address a critique of my semantics here forwarded by TIK. To be clear, TIK agrees with the ancaps on ethics, at least as far as I can tell, he just disagrees with calling it anarchism:
#+begin_quote
Anarchy just means no state. It doesn't mean everything is on fire or people are barbarians. It just means no state.[fn:2]

The problem is that the dictionary definition of what a state is does not mention coercion. The dictionaries vary but the essential definition is that a state is a politically-organised community on a given piece of territory. [...] The idea goes like this: when humans group together they form hierarchies. These hierarchies, when they reach a certain size, get classed as "public" which is when they become states. [...] When you have a large hierarchy of society, that is classed as a state.[fn:3]
#+end_quote

So, on this view anarchism is an ideology that is opposed to the state, where the state is any "public" hierarchy. TIK says here that the standard for what is "public" as against "private" is size. He elaborates on this in another video:
#+begin_quote
"The family did not receive its laws from the city... Private law existed before the city." These families were /private/ families. Privus meaning single or individual meant--and still does--a person or belonging to a small group of people that were separate from public life. In a sense, small, independent, private estates rather than large organisations.[fn:4]
#+end_quote

It is on this front that the entire problem with TIKs rejection of anarchism can be found, because the definition of public as against private that he is using is a package deal.

#+begin_quote
“Package-dealing” is the fallacy of failing to discriminate crucial differences. It consists of treating together, as parts of a single conceptual whole or “package,” elements which differ essentially in nature, truth-status, importance or value.[fn:5]
#+end_quote

On both the private and the public front, TIK engages in package-dealing. For him private means small and either individual or collective (the family unit is just a small collective); and public means large and collective. This is clear to see 33:00 into his video on public vs private when he classes "big business" under the same term as "central banks" and "State."[fn:6] This is where the package comes from, the historical association has been that the only way for a society to become large-scale and have any "big" groups within it is for those groups to rule everyone else. So, if we have a society where each individual lives peacefully with everyone else, and operates purely on production and trade, is each person a state? I'm tempted to say they are if there can be multiple "states" in ancapistan like TIK says,[fn:7] but all of these interactions are individual, i.e. private, i.e. non-state. So then perhaps the "state" here encompasses the entire private society, but then we are back to the assumption that the only way for there to be a society is for there to be subjects who are ruled by the same central authority. This is a problem.

TIK justified his classing of big business as "public" here using the Rothbardian argument against natural monopolisation. The argument is basically that as a firm grows in size within some particular market it has a growing internal economy that it cannot perform calculation within. If you want to understand this point fully I suggest you watch this video on the economic calculation problem[fn:8]---but I do not think understanding that is required here.

This argument is correct as far as it goes, but it does not go as far as TIK needs it to go. The Rothbardian argument establishes only that it is impossible for a purely voluntary firm to establish a stranglehold over an entire market and achieve natural monopolisation. It does not establish that no business can ever become very large in either real or relative terms. In real terms, it is obviously possible for a firm in a society with a high level of capital development to be "big" in comparison to Crusoe on the island; and it is also possible for a firm to come to some brand new and very valuable innovation that rockets them to the top of an entirely new market for some period of time. Thus "bigness" vs "smallness" is not the key criterion we must work upon here. The correct criterion is collective as against individual. The actual public entities such as the state or central banks operate through aggressive means, they do not function on the traders principle---rather they rely on being economic parasites sucking the blood of the productive men in society. Those productive men may or may not control vast wealth, because the wealth or the bigness is not the key component.

Notice how this applies also on the private side of TIKs definitions; he tells us that "private" means belonging to or for the use of one particular person *or group of people* only. The inclusion of the group here is the infection of the term with collectivism. Thus the choice we are given is not between individualism or collectivism, it is between small- or big-collectivism. Group ownership is not possible, it is a contradiction in terms.[fn:9] The idea of group ownership comes about out of pure Platonism---the idea is that the collective is the really real thing, and that the individual is merely a subsidiary, or cell of the collective body. /That/ is the proper division between public or private---not whether things should be big or small, but whether the political unit and standard of value is the one or the many, the individual or the group, Howard Roark or Henry Cameron's Egregore.

The key insight to be gleaned here is that definitions are not and cannot be arbitrary labels for whatever you want---the words that one uses must conform to the requirements of man's conceptual faculty. It is the science of epistemology that teaches us said requirements. The primary purpose of language is to objectify concepts,[fn:10] these concepts are formed by abstracting away from concrete data which actually exists. Thus the concept itself isn't out there in the world ready to be seen and recalled at a moment's notice, but by using a symbol to stand in its place you make it perceptually graspable.

Any definition that relies on a package deal is thus an anathema to the very purpose of language in the first place: instead of aiding man's conceptual faculty, it hinders it. Package deals are not valid concepts, and cannot be knowledge. Any analysis that relies upon them must therefore be entirely discarded. Anarchy accordingly does not mean the absence of aggression /and/ the absence of bigness, these are separate concepts that must be analysed separately. The absence of bigness is already captured by the concept of non-society. It is when you don't have a society that you just have lone individuals wandering out and not interacting with others. Thus the proper way to understand anarchy is to throw out the bigness aspect and have anarchy be the absence of aggression. Certainly, if you have no interactions between anyone ever, i.e. non-society, then you will have an absence of aggression. But the alternative to this is not aggression + society. You can have a society without aggression.

*** The Nominalist Origin of TIK's Anti-Concepts
The theory of concepts that TIK is counting on in his use of historical definitions above all else, is called nominalism. Nominalist arguments have been maintained throughout the history of philosophy, going right back to the Ancient Greeks, but in the context of modern philosophy, the man we must look to in order to understand nominalism is Thomas Hobbes.

Hobbes comes onto the scene during the renaissance, and was deeply influenced by the new, scientific attitude that was proliferated at the time. He constructed his philosophy using the methods found in geometry. That is: he would start with basic axioms, which are then used to produce lemmas, and draw further implications, until you have an entire system. The axioms he chose were the basic premises of modern science. He was second-rate in this sense---unlike better philosophers, he merely accepted the principles that were proliferated by others without questioning them.

The Platonists would tell him that the mind is supernatural, he would accept this on its face, and by that token reject the faculty of consciousness. Hobbes was accordingly a total materialist on metaphysics---everything is matter in motion, just like the particles studied by the physicists, or the chemicals studied by the chemists. Thus there is no such thing as purpose, or goal, there are only what Aristotle called "efficient" causes---i.e. all of existence is like a big swirling mess of billiard balls whose motion is entirely pre-determined by the laws of mechanics.

Of course, by the time Hobbes gets to his epistemology--like all materialists--he has to smuggle in the mind, as that is the very faculty that epistemology studies. Again here, he merely accepts a pre-established position, namely empiricism---that all knowledge is based on the evidence of the senses; there are no innate ideas or mystic means of gaining knowledge on Hobbes' philosophy.

How then does he account for sense perception on purely materialist grounds? His idea, in basic terms, is that external matter strikes our body in specific locations which then sets of a chain of various oscillations and motions towards the brain according to the laws of mechanics---and sensation is the way in which we experience motions in the brain. What it means to "experience" anything if there is no such thing as a mind, nor why we only experience these motions in the brain but not elsewhere is left entirely unclear, which is a bit of a problem.

This is compounded further by his acceptance of what philosophers call the primary/secondary quality distinction---that our senses only pick up distorted impressions of what is "really" out there, such that the real world is not remotely what it appears to be. In actual fact, this position has it, the real world is colourless, soundless, temperatureless, odourless, etc. All that really exists is quantity and motion. So, for Hobbes, we know that the senses are invalid through a process of thought, and that thought is based on the evidence of the senses; so thought is supposed to invalidate that which it is based upon. You can see, I'm sure, how the materialist position is leading Hobbes to total epistemic suicide.

Allow me to draw out just one aspect of that as it pertains to concepts. For Hobbes, thought is merely an image---a decaying sense experience. The idea is that these motions and oscillations in the mind slowly fade away over time into noise. Because this applies to all thought, it applies also to concepts. This position is called sensualism---that all cognitive elements are sense perceptions. That the only cognitive faculty possessed by man is that of sensation.

Of course, on this view where all man can do is sense things, the only thing he can be cognisant of is particulars. In other words, on this view, it is not possible for man to abstract away from a number of particulars to form concepts.

This brings us squarely to nominalism: that concepts are merely linguistic conventions, collective names arbitrarily imposed by men on roughly resembling particulars on the standard of subjective human convenience. That there are no /real/ universals, particulars are the only things that exist. That man /creates/ classes of objects, rathers than discovering them.

This nominalist-sensualist position, which has been grafted onto empiricism since the renaissance, yields disastrous consequences on philosophy. There can be no meaningful definitions on this view, a definition is supposed to be a statement of the essence of some class; but if classification is subjective and arbitrary, so too must definitions be. Definitions can no longer be stated to be true or false, just convenient or inconvenient---and there can be no objective standard of convenience! This then means that there can be no general principles. If one says that man is mortal, or socialism is slavery; he is counting upon the definitions of those terms. But those definitions are now said to be arbitrary, and so the general statements are also arbitrary and so falls away general objective principles. Every dispute over principles thus falls into the well of being a merely semantic disagreement over how we are going to use words, rather than an actual dispute over what is true or false.

As Peikoff states the point:
#+begin_quote
Now for instance our communist comes in and says: "I have my own definition of slavery. Slavery by my definition [...] is the state of being wrapped up in bondage to your own selfish interests, whereas true freedom I define as the state of being released from confining personal concerns and being compelled to serve and love your brothers."

Well, if slavery is being egoistic and freedom is being compelled to be self-sacrificial--and this is the Platonic-Hegelian definition of freedom and slavery--then socialism is freedom, and capitalism does rest on slavery.[fn:11]
#+end_quote

Now here at least, the communist is asserting that their definition is correct and mine is incorrect, so there is a possibility of debating who is right and how the words should be used. The nominalist on the other hand completely rejects that its possible for a definition to be anything other than a linguistic contract of sorts.

Thus when TIK says that the standard of which words should be used is those which are most accepted and can thus be used to communicate,[fn:12] and when he takes the historic definition above all else, he is implicitly adopting the nominalist viewpoint. That is to say: the fundamental principle underlying definitions is not communication. Words are not mere linguistic playthings that we may select at will and the standard of their truth is not that people use them in that way. Definitions can be objectively correct or incorrect on epistemic grounds---and thus epistemology must be employed when we are choosing which definition to adopt.

Now, I don't think that TIK is a raging Humean or anything like that---but this is an area where I think he is not applying the correct methods of epistemology. He must take into account not only how the words are used, but more fundamentally what the requirements of man's mind are.

*** The Rothbardian Definition as Identifying the Essential !!!HERE!!!
Furthermore, I also don't think that TIK's understanding of the state just being a large collection of people lines up with what most people think. It is my view that Murray Rothbard correctly identified what it is that people mean when they say "state," namely a monopoly on the use of force. They then combine this with legal positivism which almost everyone adopts, and thus conclude that the state is also a monopoly on the justification of the use of force. Such that aggression done by the state or by the state's order is justified, whereas other aggression is not.

This is why people are fine with the government stealing their money, but not a random thug on the street. After all, if you believe that there is a legitimate monopoly on the use of force, then that monopoly gets to decide that certain aggressions are fine by pure fiat. A monopoly means that you are excluding competition, this means that if the state is justified it must be justified in preventing people from defending property on their own, and therefore the state must be operating under legal authoritarianism.

Now, I want to be clear here on one point---TIK brought up in his video[fn:13] that it is wrong to /define/ the state as being coercive or aggressive because the dictionary definitions do not mention coercion, and that I myself appeal to dictionary definitions when it comes to socialism, so it would be improper for me to drop the dictionary all-together on this issue. First, I agree on the point that it is incorrect to make the state coercive by definitional fiat; but I do not think that this is what the Rothbardians are doing. Rather, Rothbard has identified that the essence of the state is to be anti-productive, parasitic, monopolistic in the arena of the use of force at the very least. Then on top of that he has a separate legal theory which identifies those activities as being nocent. So its not that the state is that organisation that is bad; its rather the state is an organisation that engages in certain activities that we have separately identified as being bad. As for the point that I use dictionary definitions myself in arguing that socialism is when the government does stuff this does not contradict the previous analysis of certain dictionary definitions being invalid. Those definitions were not based on package deals or any other such flawed epistemology, and in fact identified the proper essence of socialism---that socialism is when the government does stuff.

This is why it would be invalid for socialists to change the definition of socialism to be when puppydogs and rainbows happen[fn:14] as that would not be digging down to the essentials. Rather, what a definition like that is doing, is it is substituting the expected outcome of some system for the system itself---i.e. it is packaging together what effects they think would occur with the things they think will cause those effects. This is invalid; the definition in this case needs to identify the cause, and then further analysis can be performed to determine what the effect of that cause will be. The change I propose to the definition of the state is of a different sort---it is not an invalid poisoning of a term, it is the removal of an already established poison. My claim is that the current dictionary definitions that TIK is working on are in fact obfuscating the core, and that this obfuscation should be removed.

*** Praxeology as Mystic?
Due to the time taken to make this video, TIK has released a further video where he draws a connection between the Austrian tradition that anarcho-capitalism is built on with the mystic philosophy of Immanuel Kant:
#+begin_quote
From John Locke and Kant we eventually get Ludwig von Mises, and the Austrian school of economics. And to prove the connection from Kant to Mises, here is an article from [the] Mises Institute /this year/ titled: "On Immanuel Kant's 300th birthday: Kant's Epistemology and Its Influence on Ludwig von Mises's Praxeology."

From the body of the article itself: "In the epistemological works of Ludwig von Mises (1883–1971), there are not only clear parallels with but also lines of reference to Kant’s theory of knowledge: Mises not only employs the term a priori and occasionally references Kant, but also rationalizes the use of a priori knowledge as the appropriate method for the social and economic sciences – the logic of human action (“praxeology”)." Do not shoot the messenger guys.

I know the Austrians have historically challenged Hegel, so I know they're not Hegelians, but yes, Mises' a priori reasoning actually comes from immanuel Kant's explanation of that meaning that there is a Kantian influence here. This is problematic because they have allowed mysticism into their movement. *This might not affect their basic economics as such, but it does affect the more in-depth stuff and their politics*.

And this has been one of the reasons why I have been hesitent to say where I sit on the political spectrum. Part of it is that I don't want to pigeon-hole myself, but part of it is because when I was reading Mises and Rothbard, I recognised that something wasn't quite right with the logic. I couldn't explain it, but I saw it and expected it, and I now think I understand why but that's a topic for another day. The point is for today that this Kantian influence is there.

But Ayn Rand is absolutely not influenced by Kant or Hegel whom she totally rejects. Her connection comes from Aristotle via Thomas Aquinas and is based in modern science. But she also rejects all religion so Objectivism is not mystic in any way, at least not consciously. And Murray Rothbard had been part of Ayn Rand's group, but broke from the movement for reasons I'm not entirely clear upon. He then accused her of founding a cult which is ironic given the Kantian influences on his movement.[fn:15]
#+end_quote

To be clear, I think this video is mostly correct; I even agree that this connection between Kant and Mises has allowed some mystic elements to remain within the modern Austrian school. This is why my philosophical project, which is to integrate Objectivism and anarcho-capitalism is so important; and I will explain more on that later in the video when I respond to Ayn Rand's points against anarchism. Regardless I do have some things I want to address here.

First, I completely reject the claim made by the article that any so-called "a priori reasoning" forms "the most robust epistemological foundation" for economics, or even praxeology. And I further reject that praxeology is even close to being a sensible science on Kant's philosophy. This is because praxeology is just a certain science built on top of the understanding that humans have free will. Following the naming schema used for "praxeology," I propose that any science of free will falls under the banner "epilology,"[fn:16] namely epilology includes the sciences praxeology and thymology---with thymology studying particular instances of man-made facts, and praxeology studying general statements on the man-made as such.

This gives us the proper conceptual distinction--not between a priori and a posteriori, or supposed facts of "pure" reason as agaisnt "mere" empirical and contingent facts--but between the conceptual and the perceptual---the general and the particular. For far too long, the Austrian school has swallowed the poison pill that empiricism cannot yield general and necessary truths, so they have turned to the evil mysticism of Immanuel Kant, turning themselves away from reality to try get a better grasp of it.

After all, the Objectivists have already provided a rational, this worldly, scientific account of free will, and shown that without it epistemology itself falls.[fn:17] The basic idea is that if determinism is true, then the determinist is pre-destined to accept this position. How, then, does he hope to validate it? The factors that caused him to be a determinist are clearly not infallible, as those same factors caused other people to not be determinists---so he must accept that man can think in error. Given the determinist's mind is not automatically attuned to reality, and he claims that he has no choice over what he believes, then he cannot validate any belief that he holds---the determinist claims that on his own premises he cannot deliberately choose reality over fantasy.

#+begin_quote
The concept of “volition” is one of the roots of the concept of “validation” (and of its subdivisions, such as “proof”). A validation of ideas is necessary and possible only because man’s consciousness is volitional. This applies to any idea, including the advocacy of free will, to ask for its proof is to presuppose the reality of free will.

[...]

The determinist's position amounts to the following. “My mind does not automatically conform to facts, yet I have no choice about its course. I have no way to choose reality to be my guide as against subjective feeling, social pressure, or the falsifications inherent in being only semiconscious. If and when I distort the evidence through sloppiness or laziness, or place popularity above logic, or evade out of fear, or hide my evasions from myself under layers of rationalizations and lies, I have to do it, even if I realize at the time how badly I am acting. Whatever the irrationalities that warp and invalidate my mind’s conclusion on any issue, they are irresistible, like every event in my history, and could not have been otherwise.” If such were the case, a man could not rely on his own judgment. He could claim nothing as objective knowledge, including the theory of determinism.[fn:18]
#+end_quote

So, the Austrians are correct to embrace a methodological dualism and reject the application of the methods used to study particles and chemicals to the study of man---but not because the study of man is non-empirical. Rather, when one studies human action, he must take into account the fact of free will.

This integration between Objectivism and anarcho-capitalism is not idiosyncratic either. Murray Rothbard himself was an Objectivist[fn:19] +and the link between him and Rand deserves to be re-instated on TIK's chart+.[fn:20] As Rothbard himself explains:
#+begin_quote
I just finished your novel today. I will start by saying that all of us in the "Circle Bastiat" are convinced, and were convinced very early in the reading, that Atlas Shrugged is the greatest novel ever written.

[...]

But the truly staggering thing about your novel is the vast and completely integrated edifice, of thought and of action: the astounding infinity of rational connections that abound, great and small, throughout this novel. Joey says she used to wonder how a novel could take you over ten years to write; she now wonders how you possibly could have written all that in a mere ten years. Every page, almost every word, has its meaning and function. I am sure that I have only scratched the surface of tracing all the interconnections, and a good part of my conversation consists of saying; and what of page so-and-so: do you see how that fits in?

[...]

To find one person that has carved out a completely integrated rational ethic, rational epistemology, rational psychology, and rational politics, all integrated one with the other, and then to find each with the other portrayed through characters in action, is a doubly staggering event. And I am surprised that it astonishes even I who was familiar with the general outlines of your system. What it will do the person stumbling upon it anew I cannot imagine. For you have achieved not only the unity of principle and person, and of reason and passion, but also the unity of mind and body, matter and spirit, sex and politics... in short, to use the old Marxist phrase, "the unity of theory and practice."

[...]

I want you to know that, even without seeing you, you have had an enormous influence upon me---even before the novel came out. [...] When I first met you, many years ago, I was a follower of Mises, but unhappy about his antipathy to natural rights, which I "felt" was true but could not demonstrate. You introduced me to the whole field of natural rights and natural law philosophy, which I did not know existed, and month by month, working on my own as I preferred, I learned and studied the glorious natural rights tradition. I also learned from you about the existence of Aristotelian epistemology, and then I studied that, and came to adopt it wholeheartedly. So that I owe you a great intellectual debt for many years, the least of which is introducing me to a tradition of which four years of college and three years of graduate school, to say nothing of other reading, had kept me in ignorance.[fn:21]
#+end_quote

Barbara Branden further notes in her biography of Ayn Rand that:
#+begin_quote
Though disagreeing with Ayn Rand's key concept of limited government, Murray Rothbard has stated that he "is in agreement basically with all her philosophy," and that it was she who convinced him of the theory of natural rights which his books uphold.[fn:22]
#+end_quote

I would certainly reject that limited government is a "key" concept within Objectivism---politics is held as being a very remote branch of philosophy. But as stated I will address that point more fully later in this video. I would like to give some indication here as to why it is that Rothbard is basically never cited as an Objectivist, if he is indeed one. Unfortunately, because of the Randians refusal to re-publish works without explicit permission, many of the sources on some of the things I will state here point to ancient websites that have since lost the relevant documents, so I can go only on things that I have heard other people saying. If any Randians get pissy about this, they are free to present the relevant information in a form that has not been lost from the internet.

I think that one of the major reasons why Rothbard is never called an Objectivist is one of the many disputes he had with Rand---namely that he neglected to cite Ayn Rand and her associates as sources. His reasoning is supposedly that he did not want a novellist to appear in the bibliography of any academic work. In Rand's place, Rothbard would cite Aristotle and St. Thomas Aquinas as sources for things such as the law of causality, or natural rights. I conjecture that this is the reason why you frequently find Rothbard being called a neo-Thomist, or neo-Aristotelian rather than an Objectivist. That is, the various dramas that went on between two people more than half a century ago have since impacted the movements they founded, such that modern anarcho-capitalists refuse to align with Ayn Rand "because that's what Rothbard did" and vice versa for Randians often refusing to even consider whether further developments in legal philosophy can be made.

When it's all said and done, I think it is frankly ludicrous that people who live decades after everyone involved in the various beefs have long since passed would still hold onto these grudges to the extent that they shut down their mind at any mention of debate. Yes, whether Rothbard plagiarised from Rand might be relevant to a moral evaluation of Rothbard-the-man; but it is not relevant to any evaluation of anarcho-capitalism the legal theory. And, yes, whether Ayn Rand was a meany-pie to people who disagreed with her might be relevant to a moral evaluation of Ayn Rand-the-person; but it is not relevant to any evaluation of Objectivism the philosophy.

It certainly isn't /every/ Objectivist or /every/ anarcho-capitalist who operates in this way, but it is enough that it is worth calling out here: drop the beefs of dead people---they are utterly irrelevant.

There is one last point on this front, which is that Rothbard did make frequent use of the Kantian terminology. He explains why he does so, despite not being a Kantian:
#+begin_quote
Whether we consider the Action Axiom "a priori" or "empirical" depends on our ultimate philosophical position. Professor Mises, in the neo-Kantian tradition, considers this axiom a /law of thought/ and therefore a categorical truth /a priori/ to all experience. My own epistemological position rests on Aristotle and St. Thomas rather than Kant, and hence I would interpret the proposition differently. I would consider the axiom a /law of reality/ rather than a law of thought, and hence "empirical" rather than "a priori." But it should be obvious that this type of "empiricism" is so out of step with modern empiricism [i.e. nominalism-sensualism] that I may just as well continue to call it /a priori/ for present purposes. For (1) it is a law of reality that is not conceivably falsifiable, and yet is empirically meaningful and true; (2) it rests on universal /inner/ experience, and not simply on external experience, that is, its evidence is /reflective/ rather than physical; and (3) it is clearly /a priori/ to complex historical events.[fn:23]
#+end_quote

So, from the very beginning, anarcho-capitalism and the Rothbardian wing of the Austrian school owe their fundamental philosophy to Ayn Rand---not Immanuel Kant.

** The conflation of Jungle Ethics with Anarchism
Moving on from TIK now, I must address those who would seek to call anarchism chaotic by conflating it with the law of the jungle---the idea that anything goes as far as law is concerned. Recall above that anarchism must be opposed to legal authoritarianism---the theory that the correct way to resolve conflicts is by appealing to some authority. Notice then that the law of the jungle in its many forms therefore cannot be anarchist. If the claim is that might makes right, then the mighty justify their claim by demonstrating that they are the authority on law by virtue of having the biggest stick in the land. Certainly, this is not anarchist in the slightest. Anarchism does not mean no laws, having no laws is impossible---anarchism rather means that those laws are natural and peaceful.

This provides a retort also to the various other primitive, brutish, and/or stupid varieties of supposed-anarchist thought: chief among them the "anarcho-communists." The term itself is a clear contradiction. Communism holds that total metaphysical, epistemic, ethical, aesthetic, and legal authority lies with the collective---and that accordingly the proper way to resolve conflicts is for the individual to be crushed under the boot and be made to be a complete slave to the whims of the egregore. The communist cannot, therefore, appeal to any naturalistic understanding of which individual ought be given precedence in some conflict, as he does not recognise the individual as being a self-sufficient existent in the first place.

This is why anarcho-capitalism is the only proper variant of anarchist thought. The capitalism implies the anarchism and the anarchism implies the capitalism. Capitalism implies anarchism because the recognition of full private property rights implies there can be no legal authorities that may flout or change those rights; and anarchism implies capitalism because with no authorities to appeal to, we are left with the non-aggression principle, which implies full private property rights.

The origin of this conflation between anarchism and jungle ethics is found in those who freeze legal positivism to the broader abstraction of law:
#+begin_quote
A fallacy which may be termed "the fallacy of the frozen abstraction" [...] consists of substituting some one particular concrete for the wider abstract class to which it belongs---[e.g.,] substituting a specific ethics (altruism) for the wider abstraction of "ethics." Thus, a man may reject the theory of altruism and assert that he has accepted a rational code---but, failing to integrate his ideas, he continues unthinkingly to approach ethical questions in terms established by altruism.[fn:24]
#+end_quote

Legal positivism is one specific theory about what the law is, namely it is the thesis that the existence and content of law depends upon social facts, and not on its merits.[fn:25] In other words, the legal positivist claims that law is "posited," i.e. decreed by some authority, rather than discovered by jurists. This leaves us with a gross false alternative: arbitrary law declared by politicians vs arbitrary law declared by bandits; agression vs agression; might vs might. It is the dictum of every great villain in the history of philosophy: heads I win, tails you lose.

#+begin_quote
Fight the doctrine which slaughters the individual with a doctrine which slaughters the individual. Give up your soul to a council--or give it up to a leader. But give it up, give it up, give it up. My technique, Peter. Offer poison as food and poison as antidote. Go fancy on the trimmings, but hang on to the main objective. Give the fools a choice, let them have their fun--but don’t forget the only purpose you have to accomplish. Kill the individual. Kill man's soul. The rest will follow automatically.[fn:26]
#+end_quote

The jungle anarchist accepts and furthers the brutish violence vs brutish violence false alternative; taking up the side of disorganised aggression as against organised aggression. He never stops to check his premises and question whether aggression is required in the first place. He merely asserts that somebody's got to rule, so its better if that ruling is done by syndicates, or cooperatives, or random Stirnerites rather than a union of syndicates, or democratic republic, or a specific Stirnerite called "dear leader." Surely this is as far from any reasonable conception of anarchist as one can come. Indeed, these anarcho-idiots are entirely correct to segregate anarcho-capitalism from their various moronic and/or brutish creeds, as they nearly universally do. When you see such attempts made to kick out anarcho-capitalism from the flag of "mother anarchy," you should not protest their disassociation from us. Rather, you should embrace this and point out that they are distancing /themselves/ from anarchism. Their facts are correct, but their evaluation is sorely reversed.

** The Private Production of Defense
*** The Myth of Collective Security
Now that it has been established that anarchism is definitively not chaos, it is worth explaining exactly how defense services could be provided on the free market. After all, some people are criminal, and the free society would need a way to deal with them. It is a general rule of economics that a free market can more efficiently provide any good than state central planning;[fn:27] however, because of that it is not possible for me to explain the specific bureaucratic structure that would obtain on the market to provide the service of defending one's rights. Just as it wouldn't be possible to explain what the restaurant industry would look like before one had developed. Regardless, it is possible to discuss some likely or possible features that could exist.

First, I must deconstruct the myth of collective security, most prominently advanced by Thomas Hobbes. The destruction he wrought in epistemology by conflating empiricism with nominalism-sensualism can be found in the political realm also---it is accepted by legion political philosophers and economists that a only a state can provide security against invasions of one's property. The argument goes that in the state of nature men are all snarling beasts who are constantly at each others throats, doing anything in their power to invade and expropriate what has been produced by others. In other words, Hobbes has it that there would be a permanent underproduction of security---each individual, left to his own devices, would spend too little on his own defense, thus constant interpersonal warfare would result.

#+begin_quote
The solution to this presumably intolerable situation, according to Hobbes and his followers, is the institution of a state. In order to institute peaceful cooperation among themselves, two individuals, A and B, require a third independent party, S, as ultimate judge and peacemaker. However, this third party, S, is not just another individual, and the good provided by S, that of security, is not just another "private" good. Rather, S is a /sovereign/ and has as such two unique powers. On the one hand, S can insist that his /subjects/, A and B, not seek protection from anyone but him; that is, S is a compulsory territorial monopolist of protection. On the other hand, S can determine unilaterally how much A and B must spend on their own security; that is, S has the power to impose taxes in order to provide security "collectively."[fn:28]
#+end_quote

On its face, even if we grant the premise that men are brutes who must necessarily be at war with each other, it is entirely unclear how exactly this is any solution to this problem at all. Surely the sovereign is just as brutish as his subjects and now has the territorial monopoly and compulsory funding to externalise the costs of his aggression onto a vast array of victims who are forced to pay for their own victimisation. It is clear that this sovereign is no protector at all---rather, he is the greatest brute of them all. A rights-protecting violator of rights is simply a contradiction in terms.

Furthermore, so long as multiple states, $S_1, \cdots, S_n$, exist, just as there is supposed to be constant warfare between $A$ and $B$ in the state of anarchy, so too must there be constant warfare between these different states. Indeed, we do find that states engage in near constant war with each other, so this could be a point in favour of Hobbes and would imply that a world government must be implemented to reduce the level of violence.

However, this point does not account for the actual observed relations between the subjects of different states. These subjects are just as surely in a state of anarchy with respect to each other as they would be without any states at all, but we find that the private dealings between individuals who reside in different countries are for the most part entirely amicable.

Moreover, it is also not clear how such a world government would be an improvement in the provision of security as compared to competing private firms and individual defense. For this state would have to be the winner of all wars, the biggest brute in the land, the most skilled at expropriating its subjects to fund violence and the most capable at engaging in violence ever seen. This would then not be the most protective agency ever, but the complete opposite---it would be the last surviving protection racket. This makes it the biggest danger that any man would face in his life, and it is specifically this danger that Hobbes advocates be free to do as it pleases. At least in his state of nature it is possible for me to overwhelm a single foe who attempts to waylay me on the side of the road---but what possible means of defense could I muster against the giga-Leviathan, which has already proven itself to be superlative at the craft of war?

So the Hobbesian myth stands as completely false and absurd /even if/ one grants the premise that men are naturally brutish---but let's go further and examine this premise. First, man has free will[fn:29] and can as such choose either peaceful productivity or brutish anti-productivity. It is in the world where the philosophy of the day is that of evasion that a correspondent brutishness and statism arise; if the philosophy of the day were one of thought and objectivity, then men would understand that production is the proper way to live. So contrary to the claim at hand, it is not that a state is required to civilise naturally brutish men; rather it is that when men choose brutality they form states to engage in it.

Furthermore, the entire purpose of protecting rights in the first place is to allow for the flourishing of mankind. The reason why Crusoe would want to be free of conflict is so that he can be productive. Thus shifting the infringement of rights onto an institutionalised (protected) anti-productive class is an anathema to the very problem that had to be solved in the first place, as such an institution would tend to maximise the price of protection (i.e. taxes) whilst minimising the quality.

Quite simply, given that the principle of government requires that it be a judicial monopoly with the power to tax, any notion of limiting it's power and safeguarding individual life and property is illusory; necessarily the state tends towards greater expropriation and less protection, because the sovereign is motivated by self-interest (albeit irrational) and the disutility of labour just as anyone else. Why allocate more resources towards protecting citizens than the minimum required to keep them in line and preserve their property for your own future expropriation? On Hobbes, the sovereign would /have/ to do this because he is supposed to be a brute.

Furthermore, even if the sovereign is, contrary to the Hobbesian premise, an angel who wants to try his best to provide the correct level of protection, it is simply not possible for him to do this. He is faced with the unanswerable question of how much security must be rationally allocated. Should he give every citizen a handgun? Should he post armed guards on every street corner? Should he have a police patrol every 10 miles? He cannot answer, because the economic calculation problem stands in his way. I have already explained the ECP in this video,[fn:30] so I will not repeat the explanation here. You can read the full deductive argument on my wiki if you do not wish to watch the video.[fn:31]

Regardless, in the statist society there will also exist a tendency toward a deterioration in the quality of justice, because if one can only appeal to the government for justice and protection, justice and protection will invariably be perverted in favour of the government. Even the constitutions and supreme courts that are supposed to limit this may be interpreted and administered solely by the government---the very agents who are supposed to be limited are the ones who determine what the limit is. "Accordingly, the definition of property and protection will continually be altered and the range of jurisdiction expanded to the government's advantage."[fn:32]

It is in the near universal acceptance of the myth of collective security that we find another odious false alternative. On the one hand, the so-called capitalists accept Hobbes' premises, then conclude that the only way to protect private property is to collectivise the invasions thereof; and on the other hand, the communists will accept the same premises, and claim the banner of anarchism as an anti-capitalist, anti-property stance. We are left yet again with the alternative of collectivism vs collectivism.

*** Defense as an Insurance Good
Now that the fundamental philosophical backing for statism is in ruin, I may build the positive case for the private production of defense. First, the threat of aggression against one's property is a form of risk, and there are two potential ways to deal with any risk on the market: (1) through your own privately controlled means; and (2) through the use of an insurance agency.

So, we must analyse whether defense is an insurable good. After all, I may not take out insurance against /any/ risk that I face---namely, I cannot insure myself against those risks whose outcome I have control over. On the market I could not rightly get insurance against setting my own house on fire, as I could then simply pay in the first premium, set my house alight, and immediately get compensation---such a non-discriminatory insurance firm could not profit.

So clearly a defense insurer could not insure one against any aggression that they themselves provoke. Norms of peaceful, conflict-avoiding conduct would have to be implemented into the contracts which would bind the insured to civilised behaviour. In defending against any risk that is non-insurable, one must utilise their own personal means, which would still be far more effective than the current heavily restricted weapons that the state allows one to possess.

Moreover, any defensive action taken--either by an insurance firm or in personal self-defense--would tend to minimise any collateral damage. This is because if in the process of some defensive action I thereby damage the insured property of innocents I will have to face not a sole aggressor or small gang, but a large firm capable of extracting restitution from me. As such, collectivist weapons such as bombs, weaponised diseases, and chemical attacks would tend to not be used in favour of precision strikes against only aggressive targets. This is quite on the contrary to current statist methods of invasion and retaliation which make frequent use of collective attacks; not caring in the slightest about collateral damage, or in some cases, even maximising collateral damage. After all, when it comes to interstate warfare, killing off the civilian population of your enemy reduces the total pool of taxable resources available to the enemy state in the future.

In addition to this tendency for free-market defense towards precision in lieu of sweeping destruction; any defense insurance firm would have both the incentive to provide effective defense and likely the resources to engage in it. Even in their heavily restricted form today, insurance firms control vast arrays of capital spread across the globe which they can use to compensate anyone who makes a claim on their policy. After all, if an insurer does not have such a warchest of resources, nobody would trust them to have the means to pay up should the time come. Thus they would have to publicly show that they are in control of great capital holdings not subject to the risk of immediate state seizure. Because these firms would have to dip into their own resources to pay off anyone whose property was not adequately protected, they have the incentive not just to vigorously track down and extract restitution from the criminals, but also to efficiently predict and mitigate crime before it happens; which is in stark distinction to the state method of forcing victims to pay for the shelter, feeding, and entertainment of their aggressors through taxation.

This tendency enacts a civilising process, in contrast to the decivilising one created by monopoly "protection" under a state. All other things being equal, men would prefer to have their property under a lower risk of predation; so as the risk of aggression increases, the value of property decreases. On the one hand, in low-risk-high-value (i.e. "good") neighborhoods, insurance rates could be low in accordance with the low risk of predation; and on the other hand, in high-risk-low-value (i.e. "bad") neighborhoods, insurance rates would be accordingly higher. This creates a tendency for productive individuals to move to and invest their resources in good as against bad areas. In contrast, those who are in good neighborhoods under state-monopoly protection are forced to pay more in taxes in order to subsidise those who languish in the bad neighborhoods---shifting resources from civilisation to decivilisation.

Not only does this hypothetical free-market in defensive services have the benefits that there would tend to not be total war, the victims would be compensated rather than the aggressors, and that accordingly resources are shifted away from predation and towards production; but also even current insurance agencies already utilise free market arbitration systems rather than statist courts. These free-market dispute resolution firms would only become more effective and more broadly used without the state forcefully positioning itself as the "true" "court of the land" that may be appealed to if one does not like the just verdicts of private judges.

One final point must be addressed here before the positive case for private defense insurance is complete: namely, in a capitalist society, what methods could free peoples utilise in order to defend themselves against state aggression? First, it is worth questioning /why/ a sovereign would wish to do this in the first place. /Who/ would they be invading? There is no competing sovereign or state in this area to direct his attacks towards, there are only freely associating people, each engaged in their own individual behaviours. These free men would tend to have not aggressed against any citizens in the invading nation, and they would tend to have not provoked any aggressions from the invaders for reasons previously stated. Any individual who was engaged in such provocation or aggression would quickly become unwelcome in the free society, forced to live on the outskirts where the state may simply arrest him without needing to invade. Furthermore, options for casus belli become quite limited without a single collective state to pin grievances onto. Any state must in some way justify its conduct to the men who would be carrying out its crimes, the justification needn't be good, but it needs to exist. There would be no terrorist attacks coming from the free people, the free people would not be seeking any expansionist wars against neighboring territories, and they would be engaged in no internal ethnic cleansings or other such "crimes against humanity" to be used as a justification for attack.

It would be quite the risk indeed for any sovereign to show their hand by attempting to wipe out clearly innocent and peaceful men; far easier to stick to standard inter-state conflict. Indeed, the wars fought by the predominant empire, the United States, are justified on the Hobbesian grounds that there must be a single powerful world sovereign who can overwhelm all others. But these attacks are pointed, then, at other sovereigns, rather than random businessmen and industrialists who do not represent any contest in the ruling of subjects.

However, let's say that a state does find such a cause for invasion--perhaps justified on the grounds that the capitalists are selfishly hogging wealth and exploiting the workers of the world--how could the state expect to win in such a conflict? Recall that the state in its capacity as a monopolistic expropriator of wealth tends to provide lower quality and less efficient services; thus the free capitalists would be in a far superior fighting position per dollar spent. Any invading state would face not disarmed civilians who rely upon a central power to protect them, but the most well-armed population ever seen on planet Earth. Each individual would be capable of neutralising scores of enemy combatants at the flick of his wrist. If the biggest military ever failed to win a war against a bunch of rice farmers living under communism, how would any state stand even the slightest chance against hyper-industry incentivised to immediately deal with any threats that face it, and with the means to do so?

The Randian war-hawks have it that examples such as Vietnam and the various Middle Eastern wars do not demonstrate that America is impotent as a matter of economic necessity, but rather that the American government is impotent by choice. Peikoff has it that if America would utterly destroy the Iranian government, up to and including the glassing of the entire territory with nuclear weapons, that then the military goals of the US are achievable.[fn:33] The assertion is that the US operates as a paper tiger with respect to these regions, wearing kiddy gloves and refusing to use its full might---and that this is why it constantly fails at these military objectives against guerillas.

Putting aside the total moral abhorrence and collectivism inherent in these arguments about using force against civilisans in so-called "enemy territories," it strikes me that this "paper tiger" claim is completely at odds with the example of the Vietnam war. The US military would routinely shell mountain-sides with long-range artillery, burn down entire jungles with napalm strikes, and spray chemical agents over vast swathes of land. In fact, the US military dropped more than double the /entire/ yield of all explosives used in WW2 /including/ the atom bombs during the Vietnam war. All of this and they /still/ didn't take out some commie rice farmers. This hardly strikes me as what a "paper tiger" would do, and certainly points to the fact that guerilla strategies are simply massively successful against giant collectivist militaries.

Furthermore, if we assume that we have an established free region, rather than commie rice farmers, there would have been in the preceding however-many-years a steady brain drain from statist countries to the capitalist society. The states of the world would find themselves with an ever-reducing scientific community to develop weaponry and devise methods of attack.

Insurance firms would also surely recognise the acute threat posed by any neighboring state and would as such charge higher insurance premiums from areas likely to be the target of invasion. These higher premiums would have to be justified by a demonstrable improvement to defensive instalments in these areas. Any insurance firm that hopes to stay in business would have to keep track of statist military movements and capabilities through advanced intelligence services, and would have to be capable and prepared to overwhelm any force that arrives through sufficient equipment and training. Any statist invaders would face long-range precision weaponry that had only been dreamed about in the minds of science fiction authors. It would be very challenging to muster the morale required to send archers and stone-throwers to invade a sophisticated multi-domain and highly-adaptive power.

Insurance firms could also engage in offensive surgical strikes against key state opponents. Any warmongerer could be efficiently dispatched by stealthy assassins or orbital strikes. These offensive capabilities would minimise collateral damage, yielding minimal resistance from state subjects---those subjects could be further imbibed with constant and effective propaganda about how much better life is under capitalism. Any attempted invasion against the capitalists would very quickly yield a decisive response from basically every insurance agency in the area; and perhaps others abroad who wish to discourage war against free people. These invasions could thus very well spell the end of any regime who attempts them, leaving way for all-too-eager coups whose progenitors promise to not invoke the wrath of their military and intellectual superiors.

*** Why Private Defense Services Have NOt Arrived
So, if free market defensive services are so superior to the statist offerings, why have they not arrived? The answer, in short, is that the philosophy of the day does not allow for it. I will be making a detailed video on the philosophy of history that will more-fully explain this point in the future--and in fact the original version of this script contained such an explanation--but for now I must remain brief in giving an explanation of Leonard Peikoff's philosophical theory of history.

The basic premise underlying this idea is that man has free will, and as such the type of society which obtains at any point in history must be the result of the choices made by the men who live in it. Fundamentally, the choices men make will be influenced by the philosophy they hold---if a man believes that knowledge can be gained only by appealing to the mystic divinations of temple priests or Keynesian economists then he will find himself weak and dependent. If the philosophy of the day teaches man that his only moral worth can be found in doing his duty and that this demands he not live for himself, then he will be primed to obey the orders of any tyrant who comes along.

This is the key insight for our topic here. If men broadly accept a philosophy that implies a statist politics, this will practically result in the average man having less and less control over his own life, and more and more dependence upon the government. Through every inevitable crisis that results from such a system, the man will feel ever less in control and ever less able to shape his own life and achieve wellbeing, and he will be accordingly driven deeper into the well of dependence upon the ones who rule him.

All the while the intellectuals spend their time degrading the individual, telling him that his mind is helpless, he cannot know anything, thought is untrustworthy, there are no answers, there are no absolutes, that he must share his wealth, that his race is evil, and that his only goal in life should be to see how fully he can destroy himself for the collective.

Fundamentally, the state makes up a tiny fraction of the population---they cannot control men by brute force. The sovereign counts on men to follow an anti-individual philosophy, such that they will cheer with glee as everything good is destroyed. A philosophy that would shape a free society would have men thinking for themselves, acting independently, working for their own sake and for their own happiness. If this is the philosophy that men accept then it would become the standard that everyone would expect---and as such these would be the standards adopted by institutions and those that men would learn to follow.

For there to be a society that accepts anarcho-capitalism and operates on the terms set by private property, there must first be a rational, this-worldly philosophy accepted by the masses. There must first be an acceptance of Objectivism.

* Anarchism as Immoral
** The Integration of Objectivism and Anarcho-Capitalism
Thus I may now turn my attention towards my aforementioned integration of anarcho-capitalism with Objectivism. In my view, Objectivism is the only proper philosophical basis for the anarcho-capitalist legal theory, and the anarcho-capitalist legal theory is the only proper legal theory on Objectivist philosophy.

First, the need to have a sound philosophy for a sound legal theory comes from the fact that law is a highly remote area of philosophy. Law is the subset of ethics which specifically tells man what he should do with respect to conflicts---should they be avoided or not? When should they be avoided or not? Are they ethically relevant or not? This is the area that law tackles and it obviously depends in the first case on ethics itself. If there are no ethical truths, then there cannot be legal truths either, and we are forced to retreat into subjectivism or relativism. If there are ethical truths but they are intrinsic and come from the mystical dictate of a king or God, this will clearly lead to a legal philosophy which holds law as being intrinsic also.

This has happened--and still happens--in the real world application of law to specific disputes. During the Salem witch trials it was not uncommon to have testimony reach the court alleging that someone had committed a spiritual attack against a person. The accusers claim was taken as so-called "spectral evidence" that this attack had actually occurred. Per USLegal.com:

#+begin_quote
Spectral evidence refers to a witness testimony that the accused person's spirit or spectral shape appeared to [the] witness in a dream at the time the accused person's physical body was at another location. It was accepted in the courts during the Salem Witch Trials. The evidence was accepted on the basis that the devil and his minions were powerful enough to send their spirits, or specters, to pure, religious people in order to lead them astray.

In spectral evidence, the admission of victims' conjectures is governed only by the limits of their fears and imaginations, whether or not objectively proven facts are forthcoming to justify them.[fn:34]
#+end_quote

This legal principle comes directly from the supernaturalistic metaphysics of the Puritans:

#+begin_quote
The Puritans believed that physical realities had spiritual causes. For example, if the crop failed, the Devil may have played a role---and Satan could not take the form of an unwilling person. So if anyone claimed to have seen a ghost or spirit in the form of the accused, that person must be a witch. With this worldview, it was not a stretch for Puritans to believe in spectral evidence, which was the primary evidence used as proof of guilt.[fn:35]
#+end_quote

With a false philosophy as the grounding, even the most sound legal theory cannot properly map onto reality. After all, one can imagine that even if the Puritans accepted wholeheartedly the non-aggression principle, they could simply hold that these spectral attacks initiate conflict and are thus illicit. Perhaps the Marxian completely agrees with any argument one might come forth that the only proper legal principle is non-aggression, but claim that this applies only to the bourgeoisie with their bourgeois logic---if we were so-conditioned to accept proletarian logic, we would understand that individual property rights are illusory and that the proper meaning of liberty involves total obedience to the collective.

** Rand's Politics
*** Value vs Force
Now, before elaborating on why Objectivism properly understood yields anarcho-capitalism, it is worth going over the case Rand gives for her--decidedly not anarchistic--politics. Before I can give a proper case for politics as Rand sees it, I must establish a more fundamental ethical principle, which I agree with Rand on: namely that the initiation of force is a moral evil.[fn:36]

The justification of this principle on Objectivist grounds is that the mind cannot work under compulsion---in order to make a man act against his judgement you must nullify his judgement. This is what is meant by the use of force. There would be no reason to force a man to do what he was already planning to do---insofar as you are actually forcing him, you must be making him act /against/ his own rational judgement, i.e. you are making him act as his own destroyer. What this means is that force and value are entirely opposed to each other---you can have either one or the other.

This is a perspective unique to Objectivism within the history of philosophy---the two main opposing schools, intrinsicism and subjectivism, both reject it in their own way.

The intrinsic school holds that values have nothing to do with a man's perception, his evaluation, or the context of his life. On this view "value" is an intrinsic attribute of something, knowledge of which is derived through mystic means. Therefore, they say, values can be forced upon a man against his own judgement and "for his own good"---because value has nothing to do with his judgement, even forcing him to act against his judgement can be a value to him. You can achieve the good for someone else at the point of a gun.

The subjectivists take the other side of the mind-body false-dichotomy but arrive at the same conclusion. On subjectivism, something is a value if one merely claims it to be, as "value" is a mere arbitrary name that tells us nothing about the world, only giving insight into a so-called relation of ideas. Because there are no objective values on this viewpoint, a value can be whatever a man claims it to be. If a man feels that he is right in robbing or beating his fellow men, then he is---if he feels that something is good, then it is. Given subjective feelings are the standard, one could not possibly hope to convince others of a moral view through rational argumentation---thus the only remaining option is to force others to obey your arbitrary whims.

The error of both schools is found in their attempted separation of values from the mind---that values are whatever is in accord with gods plan, irrespective of judgement; or that values are based on arbitrary whim completely divorced from the faculty that judges. Neither school recognises that a value is a value /as evaluated by a thinking mind through the application of a rational standard/. Values cannot exist without a mind there to do the evaluating, namely, a man's /own/ mind. Just as others cannot digest food for you, so too can they not think or evaluate for you.

The brute exists as a parasite. He does not produce values himself, rather his survival depends on the values produced by those whom he predates upon. They undercut themselves in this activity---they are attacking and destroying the very root of their own sustenance. They rely on the universe to make A non-A, to yield an effect without the cause, to conform to their wishes.

*** The Moral Society
Now that it has been established that force and value are incompatible, we can move into the territory of the Randian politics proper. So, the case is something like the following: if man is to live he requires a code of values to guide his actions---living in a society is such a value to man if it is the right /kind/ of society.[fn:37] Politics is the branch of philosophy that seeks to define the principles that must undergird a society if it is to be a value to man---that is, the principles of a moral society.

First it must be noted that the individual is the unit of reality and the standard of value. That is, society is a derivative concept that has no existence unto itself---a group is a group /of individuals/, rather than the other way around. This means that any politics that proceeds in its analysis by concerning itself with "the good of the many" or any other such similar notion must be completely discarded on its face.

The most basic principle in politics is inalienable, individual rights. Our preceding analysis makes clear why it is that rights must be individual: the individual is the basic political unit and so the theory of rights must be a theory of /individual/ rights if it is to be considered rational. The rights must be inalienable because the alternative is not a right, but a permission---if my rights are subject to the arbitrary decrees of some king, or duke, or other such figure, then I must receive /permission/ from him to engage in some activity. This is the key insight here: a right can only mean a principle that defends the individual from others---this is accordingly a theory of /negative/, not /positive/ rights.

A so-called positive right would be something like my having a right to healthcare. Such a theory of rights is faced with an immediate contradiction: if I have a right to receive the services of doctors no matter what they want to do, then those doctors must no longer have the right to live their own life. Force must be used against the doctors to make them comply, but as explained above this means nullifying the doctors' basic means of survival: their minds. That is, if I demand this treatment and should get it, then they no longer have the right to live; if I demand it and should not get it, then I no longer have the right to their labour---the two are mutually-exclusive.

Accordingly, Rand defined a right as "a moral principle defining and sanctioning a man's freedom of action in a social context."[fn:38] A right is a /moral/ principle because it stands as the precondition for a society to be a value to man; it defines and sanctions mans "freedom of action" because it is and must be negative; it does so in a social context because there is no society to protect man from without said context.

** Open vs Closed
Now that I have elucidated the Objectivist politics--at least briefly--I must turn to my dispute with it, which impinges upon a great schism within the Objectivism movement: namely, the debate over whether Objectivism is an open or closed system. If Objectivism is a closed system, that is, if it is just whatever beliefs in philosophy that Ayn Rand held, then it can never develop or shift from the moment of her death. In this case, the preceding analysis of Rand's politics /is/ the Objectivist politics. If, on the other hand, Objectivism is an open system, then "Ayn Rand said so" cannot stand as an argument for the preceding analysis being the /Objectivist/ politics.

Let me first state that I am not going to give the standard case for Objectivism being an open system as forwarded by Stephen Hicks. I think that Craig Biddle gave an unanswerable objection to Hicks' presentation of open Objectivism in their debate. Namely: Hicks has it that Objectivism means true philosophy---this is a frozen abstraction and must therefore be entirely disallowed within our conceptual framework. Objectivism is not a science, it is a particular philosophical theory.

I do want to be clear here because this debate often gets fairly heated; I hold no animosity or contempt to anybody in the Atlas Society or anybody else who is in the David Kelley school of open Objectivism.[fn:39] I think that they are doing fantastic work to promote Objectivism and they form a great resistance to some of the more Rand-worshipper elements of the movement.[fn:40] I also am not adopting any sort of a smear against the closed Objectivists in claiming they are closed minded as is allegedly done sometimes[fn:41]---closed Objectivism in the context of this video should be taken /only/ to mean that theory that Objectivism means whatever beliefs in philosophy Ayn Rand held. I hold to a different sort of open Objectivism than that of Kelley or Hicks. Namely: I don't hold that Objectivism means true philosophy, /or/ that it means whatever beliefs in philosophy are held by Ayn Rand---in my view, Objectivism is the philosophy of the primacy of existence.

The primacy of existence is basically the view that existence is the most fundamental fact. That /first/ one must have it that existence exists, /then/ one can recognise that they are conscious of it. To explain this view, it is worth contrasting it with the opposing view---the primacy of consciousness. One form of this is found in Descartes' /cogito ergo sum/---I think, /therefore/ I am. The starting point for Descartes is an "I think," not an "it is." Another form of it is found in the religious viewpoint that reality requires a cause, and that this cause must be the consciousness they call God. This is also the primacy of consciousness---supernatural thoughts are held as the fundamental which comes before reality.

If you are interested in why the primacy of existence is true, I refer you to this wiki article[fn:42] I wrote on the subject. Regardless, to justify the claim that Objectivism means the philosophy of the primacy of consciousness, let me consult the standard Objectivist account of definition; namely, that a definition is a statement that identifies the nature of a concept's units:
#+begin_quote
A proper definition is made of two parts, each of which follows from the nature of concept-formation. When we form a concept, we isolate its units by grasping a distinguishing characteristic. In the definition, this becomes what the medieval Aristotelians called the differentia. Further, we can differentiate only on the basis of a wider characteristic, the [conceptual common-denominator], which is shared both by the concretes we are isolating and by the concretes from which we are isolating them. In the definition, this gives rise to the genus.

A definition in terms of genus and differentia is like a logical X ray of a concept. It condenses into a brief, retainable statement the essence of the concept-forming process: it tells us what distinguishes the units and from what they are being distinguished, i.e., within what wider group the distinction is being made. To give the standard example: if we conceptualize man by differentiating men from dogs, cats, and horses, then “animal” would be the genus—“rational,” the differentia.[fn:43]
#+end_quote

So, for my definition, that Objectivism is the philosophy of the primacy of existence, the /genus/--the common denominator[fn:44]--is philosophy. Objectivism is a philosophy, like everything else which is a philosophy. What makes Objectivism different to all other philosophies--the /differentia/--is that Objectivism explicitly identifies and applies the primacy of existence to every philosophical issue.

Let me explicate this with respect to a few areas. In metaphysics, the most fundamental branch of philosophy, we have it that according to Rand's legal and intellectual heir, Leonard Peikoff, "[...] the essence of metaphysics [...] is the step-by-step development of the corollaries of the existence axiom."[fn:45] So the /essence/ of the /Objectivist/ approach to metaphysics according to its de-facto living leader is the development of the fact that existence exists and that it is not subject to change by thought.

The basic approach underlying this carries on up to the epistemology---the philosophy of knowledge. What it means to be /objective/ in epistemology, according to standard Objectivism, is to appeal to reality. It is the recognition of reality. This is so because existence has primacy over consciousness. Every single doctrine found within the Objectivist epistemology is based on the premise that reality exists independently of you, and that the role of your consciousness is merely to discover facts about it, or--if you choose to--obscure those facts.

I could go on, but I think you get the point---the /essence/ of Objectivism is this consistent application of the primacy of existence to every philosophical issue. This is a uniquely Objectivist viewpoint, and is in fact what Objectivists mean when they tell you to be objective[fn:46]--the very namesake of the philosophy--namely: that objectivity means adherence to the primacy of existence. Even Aristotle was not fully consistent in this approach. He failed to explicitly identify and apply the primacy of existence---the most fundamental thing in his metaphysics is not that existence exists, but rather that the Prime Mover thinks about his own thoughts.

I have thus satisfied both requirements of a definition on Objectivist grounds---I have a genus (philosophy) and differentia (the explicit application of the primacy of existence). And I do not fall into the same frozen abstraction objection brought forth by Biddle, because I am not /defining/ Objectivism as "true philosophy." To be sure, Objectivism is true philosophy /on/ my definition, but not /by/ definition as it is with more primitive forms of open Objectivism---rather, Objectivism is true philosophy /because the primacy of existence is true/. So if somehow I were to be convinced that the correct approach in, say, aesthetics is to appeal to Platonic forms or something, I would consider that Platonic aesthetics to be part of true philosophy, but not part of Objectivism. The Platonic method would here be supposedly yielding truth, but it would not be adhering to the unique Objectivist innovation which is to explicitly apply the primacy of existence to /every/ philosophical issue.

It is also not at all idiosyncratic of me to separate the philosophy from the philosopher who originated it. The arch-closed-Objectivist, Leonard Peikoff, does this very thing with respect to Aristotle. Peikoff tells us in his history of philosophy that Aristotle the man had both Platonist and Aristotelian elements in him.[fn:47] This simply could not be the case if Aristotelian meant whatever beliefs in philosophy Aristotle held, much like the closed Objectivists want to have for Rand. Indeed, Peikoff is entirely correct to conceptually separate the /essential/ approach that Aristotle performed[fn:48] from whatever remote deviations he may have had. As far as the history of philosophy is concerned, any such deviation is simply irrelevant, and will quickly be ironed over by more consistent students of the philosopher who did the deviation. What matters in the definition of philosophies is an identification of their essence---and that essence has nothing to do, conceptually speaking, with the person who discovered or invented the philosophy.

Indeed, Rand herself rejected the term "Randism" as a description of her philosophy, correcting Mike Wallace that she calls it Objectivism "meaning a philosophy based on objective reality."[fn:49]

So, then, is it possible to make such simple statements of other philosophies like my one for Objectivism? Perhaps, or perhaps not. I will leave it to the adherents of Kant, or Descartes, or Saint Augustine to distil such beliefs into an easily recognisable essence. I will say on this front that most philosophies except for Objectivism form an ecclectic hodge-podge of random positions hastily strung together, and that to whatever extent this is the case one requires more clarifications and asterisks to be stuck onto an otherwise neat statement of that philosophy. When it comes to some of the more ecclectic philosophies, it becomes possible to identify it only by gesturing at the philosopher who thought it made sense. But, insofar as a given philosophy is integrated in its claims and basic approach, one can identify it as easily as I identify Objectivism: the philosophy of the primacy of existence.

Of course, I would be remiss if I did not present some of the arguments provided by the closed Objectivists on why they think it is closed. Onkar Ghate has it that this is the normal way of thinking of theories elsewhere:
#+begin_quote
So there's Darwin's theories in evolutionary biology, and they're Darwin's theories, and they end when he stops writing and dies. Then those are his theories in biology. Or Einstein's theories in physics. They're closed, again, when he dies or stops writing. And that was the perspective that ARI adopted and its a perspective I certainly agree with. But if you ask: is philosophy open or closed? I think it's a different answer. Philosophy is open. So Objectivism and [...] truths in philosophy are not synonyms.[fn:50]
#+end_quote

He goes on to further address the "Objectivism is truths in philosophy" type of open Objectivism, which I agree with him on. What I disagree with him on, is his attempted analogising of Rand to Darwin and Einstein. Notice that he said "Darwin's theories in biology" and "Einstein's theories in physics" rather than "evolution" or "general relativity." Because the theories of evolution and general relativity are decidedly /not/ closed upon the deaths of their originators. We know /for sure/ that further discoveries need to be made in the theory of general relativity, because it cannot account for quantum gravity or dark matter. It is also possible to make further discoveries under the broad umbrella of the theory of evolution, but I know far less about biology so I cannot say exactly what that would consist of. Indeed, nobody is debating over whether "Ayn Rand's theories in philosophy" is open or closed---clearly, whatever beliefs Ayn Rand holds on philosophy is a closed set the instant she dies. But the word "Objectivism"--much like the words "evolution" and "general relativity"--does not refer to whatever beliefs she happens to hold. It refers to the essential theory that she was forwarding.

The theories of evolution and general relativity are not terms analogous to "philosophy"--the proper analogy there would be "biology" and "physics"--evolution and general relativity, on the other hand, are specific theories in their respective fields, like how Objectivism is a specific theory about philosophy.

I will cap off this section with Rand's nascent words on the topic---which to be clear were written before this particular debate occurred:
#+begin_quote
This is to say that I approve of the publication of /The Objectivist Forum/, that it promises to be a very interesting magazine, and that I recommend it to your attention. It is not, however, the official voice of Objectivism and it is not my representative or spokesman.

As its name indicates, this magazine is a /forum/ for students of Objectivism to discuss their ideas, each speaking only for himself.

[...]

If you wonder why I am so particular about protecting the integrity of the term "Objectivism," my reason is that "Objectivism" is the name I have given to /my/ philosophy --- therefore, anyone using that name for some philosophical hodgepodge of his own, without my knowledge or consent, is guilty of the fraudulent presumption of trying to put thoughts into /my/ brain (or of trying to pass his thinking off as mine --- an attempt which fails, for obvious reasons). I chose the name "Objectivism" at a time when my philosophy was beginning to be known and some people were starting to call themselves "Randists." I am much too conceited to allow such a use of my name.

[...]

What is the proper policy on this issue? If you agree with some tenets of Objectivism, but disagree with others, do not call yourself an Objectivist; give proper authorship credit for the parts you agree with --- and then indulge in any flights of fancy you wish, on your own.[fn:51]
#+end_quote

This quoted text was specifically selected by Onkar Ghate, before anybody tries accusing me of omitting important information. Regardless, I do agree with the closed Objectivists that this is evidence that Rand would have been a closed Objectivist if she were alive for the debates. But, that Ayn Rand would take that position does not imply that it is the correct position. "Ayn Rand said so" isn't an argument. At least the open Objectivism that I present is not a philosophical hodgepodge---it is the properly integrated form of the theory. And I am making no attempts to represent any discoveries I have made as being discoveries made by Ayn Rand, she deserves no credit for the numerous innovations in legal theory I have made. This is precisely because /Objectivism does not mean whatever beliefs in philosophy Ayn Rand held/. /Because/ I hold that Objectivism is a broader abstraction, I am perfectly free to hold both that there are correct Objectivist stances that Ayn Rand did not hold /whilst/ not pinning these positions onto Ayn Rand.

I give proper credit for the discovery of the correct legal theory /on Objectivist terms/ to Murray Rothbard, and then to myself and other contributors for completing it. /This does not require that Objectivism means whatever beliefs in philosophy Ayn Rand held/.

** Law vs Politics
So then, why is it that I think the anarcho-capitalist legal theory as formulated by myself is the proper implication of prior Objectivist philosophy? The reason is that I think Ayn Rand and her legion followers were all answering the wrong question when it came time to formulate the politics. Namely: I think politics is not a valid field of philosophy---law is.

Peikoff states the question that politics is trying to answer as: "what is right or wrong in terms of what the government does, what society does,"[fn:52] or that:
#+begin_quote
Politics, like ethics, is a normative branch of philosophy. Politics defines the principles of a proper social system, including the proper functions of government.[fn:53]
#+end_quote

This is, once again, the fallacy of the frozen abstraction. Allow me to highlight this with respect to another example from Rand:

#+begin_quote
Objectivists will often hear a question such as: "What will be done about the poor or the handicapped in a free society?" [...] Observe that he does not ask: "Should anything be done?" but: "What will be done?"---as if the collectivist premise had been tacitly accepted and all that remains is a discussion of the means to implement it.[fn:54]
#+end_quote

In the case of politics, the Randians have grafted the premise that there should be a government onto the very problem-statement. This poisons every piece of analysis they provide from this point on. Their formulation doesn't even consider the question "should there be a government?" it asks "how should the government be run?"

This snuck premise is a collectivist deviation. "Society" or "the government" cannot do right or wrong---those are collective terms. Rand and all of her followers on this front reify "society" as something that can be good or bad, proper or improper. But society is not an entity, it cannot act. We might as well make a new branch of philosophy called murderology, which asks the question: "how should men act, including what are the proper methods of murder? Murder is a value to men only if it is the right kind of murder, after all!" This is a gross deviation not only from the proper Objectivist line, but from philosophy itself. None of the other branches are defined in such a crude fashion.

Metaphysics isn't "what is there, and also what is the world stuff?," epistemology isn't "how do I know and also why are the senses invalid?," and ethics isn't "what should I do about it, and what are therefore my duties?" So then why on Earth should one accept such sloppy grafting on of a specific theory in Politics--that there should be a government--to the broader abstraction of politics itself? Say, I think theres a term for doing that. The fallacy of making cold abstractions? Something like that.

Just as it is collectivist to speculate on what "society" should do for the poor, it is collectivist to speculate on what "society" should do for those whose rights are being violated. The proper response, in both cases, is: "if you want to do something about it, then do it---I am not my brothers keepers!"

** Proof of The NAP on Objectivist Grounds
*** The Correct Question: Law
The Objectivists do present various arguments against anarchism, but before I address those I will give you my case for what should go in place of the Randian politics.

We have seen that the error made by Rand and others on this front was in answering the wrong question, so what is the right question? What is the problem that men face that requires an answer from philosophy? The problem is that we live in a world of scarce means, and as such men can come into conflict with each other---so how should you deal with conflicts? This is the question that law poses.

A conflict in this context does not mean a mere disagreement, or argument, or dispute; a conflict means mutually-exclusive actions. So, perhaps Robinson Crusoe is on a desert island and comes across a stick in nature. He takes this stick and wishes to use it for spearfishing. As he is on his way to the ocean, another man, Friday, sees this same stick and decides to use it to stoke his fire. The two men cannot both perform these actions at the same time--they are mutually exclusive--such that if Friday went ahead with his course of action, there would be a conflict and one man would have to be deprived of the attainment of his end.

Notice that nowhere in the formulation of this problem have any additional unchecked premises been introduced. It is true that means are scarce and therefore conflicts are possible. And it is true that this is a problem that ethics can answer---namely, it answers it on the individual level. Should you initiate conflicts, or not?

There are three basic answers to this question:
1. the law of the jungle---initiate conflicts at your whim;
2. mixed law---sometimes initiate conflicts, and;
3. the non-aggression principle---don't initiate conflicts.

*** The Law of the Jungle
First let's consider the law of the jungle---what would a universal acceptance of conflict-engendering norms look like? If Crusoe were to take a stick from nature and try to use it for spearfishing, he would not be able to complain under this system if Friday came along and took that stick from him, because Crusoe could not claim the stick as his /property/, the property right would rather travel from person to person always being attached to the item itself. In other words, on such a view there would be no distinction whatsoever between /ownership/ and /possession/. We would have--in the words of Stephan Kinsella[fn:55]--a "mere possessor" ethic.

The issue with this view is that ownership--which we can define as the /right/ to possess a given scarce good--is necessarily distinct from possession. If there is some dispute between $A$ and $B$ over who should be the one to control a given property, then /both/ $A$ and $B$ must pre-suppose this to be the case. $A$ is asserting that though $B$ might be able to actually obtain control, it would nevertheless be the case that $A$ /should/ be the one to control it, and similarly $B$ is asserting that though $A$ might be able to actually obtain control, it would nevertheless be the case that $\textit{\textbf{B}}$ should be the one to actually control it.

So this mere possessor ethic, which the law of the jungle asserts, would require a conflation of the concepts /ownership/ and /possession/, that is to say that the law of the jungle is the assertion that ownership rights are acquired by the mere act of taking a given good from someone else---if $A$ has a stick and $B$ takes that stick from him, then the jungle-jurist says that $C$ could come along and take the stick from $B$ and then become the owner, i.e. that whomever is in possession of the stick is in fact it's owner. But, how exactly is a person able to assert this jungle-law view in defense of their actions? We saw above that both $A$ and $B$ must pre-suppose the distinction between ownership and possession---they are saying that /they/ should control the item which implies that they have a /right/ to exclude other people from using it.[fn:56]

We have this real problem of conflicts that we are trying to resolve and the jungle law view is simply incommunicable by the fact that it is a contradiction to even assert---the instant a man tries to defend his conduct by asserting that conflicts should not be avoided and that rights are illusory he necessarily asserts that conflicts should be avoided (when initiated against him) and that rights are real (when the thief is facing a counter-attack).[fn:57] So this man would be left with only the option of sealing up his lips and making no defense, living as an animal-beast ruled by whatever whims he feels at the moment, with no concern for whether his conduct is rationally defensible.

So at best the jungle-law ethic reduces into whim-worship, but recall above that ethics itself rests upon earlier conclusions in metaphysics and epistemology, so upon what metaphysical and/or epistemic premises does such an ethic rest? Fundamentally, we have the question of "how should we be dealing with conflicts, what is criminal?" and the jungle-jurist asserts: "who gives a damn? Might makes right; live by your arbitrary whims." What this means, if taken as a serious ethical proposal, is that whims are a genuine source of knowledge, i.e. this is not only a whim-ethic, but a whim-epistemology---it all boils down to "I think this is true because I feel like it is;" "I should take this spear because I feel like I should."

But of course, epistemology does not stand on it's own, it is not primary in philosophy; rather a given epistemology rests on prior metaphysical premises. So on what metaphysical premises does this whim-epistemology rest? What is really being said here is that if you simply /think/ something to be the case hard enough then it /is/ the case; that your whims, your thoughts, your consciousness is the basis of reality. That existence conforms to your consciousness, rather than the other way around. This is the fallacy of the primacy of consciousness. This view of the law of the jungle or any other whim-based theory does and must rely on the premise that consciousness--mere thoughts--have metaphysical primacy over existence.

*** Mixed Law
**** Reduction to the Primacy of Consciousness
Next, let's consider the "mixed law" system(s); i.e. that conflicts should be avoided under certain circumstances, but not always. First any mixed-law system that can be reduced to "we must aggress in these arbitrary situations" is refuted by the above reasoning against the law of the jungle.

Allow me to now quickly introduce a number of different proposals for a mixed-law system such that I may draw your attention to a common principle among them all:
1. consequentialism---he whose victory would yield the best outcome is he who should win the conflict at hand;[fn:58]
2. racism---he who is fighting for the interests of the preferred race is he who should win the conflict at hand;
3. Marxism---he who is fighting for the interests of the proletariat is he who should win the conflict at hand;
4. primitivism---he who is fighting for apocalypse[fn:59] is he who should win the conflict at hand;
5. monarchism---he who is deemed to be the proper victor by the monarch is he who should win the conflict at hand;
6. democratism---he who is deemed to be the proper victor by majority opinion is he who should win the conflict at hand;
7. Rawlsianism---he who is deemed to be the proper victor by a party situated behind a veil of ignorance is he who should win the conflict at hand,[fn:60] and;
8. imperialism---he who is deemed to be an ally by the military leadership of the preferred country is he who should win the conflict at hand.

You will notice that on their face these ideologies fall under two categories: (1) the class-based, i.e. "he who is part of the preferred class is he who should win the conflict at hand,"[fn:61] and (2) the whim-based, i.e. "he who is deemed to be the proper victor by X is he who should win the conflict at hand." It should be clear why the latter would fall under the same reasoning as used against the law of the jungle; thus I shall focus my efforts on those class-based mixed-law systems.

Any form of class-based law is an ethic in the form: one rule for class $A$ and another for class non-$A$. But by what possible means could one derive that one ethic applies to $A$ and another /incompatible/[fn:62] ethic applies to non-$A$? Surely such an ethic could not be derived from the nature of man as such, because if it were then we would have a universal principle, not one that applies only to a particular subset of humanity. Therefore, such an ethic must be arbitrarily particularised---we have an arbitrary distinction which forms a class of humans and a class of sub-humans, we do not here have a rational ethic for /man/. This particularisation then falls back into the primacy of consciousness and therefore fails.

**** The ARgument from Argument
On top of this, there exists a built-in self-destruct for any mixed law ethic, in the form of Hans-Hermann Hoppe's argument from argument.[fn:63]

The basic idea behind this attack is found in noticing that there exists an inescapable inconsistency when it comes to arguing in favour of aggression, borne from the fact that argumentation is and must be a conflict-free interaction. When people have some dispute and they choose to argue about it, they are doing the exact opposite of fighting over the dispute. That is, if Crusoe and Friday have a disagreement over how to use a spear, then each party sitting down and giving arguments as to why their use should go forth is quite distinct to each party launching missiles and trying to stab the other to death in order that their use may go forth unimpeded.

That is, simply by arguing about property rights, you must pre-suppose libertarian non-aggression in your act of peacefully attempting to resolve the disagreement. For our above dispute between Crusoe and Friday, if Friday is trying to convince Crusoe that the proper use of the spear is to violate Crusoe's bodily autonomy, then he finds himself in a practical contradiction,[fn:64] namely he is respecting Crusoe's bodily autonomy and trying to achieve consent from Crusoe by his act of arguing, whilst he is explicitly rejecting that Crusoe's consent is required in the first place. To escape this contradiction, Friday has two options: first, he can stop arguing and go back to fighting over it, or second, he can drop his claim that Crusoe's bodily autonomy should be violated. In this second case the mixed law or jungle ethic has trivially dropped out of rational consideration, and in the first case we have it that Friday has turned himself into an animal-beast governed only by whim---which makes his ethic irrational still.

What this argument does is highlight an implicit notion we have that such jungle ethics are irrational and brutish; namely that it is simply inconsistent and hypocritical for a person to even try to assert them in an argument---that if they truly believe in their murderous creeds then why the hell aren't they living by them?

** The Objectivist Arguments Against Anarchism
So, we have it that there are three possible solutions to the correct problem-statement of law, two of them are false, leaving us only with the non-aggression principle as the correct answer. Refer to my course on how the rest of the legal theory is derived from the NAP,[fn:65] and any Randroids in the audience who find themselves screaming about rationalism because I used deductive reasoning can feel free to sob away all they want---but if I can pierce the veil of tears for a moment, I would ask them to articulate exactly what about my preceding reasoning is incorrect, rather than just screaming about how Peikoff one time said something that sort of sounds like what they want to say.

Regardless, I can now move onto some of the objections that the Randians have raised against anarchism. Do note that this is one area where the writing is laughably sparse, and for good reason---namely, they lack any solid theoretical objections so prefer to give a very light treatment to the topic and never with an anarcho-Objectivist there to provide counter-arguments.

Rand defines government as "an institution that holds the exclusive power to enforce certain rules of social conduct in a given geographical area,"[fn:66] and on this definition, anarchism is supposed to represent a floating abstraction---i.e. an abstraction with no concrete referent:

#+begin_quote
Anarchy, as a political concept, is a naive floating abstraction: for all the reasons discussed above, a society without an organized government would be at the mercy of the first criminal who came along and who would precipitate it into the chaos of gang warfare. But the possibility of human immorality is not the only objection to anarchy: even a society whose every member were fully rational and faultlessly moral, could not function in a state of anarchy; it is the need of objective laws and of an arbiter for honest disagreements among men that necessitates the establishment of a government.[fn:67]
#+end_quote

First, there is the false premise that without a monopoly on rights enforcement all that is left is brute violence and gang warfare. As I have explained earlier, competing insurance firms tend to do a far better job at enforcing rights than any monopolist could hope to. Second, there is the false premise that anarchy means no objective laws or arbitration. This is a point that is frequently repeated by the Randians, and never substantiated. It is the premise that you need some monopolist to "make the law objective"---but law is /discovered/ not /produced/. Competing arbitration firms can all appeal to reality to discover what the objective legal principles are which they can then apply to some specific case. Honest disagreements can be resolved without having a monopoly on dispute resolution.

#+begin_quote
A recent variant of anarchistic theory, which is befuddling some of the younger advocates of freedom, is a weird absurdity called "competing governments." Accepting the basic premise of the modern statists -- who see no difference between the functions of government and the functions of industry, between force and production, and who advocate government ownership of business -- the proponents of "competing governments" take the other side of the same coin and declare that since competition is so beneficial to business, it should also be applied to government. Instead of a single, monopolistic government, they declare, there should be a number of different governments in the same geographical area, competing for the allegiance of individual citizens, with every citizen free to "shop" and to patronize whatever government he chooses.

Remember that forcible restraint of men is the only service a government has to offer. Ask yourself what a competition in forcible restraint would have to mean.[fn:68]
#+end_quote

Indeed, if government means "an institution that holds the exclusive power to enforce certain rules of social conduct in a given geographical area," then we have successfully defined away any "competing governments" anarchism. But this does not begin to address the anarcho-capitalist case. If government must mean a monopolist, then competition in rights enforcement does not entail competing governments. Competition in this arena means that you can pay whomever you like to enforce your rights---nothing else. Rand continues with a hypothetical scenario that is supposed to demonstrate the absurdity of competition in rights enforcement:

#+begin_quote
[...] suppose Mr. Smith, a  customer of Government A, suspects that his next-door neighbor, Mr. Jones, a customer of Government B, has robbed him; a squad of Police A proceeds to Mr. Jones' house and is met at the door by a squad of Police B, who declare that they do not accept the validity of Mr. Smith's complaint and do not recognize the authority of Government A. What happens then? You take it from there.[fn:69]
#+end_quote

How utterly absurd! I might as well dream up my own fantasy to dispute this theory: what if instead of Government A and B, we had just the one government; Mr. Smith and Mr. Jones each have their own friends in the government. Then Smith tells his government friends that Jones stole his wallet, and of course this must obviously lead to the great war of the wallets! Millions die in the great and bloody war for power until one side prevails and genocides those who assert the incorrect view on whether the wallet was stolen or not.

What Rand forgets in her random hypothesizing, is that hypothetical scenarios are not tools to discover philosophy. They have many brilliant uses in checking that one is consistent or in trying to apply philosophical principles to cleanly defined scenarios---but they cannot do anything beyond this. What would /actually/ happen in such a scenario, is that neither /firm/ wants to go to random war, so they would investigate who the aggressor is and seek damages from him. It is the state which is capable of externalising any costs of great wars onto vast arrays of victims---not private firms.

Peikoff has his own retorts to anarchism, which stand as being just as absurd as Rand's:
#+begin_quote
Anarchism is the idea that there should be no government. In Objectivist terms, this amounts to the view that every man should defend himself by using physical force against others whenever he feels like it, with no objective standards of justice, crime, or proof.[fn:70]
#+end_quote

This is a near-explicit straw man attack on anarchism. Anarchism is the view that there should be no government--if government means a monopoly force-user--but that does not even come close to implying "that every man should defend himself by using physical force against others whenever he feels like it, with no objective standards of justice, crime, or proof." What an absolutely absurd claim that is on its face. I would be somewhat willing to excuse utter nonsense like this if it were written in a time prior to Murray Rothbard, but it wasn't---Peikoff is just openly endorsing the false alternative that either there should be a monopoly on force, or everyone should just use whatever force they want at their whim. I'm frankly shocked that he never once considered whether individual men could discover and apply philosophy on their own when it comes to the question of when the use of force is licit. Peikoff continues:

#+begin_quote
"What if an individual does not want to delegate his right of self-defense?" the anarchist frequently asks. "Isn't that a legitimate aspect of 'freedom'?" The question implies that a "free man" is one with the right to enact his desire, any desire, simply because it is his desire, including the desire to use force. This means the equation of "freedom" with whim-worship. Philosophically, the underlying premise is subjectivism (of the personal variety).[fn:71]
#+end_quote

Again, the underlying premise is decidedly /not/ that a man may do /anything/ he wants simply because he wants it---the underlying premise is that a man may defend himself if he wishes or delegate this defense to anybody he sees fit. Nowhere in this claim is there any implication that people may engage in random acts of violence or use arbitrary means to defend their property. That is a patent absurdity and false alternative presented to us by the people who are supposed to have as their banner that they check premises and never accept false alternatives.

The collectivist poison that Rand grafted onto her politics has yielded legion derivative errors, not least of which is her support of intellectual "property." If you want to know why that is wrong, you have to watch this video[fn:72] where I explain that every form of IP is an anathema to the objective principles of law.

* Footnotes

[fn:1]Fiala, Andrew, "Anarchism", /The Stanford Encyclopedia of Philosophy/ (Winter 2021 Edition), Edward N. Zalta (ed.), https://plato.stanford.edu/archives/win2021/entries/anarchism/; "Anarchism is a political theory that is skeptical of the justification of authority and power."

[fn:2]TIKhistory, /Am I an Ancap? And what is Anarcho-Capitalism?/, t. 8:08

[fn:3]TIKhistory, /Turns out, Anarcho-Capitalism ISN'T "Anarchy" (RE: LiquidZulu)/, t. 10:53

[fn:4]TIKhistory, /Public vs Private | The Historic Definitions of Socialism & Capitalism/, t. 05:24

[fn:5]Ayn Rand, "The Metaphysical Versus the Man-Made," in ead., /Philosophy: Who Needs It/, p. 24

[fn:6]TIKhistory, /Public vs Private | The Historic Definitions of Socialism & Capitalism/, t. 33:00

[fn:7]TIKhistory, /Turns out, Anarcho-Capitalism ISN'T "Anarchy" (RE: LiquidZulu)/, https://youtu.be/ZCqcttEiyIY?t=1139, t. 18:59

[fn:8]LiquidZulu, /Why Socialism is Literally Impossible/, https://www.youtube.com/watch?v=KzHA3KLL7Ho

[fn:9]See: LiquidZulu, "On the Impossibility of Group Ownership," in id., /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/homesteading-and-property-rights/#on-the-impossibility-of-group-ownership

[fn:10]See: /The Role of Language for a Conceptual Being/ (Brain), https://liquidzulu.github.io/brain/note/the-role-of-language-for-a-conceptual-being/

[fn:11]Leonard Peikoff, /Founders of Western Philosophy: Thales to Hume/, lecture 9, t. 57:14

[fn:12]TIKhistory, /Turns out, Anarcho-Capitalism ISN'T "Anarchy" (RE: LiquidZulu)/, t. 17:39

[fn:13]TIKhistory, /Turns out, Anarcho-Capitalism ISN'T "Anarchy" (RE: LiquidZulu)/, t. 10:00

[fn:14]TIKhistory, /Turns out, Anarcho-Capitalism ISN'T "Anarchy" (RE: LiquidZulu)/, t. 16:24

[fn:15]TIKhistory, /Where do our modern ideologies come from? (Timeline Map)/, t. 28:02

[fn:16]The greek for choice is reportedly epilogí̱

[fn:17]LiquidZulu, Brain, /The Validation of Free Will/, https://liquidzulu.github.io/brain/note/the-validation-of-free-will/

[fn:18]Leonard Peikoff, /Objectivism: The Philosophy of Ayn Rand/, pp. 70-71

[fn:19]Edward W. Younkins, /Murray Rothbard's Randian Austrianism/, http://rebirthofreason.com/Articles/Younkins/Murray_Rothbards_Randian_Austrianism.shtml#:~:text=his%20metanormative%20ethical%20theory; see also: id., /Ayn Rand and the Austrian Economists/, https://www.youtube.com/watch?v=w4xR-RuO3C8, and Douglas B. Rasmussen, /Rothbard’s Account of the Action Axiom: A Neo-Aristotelian-Thomistic Defense/, https://www.youtube.com/watch?v=aC0PnYd6peM

[fn:20]Note: TIK has since explained that it was a mistake that severed this connection, and that he always intended to keep this link present.  https://twitter.com/TIKhistory/status/1843259322782101911

[fn:21]Murray Rothbard, letter to Ayn Rand, October 3, 1957; available at Journal of Libertarian Studies, Volume 21, no. 4 (Winter 2007): 11-16, /Mises and Rothbard Letters to Ayn Rand/, https://cdn.mises.org/21_4_3.pdf

[fn:22]Barbara Branden, /The Passion of Ayn Rand/, p. 413

[fn:23]Murray Rothbard, /In Defense of "Extreme Apriorism"/, https://mises.org/articles-interest/defense-extreme-apriorism

[fn:24]Ayn Rand, "Collectivized Ethics," in ead., /The Virtue of Selfishness/, p. 81

[fn:25]Green, Leslie and Thomas Adams, “Legal Positivism”, The Stanford Encyclopedia of Philosophy (Winter 2019 Edition), Edward N. Zalta (ed.), https://plato.stanford.edu/archives/win2019/entries/legal-positivism/ ([[https://archive.ph/fyQWR][archived]]).

[fn:26]Ayn Rand, /The Fountainhead/, p. 568

[fn:27]See, e.g.: Ludwig von Mises, /Economic Calculation in the Socialist Commonwealth/

[fn:28]Hans-Hermann Hoppe, /The Private Production of Defense/, pp. 7-8

[fn:29]/The Validation of Free Will/ (Brain), https://liquidzulu.github.io/brain/note/the-validation-of-free-will/

[fn:30]LiquidZulu, /Why Socialism is Literally Impossible/, https://www.youtube.com/watch?v=KzHA3KLL7Ho

[fn:31]/The Economic Calculation Problem/ (Brain), https://liquidzulu.github.io/brain/note/the-economic-calculation-problem/

[fn:32]Hans-Hermann Hoppe, "How to Think About the Statist Response," in id., /The Private Production of Defense/, p. 19

[fn:33]See Leonard Peikoff on the O'Reilly Factor, https://www.youtube.com/watch?v=JoAWCwm-UXw

[fn:34]USLegal definition of spectral evidence, citing State v. Dustin, 122 N.H. 544, 551 (N.H. 1982); https://definitions.uslegal.com/s/spectral-evidence/

[fn:35]New England Law, /A True Legal Horror Story: The Laws Leading to the Salem Witch Trials/, https://www.nesl.edu/blog/detail/a-true-legal-horror-story-the-laws-leading-to-the-salem-witch-trials

[fn:36]See: Ayn Rand, /The Virtue of Selfishness/, p. 28

[fn:37]See: Leonard Peikoff, /Objectivism: The Philosophy of Ayn Rand/, p. 350

[fn:38]Quoted from: Leonard Peikoff, /Objectivism: The Philosophy of Ayn Rand/, p. 351

[fn:39]David Kelley, /A Note to Our Members About Open Objectivism/

[fn:40]See, Craig Biddle, /“Ayn Rand Said” Is Not an Argument/, https://theobjectivestandard.com/2016/04/ayn-rand-said-is-not-an-argument/

[fn:41]See: "Onkar Ghate & Yaron Discuss Objectivism Closed/Open; Fact/Value; Moral Sanction | Yaron Interviews," https://youtu.be/qSCUlarRBNA

[fn:42]/The Primacy of Existence vs The Primacy of Consciousness/ (Brain), https://liquidzulu.github.io/brain/note/the-primacy-of-existence-vs-the-primacy-of-consciousness/

[fn:43]Leonard Peikoff, /Objectivism: The Philosophy of Ayn Rand/, p. 97

[fn:44]/Conceptual Common Denominator/ (Brain), https://liquidzulu.github.io/brain/note/conceptual-common-denominator/

[fn:45]Leonard Peikoff, /Objectivism: The Philosophy of Ayn Rand/, p. 16

[fn:46]/The Meaning of Objectivity/ (Brain), https://liquidzulu.github.io/brain/note/the-meaning-of-objectivity/

[fn:47]See: Ayn Rand Institute, /Aristotle: A Philosopher for Living on Earth by Leonard Peikoff, part 13 of 50/, https://www.youtube.com/watch?v=Qvl4f8l7Ctk, t. 37:18, "Aristotle is not a fully consistent representative of the primacy of existence. There is always a vestigial, contradictory Platonic element in him. But that is unimportant to him /qua/ Aristotelian, which is our primary concern."

[fn:48]See: Ayn Rand Institute, /Aristotle: A Philosopher for Living on Earth by Leonard Peikoff, part 13 of 50/, https://www.youtube.com/watch?v=Qvl4f8l7Ctk, tt. 2:12, 4:25, 5:16

[fn:49]See: Ayn Rand Institute, /The Mike Wallace Interview with Ayn Rand/, https://www.youtube.com/watch?v=lHl2PqwRcY0

[fn:50]Onkar Ghate, /An OAC Moment: Is Objectivism an Open or Closed System?/, https://youtu.be/0JBdBPQ4dLQ?t=200, t. 3:20

[fn:51]Ayn Rand, /To The Readers of the Objectivist Forum/, https://youtu.be/ybgCeJdd5es?t=1125

[fn:52]HEAVY DUTE COLLEGE, /LEONARD PEIKOFF: MY PHILOSOPHICAL JOURNEY/, https://youtu.be/jS7-63hSG98?t=49

[fn:53]Leonard Peikoff, "Government," in id., /Objectivism: The Philosophy of Ayn Rand/, p. 350

[fn:54]Ayn Rand, "Collectivized Ethics," in ead., /The Virtue of Selfishness/

[fn:55]Stephan Kinsella, /Thoughts on the Latecomer and Homesteading Ideas; or, why the very idea of "ownership" implies that only libertarian principles are justifiable/.

[fn:56]Recall the point about scarcity; if they have a right to control the item in question this control will necessarily exclude others from using it.

[fn:57]For more on this see: N. Stephan Kinsella, "Rights-Skepticism," in idem. /Dialogical Arguments for Libertarian Rights/; LiquidZulu, "The Contradiction of Rights-Scepticism," in idem., "2. The Non-Aggression Principle," in idem., /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/the-nap

[fn:58]Utilitarianism would be a sub-category, where "best outcome" means "the outcome of maximal utility." Utilitarianism specifically can be shown to be false on purely economic grounds in its use of a category error with the determination of the data type of "utility," see: Kenneth A. Zahringer (2011), "Cardinal Utility: It's Worse Than You Thought," /Mises Daily/, or on philosophical grounds as with any parasitic ethics, see: Leonard Peikoff's history of modern philosophy.

[fn:59]Apocalypse here is meant as a break-down in the capital structure, which is what primitivists such as Ted Kaczynski advocate for. For more on this see: LiquidZulu, /Primitivism is an Apocalyptic Ideology/.

[fn:60]For more on this in particular see: Hans-Hermann Hoppe, Introduction to Murray Rothbard, /The Ethics of Liberty/, second edition.

[fn:61]This would include 1-4; consequentialism has the class of detrimental individuals as against the class of beneficial individuals, primitivism has the class of producers as against the class of anti-producers, racism and marxism are obvious.

[fn:62]If the ethics were compatible this would then not be one rule for $A$ and another for non-$A$, it would rather be the same fundamental principle applying to both groups, and would therefore not be a class-based ethic.

[fn:63]On this, see: Hans-Hermann Hoppe, "The Ethical Justification of Capitalism and Why Socialism is Morally Indefensible," in idem., /A Theory of Socialism and Capitalism/; N. Stephan Kinsella, /Dialogical Arguments for Libertarian Rights/; and Frank van Dun, /Argumentation Ethics and the Philosophy of Freedom/.

[fn:64]The terms performative contradiction and dialectic contradiction are also often used here; though dialectic contradiction is really a subset of performative contradictions in general.

[fn:65]LiquidZulu, /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/libertarian-ethics

[fn:66]Ayn Rand, "The Nature of Government," in ead., /The Virtue of Selfishness/

[fn:67]Ayn Rand, "The Nature of Government," in ead., /The Virtue of Selfishness/

[fn:68]Ayn Rand, "The Nature of Government," in ead., /The Virtue of Selfishness/

[fn:69]Ayn Rand, "The Nature of Government," in ead., /The Virtue of Selfishness/

[fn:70]Leonard Peikoff, "Statism as the Politics of Unreason," in id., /Objectivism: The Philosophy of Ayn Rand/

[fn:71]Leonard Peikoff, "Statism as the Politics of Unreason," in id., /Objectivism: The Philosophy of Ayn Rand/

[fn:72]LiquidZulu, /Why Artists Shouldn't Own Their Art/, https://www.youtube.com/watch?v=4xKjHHzLUQQ
