#+title: Kameralized Paper - "A Critical Look at Austrian Rationalism"

* notes
** structure
+ start with a brief history of the Austrian school, its Aristotelian origins going onto the Kantian shift
+ where Kant fits into the history of philosophy more broadly as a response to David Hume and nominalism-sensualism
  + Kant does it with his copernican revolution, giving rise to synthetic a priori propositions. "Instead of assuming that our minds and our knowledge ought to conform to external objects, one should instead assume that external objects must conform to our minds."
  + Rand as an alternative answer.
** why austrians tend to be kantian
+ The Austrian school started out as Aristotelian, but a massive Kantian swing occurred with Mises and Hoppe; who both spent a great deal of time expounding upon their epistemic perspectives, whereas the Aristotelian Austrians generally did not.
  + "This is mainly because the Aristotelian camp among the major Austrians—for whatever reason—decided not to spend much time elaborating on their epistemological foundations.1 In contrast to this, Ludwig von Mises and Hans-Hermann Hoppe, the two major Austrians in the Kantian camp, devoted entire books solely to epistemological matters. The logical positivists gained intellectual prominence during Mises’ time, so he was the one who took it upon himself to decisively answer them from an Austrian perspective, which he of course did in an openly Kantian way. What is the essence of the Kantian answer to the Humean-positivist strain? It is in establishing the truth of what Kant called “synthetic a priori judgments”."
  + See David Gordon (1993): Menger and Bohm-Bawerk were Aristotelian.
  + Gordon (15): “the deductive method of Austrian economics stems from Aristotle. But an obvious objection comes to mind. When one turns to the third great figure of the Austrian School, Ludwig von Mises, Aristotle seems absent from the scene. Instead, Mises resorts to a distinctively neo-Kantian terminology: in particular, he regards the propositions of Austrian economics as synthetic a priori truths.”
    + "Interestingly, and contrary to Gordon’s assertion, Mises (1998, 38) holds that propositions which express a priori knowledge are analytic, not synthetic: “Aprioristic reasoning is purely conceptual and deductive. It cannot produce anything else but tautologies and analytic judgments. All its implications are logically derived from the premises and were already contained in them.”"
+ the Kantian vs Positivist false alternative
  + since Friedman (1953), economics has adopted a positivist methodology, rooted in methodological monism: the idea that the proper method of the social sciences is the same as the method of the natural sciences
    + the method consists of forming hypotheses based on observable facts and conducting controlled experiments to continually test such hypotheses against observable facts
      + the Kantian Austrians call this the "empirical" approach, leaving their own approach as the only true Austrian one. (The rejection of the positivist thesis is what separates the Austrian school from the rest, so if positivism is empiricism, then Austrianism must be non-empirical).
        + "Even though Mises’ language is strictly Kantian, “nothing in his argument depends on Kant’s system . . . Those who prefer an Aristotelian approach can easily translate Mises' terms into their own preferred usage.”"
          + "Even though one can reconstruct Mises’ system to fit within an Aristotelian framework if one wishes, the fact that Mises was a neo-Kantian and that his Kantian rationalism played a large role in shaping the epistemological base of the modern Austrian School isn’t something that can be simply brushed aside, because the arguments he used to ground his claims are decidedly not Aristotelian.1 If one believes an Aristotelian approach is needed in order to ground necessary truths about the world, he will not find it in Mises. As a side note, it is important to point out that Mises is not strictly an Orthodox Kantian. In order to identify the similarities and differences and their relevance, a brief overview of Kantianism and its origins is necessary."
      + "Viewed as a body of substantive hypotheses, theory is to be judged by its predictive power for the class of phenomena which is intended to “explain.” Only factual evidence can show whether it is “right” or “wrong” or, better, tentatively “accepted” as valid or “rejected.” As I shall argue at greater length below, the only relevant test of the /validity/ of a hypothesis is comparison of its predictions with experience. The hypothesis is rejected if its predictions are contradicted (“frequently” or more often than predictions from an alternative hypothesis); it is accepted if its predictions are not contradicted; great confidence is attached to it if it has survived many opportunities for contradiction. Factual evidence can never “prove” a hypothesis; it can only fail to disprove it, which is what we generally mean when we say, somewhat inexactly, that the hypothesis has been “confirmed” by experience. "
        + this is verificationism which is rooted in nominalism-sensualism. So the alternative we have is between Kantian mysticism vs nominalism-sensualism; nobody considers /true/ Aristotelian empiricism
  + demonstrate the problem with positivism on Obist grounds
  + The Austrian method, contra positivism; begins with "axioms" (namely, the action axiom) and builds the body of economic science on their basis. Positivism holds that axioms are arbitrary and any deduction from them produces only "analytic statements" and "tautologies" which provide no information about reality. Thus a response to the analytic-synthetic dichotomy is required for an empiricist Austrianism.
    + The Kantians deal with this problem with their "synthetic a priori," the Objectivists do it by demolishing the dichotomy as false.
    + the issue is: how do you achieve certainty (in general) or how do you achieve certainty within economic theory. The positivists say it is impossible, the Kantians say it is done through the synthetic a priori; the Objectivists say it can be done empirically.
    + The question centers around the actual epistemic status of these necessary economic truths which form the foundation of the Austrian approach; are they empirical or a priori?
+ "For the purposes of this article, Hume’s most important idea is his distinction between “relations of ideas” and “matters of fact”. “Relations of ideas” are necessarily true propositions because they are true by definition and thus say nothing about reality and aren’t derived from experience. “Matters of fact” are brute, contingent facts which happen to be the case but could have been otherwise and are derived from experience. In this Humean distinction one sees the precursor to the positivist attacks on the epistemic claims of the Austrian School. Their claims that praxeological axioms are arbitrary and the deductions from them are merely tautological and thus divorced from reality have their roots in Hume’s skepticism. After all, the logical positivists are simply the updated, modern version of Hume’s philosophy. The crucial question is, how does one answer these Humean charges and establish the existence of necessarily true propositions which aren’t just floating abstractions divorced from reality?"
** Mises' Kantianism
+ "Ludwig von Mises was the first Austrian thinker to adopt an epistemologically neo-Kantian position. His metaphysics differ from Kant’s in crucial ways, but many of the epistemological premises are still intact. To begin with, Mises (1962, 6) does not hold that our realm of experience is a subjective creation of the mind:"
  + "The much discussed question whether physical objects can or cannot be conceived as existing independently of the mind is vain. For thousands of years the minds of physicians did not perceive germs and did not divine their existence. But the success or failure of their endeavors to preserve their patients' health and lives depended on the way germs influenced or did not influence the functioning of the patients' bodily organs. The germs were real because they conditioned the outcome of events either by interfering or by not interfering, either by being present in or by being absent from the field."
+ "Nor does Mises (1998, 36) postulate a necessary existence of a world totally unknowable to man (nor does he exclude the possibility of such a world): “It is idle to ask whether things-in-themselves are different from what they appear to us, and whether there are worlds which we cannot divine and ideas which we cannot comprehend. These are problems beyond the scope of human cognition. . . . All the theorems of praxeology refer only to these categories of action and are valid only in the orbit of their operation. They do not pretend to convey any information about never dreamed of and unimaginable worlds and relations.”"
+ "Despite these divergences with Kant, Mises (1962, 18-19) still takes over his view that the human mind has an innate structure which implies the existence of limitations of our knowledge of “real” reality:"
  + "What we know is what the nature or structure of our senses and of our mind makes comprehensible to us. We see reality, not as it "is" and may appear to a perfect being, but only as the quality of our mind and of our senses enables us to see it. . . . our senses are imperfect and do not fully and faithfully reflect reality. . . . We must never forget that our representation of the reality of the universe is conditioned by the structure of our mind as well as of our senses. We cannot preclude the hypothesis that there are features of reality that are hidden to our mental faculties but could be noticed by beings equipped with a more efficient mind and certainly by a perfect being. We must try to become aware of the characteristic features and limitations of our mind in order not to fall prey to the illusion of omniscience."
+ Mises agreed with Kant that we can only experience reality through the categories, he thought that the categories were a product of evolution:
  + "“The human mind is not a tabula rasa on which the external events write their own history. It is equipped with a set of tools for grasping reality. Man acquired these tools, i.e., the logical structure of his mind, in the course of his evolution from an amoeba to his present state. But these tools are logically prior to any experience.”"
+ "If man can only experience reality through his imperfect, limited categories, and the realm of our experiences isn’t subjectively constructed by them so as to yield necessity, how can he know if his categories conform to reality at all? Mises (1962, 14-16) here gives a pragmatic answer, claiming that one can have confidence in the power of man’s categories to apprehend reality (at least to some extent) since he are able to engage in successful action using their faculties:"
  + "Natural selection eliminated those specimens and species which developed instincts that were a liability in the struggle for survival. Only those endowed with impulses serviceable to their preservation survived and could propagate their species. . . . Only those groups could survive whose members acted in accordance with the right categories, i.e., with those that were in conformity with reality and therefore—to use the concept of pragmatism—worked. . . . Since the a priori categories emanating from the logical structure of the human mind have enabled man to develop theories the practical application of which has aided him in his endeavors to hold his own in the struggle for survival and to attain various ends that he wanted to attain, these categories provide some information about the reality of the universe. They are not merely arbitrary assumptions without any informative value, not mere conventions that could as well be replaced by some other conventions. They are the necessary mental tool to arrange sense data in a systematic way, to transform them into facts of experience, then these facts into bricks to build theories, and finally the theories into technics to attain ends aimed at."
    + "For Mises (1962,8), the category of action is the “fundamental category of epistemology, the starting point for any epistemological analysis”. Praxeology starts with the proposition: man acts. Mises (2003, 29) argues that the action axiom is not and cannot be arrived at inductively, but must be understood introspectively before any external experience can be interpreted as an action: “Nothing is more clearly an inversion of the truth than the thesis of empiricism that theoretical propositions are arrived at through induction on the basis of a presuppositionless observation of “facts.” It is only with the aid of a theory that we can determine what the facts are.” The category of action and its subsequent categories are thus prior to experience, they are “not subject to verification and falsification on the ground of experience and facts. They are both logically and temporally antecedent to any comprehension of historical facts. They are a necessary requirement of any intellectual grasp of historical events” (Mises 1998, 32). In other words, they are a priori. For Mises (1962, 18), the characteristic feature of a priori knowledge is that “we cannot think of the truth of its negation or of something that would be at variance with it”. For example, one could not even imagine a world without the existence of causality and teleology.  "
    + "With regard to causality, Mises (1998, 22; emphasis in original) states: “Man is in a position to act because he has the ability to discover causal relations which determine change and becoming in the universe. Acting requires and presupposes the category of causality. Only a man who sees the world in the light of causality is fitted to act. In this sense we may say that causality is a category of action. The category means and ends presupposes the category cause and effect. In a world without causality and regularity of phenomena there would be no field for human reasoning and human action.” This passage only serves to establish that causality as a prerequisite of action, which doesn’t itself prove that it actually applies to the external world. Here Mises is moving in a circle; since human action is caused by man, the action axiom has to be validated by at least an implicit reference to causality, but then causality is validated on the basis that it is a prerequisite of human action. On this circularity, Mises (1998, 23) comments: “We are fully aware that in asserting this we are moving in a circle. For the evidence that we have correctly perceived a causal relation is provided only by the fact that action guided by this knowledge results in the expected outcome. But we cannot avoid this vicious circular evidence precisely because causality is a category of action. And because it is such a category, praxeology cannot help bestowing some attention on this fundamental problem of philosophy.” Elsewhere, Mises (2007, 9) affirms the impossibility of proving causality and the validity of scientific induction: “There is no deductive demonstration possible of the principle of causality and of the ampliative inference of imperfect induction; there is only recourse to the no less indemonstrable statement that there is a strict regularity in the conjunction of all natural phenomena. If we were not to refer to this uniformity, all the statements of the natural sciences would appear to be hasty generalizations.” Thus, causality can be no more than an assumption which makes human action possible."
+ "The problem of reconciling the categories of causality and teleology can be compared to Kant’s task of reconciling modern science with belief in “God, freedom and immortality”. Contrary to scientism, Mises (1962, 7) writes that “The natural sciences are causality research”, while “the human sciences are teleological”. To say that “man acts” is simply another way of saying that man has free will. The faculty of volition is what differentiates action from mere behavior. The basic validation of the action axiom is that one affirms it in the process of trying to negate it.. But for this validation to work, man has to have free will. If man has no free will, a man saying that “man doesn’t act” would not actually be an action, but merely a disteleological noise produced by a complex chain of mechanistically determined causes, and thus the man would not fall into a performative contradiction by uttering that sentence. One could train a parrot to say “parrots don’t act”, but that would not mean that the parrot fell into a performative contradiction and thus established that parrots in fact do act. Given the absolutely crucial importance of human volition to the science of praxeology, where does Mises stand on the free will question? It might be surprising to find out that Mises, the arch-praxeologist, was actually a determinist. In a brief discussion on volition, Mises (1998, 46) writes: “The innate and inherited biological qualities and all that life has worked upon him make a man what he is at any instant of his pilgrimage. They are his fate and destiny. His will is not "free" in the metaphysical sense of this term. It is determined by his background and all the influences to which he himself and his ancestors were exposed.” Here seems to be a devastating contradiction at the very heart of Mises’ system. How can he affirm the proposition that “man acts” while being a full-blown determinist? The answer lies in the fact that Mises does not ascribe volition to man in the metaphysical, but in the methodological sense. Mises (1998, 18) points out that “No bridge connects-as far as we can see today” the worlds of “physical, chemical, and physiological phenomena and the internal world of thought, feeling, valuation, and purposeful action.” and goes on to argue that “as long as we do not know how external facts—physical and physiological—produce in a human mind definite thoughts and volitions resulting in concrete acts, we have to face an insurmountable methodological dualism.” (Mises 1998, 17; emphasis in original). It is thus not any metaphysical truths that commits science to methodological dualism, but the present lack in our scientific knowledge about the causes of human actions. Thus, Mises (2007, 1) claims science must adopt a dualistic approach “less as a philosophical explanation than as a methodological device”. Thus Mises develops a kind of “human action of the gaps” explanation of free will."
