#+title: A Defense of Planned Obsolescence | Planned Obsolescence is a Lie

* Main Body
** Hook
Planned obsolescence is almost universally presented as a nefarious plot by evil capitalists to make sure that you get less for your money. These depictions are all flawed to their core as there is absolutely nothing wrong with designing or selling shoddy products. Here's why.

** The Impossibility of Free-Market Cartels
The tale is often told that a group of lightbulb manufacturers formed the Phoebus Cartel as a means to reduce the lifespan of their bulbs to sell more. But rarely is it investegated how such a strategy could work and what assumptions it rests upon.

Consider first the unhampered market. If I want to form a cartel to drive up my profits, I could do this by either conspiring with others to keep prices high, or by keeping the quality of the bulbs low, it is clear that these two strategies would be entirely equivalent. If a group of companies, $A,\cdots,Z$, came together and decided to keep the price high, who benefits from this arrangement? If we assume that $A$ is the most efficient company with $Z$ being the least efficient and so on for the in-between values, this means that $Z$ is benefited at the expense of $A$. This is because, $A$ is able to sell the bulbs at a far lower price than $Z$, and thus gain a far greater market share and therefore far greater profits. The same is true for the strategy of making low-quality bulbs that burn out quicker; if the $A$ bulbs are able to last 10,000 hours and $Z$ bulbs only 1,000; this means that without any cartel agreement $A$ could quickly eat into $Z$'s market-share and gain greater profits themselves, assuming all other factors are kept equal.

Thus these cartel arrangements benefit the least effective members at the expense of the most effective members. To compound this, if we are in an unhampered market, this means that any company outside the cartel can simply produce at normal market rates, and undercut the /entire/ cartel, meaning the cartel is still subject to outside competition and cannot raise the price beyond what the market will allow. After all, if it was possible for businesses to arbitrarily reduce the quality or increase the price of their products, why would they settle for the 1,000 hours reported by Veritasium? Why not make the lightbulbs last only marginally longer than a candle or other equivalent would last? Heck, if this strategy of planned obsolescence is truly viable, why would candles ever have been made to last as long as they do? Why would anything be made to a high quality at all? How is it that we ever advanced beyond what nature provides? The answer is clear, competition drives men to innovate, and thus it is not a viable strategy to deliberately make worse products.

Some might contend that these cartels form natural monopolies and can therefore drive out any outside competition via predatory pricing. However, predatory pricing cannot work to drive out competition as has been demonstrated in the case of Herbert Dow, who was an American industrialist who sold bromine and other such products. Dow decided to export some of his bromine to Europe where a German cartel was the prominent seller. Dow was able to price his bromine lower than the Germans, so they warned him that if he did not get off of their turf they would drive him out, adopting this predatory pricing strategy. Dow refused to bow to their threat and thus they started selling at well below the market rate in the US, Dow swiftly took advantage of this by buying up all of this cheap bromine they were flooding the US with and then reselling at a higher price in Europe.

#+begin_quote
When this 15 cent price was made over here instead of meeting it we pulled out of the American market and used all of our production to supply the foreign demand. This, as we afterword learned, was not what they anticipated we would do. We are absolute dictators of the situation, one result of this fight was to give us a standing all over the world, we are in a much stronger position than we ever were.[fn:1]
#+end_quote

Veritasium makes the argument that the lightbulb cartel was maintained by fining members whose bulbs lasted too long, but it is not explained how on Earth such fines are enforced. If I was a free market enterprise and a representative from the Phoebus cartel came to me and said, "LiquidZulu, you are hereby ordered to pay 10,000 francs for your manufacture of long-lasting lightbulbs." I would simply respond by telling them to go ahead and fuck themselves right up the ass. Unless they have some manner of monopoly grant over lightbulbs I see no way that they could successfully enforce such a fine, and this is not explained in Veritasium's video or any of the multiple clone videos derived from it.

How, then, do these cartels form? The answer is and must be that cartels form and are maintained as a result of aggressive interference into the market, rather than being some natural feature of the market. For instance, there are numerous intellectual monopoly grants in the form of letters of patent enforced over the technologies that are cited as examples of planned obsolescence. These monopoly grants prevent outside competition from breaking up the cartel, because if I have a patent over some mobile phone design, nobody else is able to replicate that design and compete with me. The state can back these cartels by providing monopoly grants in other ways; for instance licensing is required to engage in many trades. These licenses can prevent outside competition. US hospitals are the prime example; men are not free to build and run hospitals as they see fit, rather a board of local "experts," who are already hired by existing hospitals decide whether there is a need for a new hospital, and if they deem that there is not then no new hospital may be built. It is of note here that we now have essentially ever-lasting lightbulbs, so the empirical evidence would indeed paint the picture that these cartels are impotent to keep the quality of bulbs down.

** Defending Planned Obsolescence
Thus, planned obsolescence is a bad thing if and insofar as it is a result of an industry warped by these aggressively formed and maintained cartels. However, this is not the critique against planned obsolescence levied by the socialist opponents you see so heavily featured in commentary on the subject. Rather the critique is that it is a problem stemming from free markets and free trade---that greedy businesses deliberately making poor-quality products is an evil. This argument is entirely false, and the reason is simple; if I want to manufacture a lightbulb it may be the case that it is far cheaper to manufacture one that lasts only 1,000 hours as opposed to one that lasts 100,000. Thus I could sell the "lower quality" product for cheaper, and if a consumer does not want the bulb to last 100,000 hours but is entirely satisfied with the far shorter-run bulb, he is able to get what he wants for a lower price---this is a win-win situation. The failure the socialist critics come to on this point, is that they are determining the quality of goods as an engineer might, rather than as an economist should. To the economist, all that can be said about this voluntary exchange is that both parties profit because both receive a good that they value higher. Thus an engineer might complain about using aluminium to manufacture cars, because there are far stronger and lighter carbon composite materials, what the engineer does not consider as it is outside of his study is that said materials make the car far more expensive. Thus if I am purchasing a car to take me to work and back I do not care about whether the frame is made from some fancy composite material, thus I would prefer the far cheaper material. The same is true of any clothing, electronics, or anything else that is made in such a way that it degrades quickly.

Moreover, if they are concerned about the quality produced by the per se more efficient capitalist market, how on Earth is central planning the solution? A central planner cannot correctly allocate resources and cannot effectively determine what to produce in the first place.

** On Perceived Obsolescence
It is entirely possible to, right now, purchase goods that will last you for years. I have purchased multiple terrible chairs in my time which each broke prior to being gifted a Herman Miller Aeron, and these things can last for decades without degrading in quality---but that extra sturdiness comes with a far greater price tag, so if that is not something you are interested in, you may well prefer the cheaper options. The socialists will bring forth also the point of "perceived obsolescence" in their Motte-and-Bailey approach, thus they could shift to the point that though companies do provide goods that can last you plenty of time, they release new products the next year with a fancy new paintjob or something thus causing men to buy the new version when the old version is perfectly fine.

All that can be said to this is a fat old waa waa wee waa, suck it the fuck up. You have no place to complain if you--on your own volition--choose to buy a new phone when your current phone works perfectly fine. This is my phone, I cannot remember what year it was made, it was already old when I bought it, I only bought it because my previous phone stopped working, I feel absolutely no desire to purchase a newer model. Same for my trousers, I have worn these exact trousers just about every day for the past three or so years, you can see this by the fact that I have had to stitch it up along the groin. I will only throw these trousers out when I am damn well good and ready to throw them out, nobody is forcing me to buy new ones. Same for this belt, I made it myself and spent about 3 pounds doing so, I have worn it every day since late 2019, and I feel absolutely no need to replace it. So how about instead of shaking your fist at companies for releasing shiny new products every year you decide on your lonesome to not give a damn and not purchase the shiny new products when the old ones work just fine. It is entirely /your/ fault if you buy new stuff to replace stuff that still serves your purposes. Stop complaining about the choices you yourself are making.

** CTA
Therefore we see that perceived obsolescence is not a problem and planned obsolescence is only a problem insofar as the state enforces intellectual monopoly grants, and to find out why these grants are the true source of evil here, you have to watch this video where I explain why all forms of intellectual property are a myth and demolish human flourishing and creativity.

* Footnotes

[fn:1]Burton W. Folsom, /Herbert Dow and Predatory Pricing/, https://fee.org/articles/herbert-dow-and-predatory-pricing/
