#+title: The "Impossible" Economics of the iPhone
#+yt-titles: Why It's "Impossible" to Make an iPhone
#+options: num:nil toc:nil
#+begin_export md
---
title: 'The "Impossible" Economics of the iPhone'
description: "The intricacies of this everyday product are reveiled."
date: 2024-12-16
---
#+end_export

* The Complexity of the iPhone
The Moon landing is perhaps the most stark example of the power of human ingenuity that one might come up with. Consider the vast enormity of the technical knowledge required and the calculations involved in sending living humans into this final frontier. The perfectly-timed rocket burns, the precisely determined angles of attack, not to mention the innumerable engineering problems both large and small that must be overcome to build the rocket in the first place. And now consider, that for $40 a month[fn:1] you can own a device of far greater complexity. A device that pushes to the very edge of our understanding of material science and nanotechnology. One that can be constructed only by the cooperation of hundreds of millions of people and which in a single second can perform over 66 times the total combined number of computations of the entire 8-day Apollo 11 mission.[fn:2]

This device is called an iPhone. It is surely a marvel of technology and a testament to the enormous power of mankind just as fully as the Saturn V rocket. It might not seem like it, but consider the innumerable steps required to construct just one functioning iPhone.

First, the phone has various components; these components, along with the labour needed to assemble them are called factors of production. But of course, these factors also don't come from nowhere. They require their own factors, and those factors require factors, and so on.

* The Production of a Microchip
You can see how quickly this is getting out of hand, but let's dig even deeper. These chains of inputs being progressively transformed and combined into different goods are called lines of production. Consider just the process used to create the microchips to get an idea of the seemingly impossible intricacy involved.

The iPhone 16 Pro contains dozens of individual microchips with separate functions that require their own particular considerations in construction, the most important is called the A18 Pro; it is the brain of the phone. This one microchip contains more than 20 billion[fn:3] nanoscopic transistors capable of performing trillions[fn:4] of computations every second and it is crammed into a space about the size of your thumbnail.[fn:5]

If you could work day and night, making one of these transistors every second with atomic accuracy and no mistakes, it would take you over 600 years to finish just one of these processing units. A semiconductor fabrication plant can produce 10s of thousands of wafers per month, each containing about 500 individual A18 chips.

Over the course of a few months, each wafer travels between dozens of machines, performing hundreds of separate processes to construct a grid of chips. These chips must then be cut, tested, packaged, and shipped to their final destination. And of course, each fabrication machine is itself based on a highly complex knowledge and requires many thousands of different steps in its construction.

It is simply not possible for one man to have all of the knowledge and expertise required to orchestrate this process. Millions upon millions of individuals with vastly different areas of expertise across great spans of time who do not share a belief system, culture, or even a language were able to do it without so much as getting together and coming up with a specific plan of action.

No one person enumerated and organised the countless steps required to construct a single iPhone, nor even a single one of the components used in its construction. And nobody could do this; not with all the time and resources in the world at their disposal. So how was it done?

* Direct vs Indirect Exchange
The answer can be found in the astronomical power of the indirect exchange economy.

Let me demonstrate this power by comparing it to a simpler system: barter. Perhaps John wants some of Sally's pears, and Sally wants some of John's carrots. This is a system of /direct/ exchange, so John would give carrots to Sally, and Sally would give pears to John. This is called a double coincidence of wants; each party wants what the other has /more/ than what they currently have. This is required for any exchange to take place---if John preferred his carrots to Sally's pears, he would not agree to the trade.

A problem with the barter system, therefore, arises wherever there is /not/ a double coincidence of wants. John perhaps desires a new tractor to plough his field, and he knows that Doug has a spare one. When John attempts to trade the tractor for carrots, he finds that Doug refuses.

It does not matter what the specific reason for the refusal is, all that matters is that even though Doug doesn't necessarily want to keep his spare tractor, and isn't even using it, he does not want what John has to offer /more/ than the tractor.

The way to solve this problem is with /indirect/ exchange. John might know that he can trade his carrots for salt, and that Doug would be willing to trade salt for the tractor. Of course, it might be the case that he /also/ can't directly trade carrots for salt, so he has to first trade the carrots for firewood which he can then use to exchange for salt; and maybe he can't trade carrots for firewood, and so on. Very quickly we could end up in a situation where John must perform dozens of individual trades with different people in town involving products that he knows little about just to get the tractor that he needs.

These intermediary products that John has no intention of directly using are called media of exchange---they are goods that are acquired for the purpose of trading them with other people.

You can see the problem we face when we have a great many media of exchange, like in the basic barter system. It becomes near impossible for John to predict how many individual exchanges he will have to make, and how much he will have to exchange in each step. This is where money comes in.

As our barter system evolves, eventually people will start holding onto more goods that are in high demand because they know that those goods are more able to be exchanged down the line. The end state of such a system would involve a good which is desired by every person in the market, a universal medium of exchange: money.

So how does this money-economy help us make an iPhone? Basically: for each step in the gargantuan line of production required, there is someone looking to do nothing else, except make a profit. Economists call this an /incentive/.

These incentives have a powerful effect: there are perhaps many thousands of different ways to perform the single step of impregnating the glass screen with potassium to increase its durability. The company that makes the glass routinely experiments with different chemical processes---they arrived at the one they use currently by subtracting the cost of the process from the expected return. This is called economic calculation.

Notice the power that this brings: the makers of the glass do not need to know anything about the countless steps involved in producing any of the many billions[fn:6] of products that it will be used within, or even what those products will be. Nor do they need to know anything about the massively complex lines of production involved in making the various factors required to make the glass. All they must focus on is making the glass such that they maximise the profit.

* Entrepreneurship
This work is not quite as mathematical as the profit equation makes it seem, though. For both the cost and the return there is a great deal of uncertainty. You cannot ask a computer to spit out whether or not there will be a silica shortage 10 months down the line and plan accordingly; you can't consult a mathematical theorem to determine how much people will desire some new feature you are implementing; in short, the specific costs and returns that come about from a given product depend upon the uncertain and ever-changing supply of and demand for the product in question.

The way to deal with this uncertainty is through the process of entrepreneurship. The entrepreneur makes an educated guess on what the future conditions of the market will be, and adjusts the lines of production under his control accordingly. Importantly: this guessing is not random in the slightest. If any entrepreneur makes a wrong guess, he will be able to discover this by the fact that he is making a loss, rather than a profit. With sufficient accounting, he can track down which areas of his business are responsible for the loss and adjust accordingly.

Any entrepreneur who fails to respond to the market properly, and remains gung-ho in his wrong decisions will quickly run out of funding and leave the profession. In this way, there is a sort of natural selection that allows only those entrepreneurs who are best at predicting future market conditions to stay managing the lines of production.

Steve Jobs' decision to create the iPhone back in 2007 is a perfect example of the risk-taking involved in good entrepreneurship. At the time, the BlackBerry was seemingly beyond reproach. In that year, it was at a 44% market share, up from 33% just a year before.[fn:7] In the midst of this, Apple spent over $150 million to create the original iPhone[fn:8] and committed its best people to the project:

#+begin_quote
The iPhone project was so complex that it occasionally threatened to derail the entire corporation. Many top engineers in the company were being sucked into the project, forcing slowdowns in the timetables of other work. Had the iPhone been a dud or not gotten off the ground at all, Apple would have had no other big products ready to announce for a long time. [...] according to a top executive [...], the company's leading engineers, frustrated by failure, would have left Apple.[fn:9]
#+end_quote

The decision to make the iPhone represents what economists call an opportunity cost---and a massive one at that. Opportunity cost refers to the value of all of the opportunities that one gives up by selecting a given course of action. So by spending all of the engineers and money on the iPhone, Apple could not put these resources to other uses. These resources can only be used towards one end at any given time---the cost involved is that no new Macintosh computers could be developed. No new iPods could be devised. No other new products were possible because all the eggs were thrown into the iPhone basket. This represents a gigantic risk. If Jobs had been wrong, Apple very well might have gone the way of the many now-dead businesses from that era.

But with great risk comes great reward---if Jobs had played it safer, it could have also cost Apple greatly. Perhaps we would all still be walking around with BlackBerry or Nokia phones. Perhaps Apple would have had to put their resources towards established products, and we would end up with super-advanced iPods for our music needs and a separate phone for calls and emails. This would represent a worse world for everyone.

An iPhone is not just a phone with a touch screen. It is your map of any foreign city, your portal to order food from anywhere you desire at the touch of a finger. It is a portable video camera to capture your fondest memories, and a library with every book you could ever hope to read. It represents such a powerful and fundamental shift in the way that we live our lives that having a smartphone is essentially a requirement for being a member of the modern world.

This is just one of the uncountable gifts given to us by entrepreneurs like Steve Jobs. It is not /just/ fair that they be rewarded for their efforts in enriching us by earning profits but also, this is a /requirement/ for the enrichment to even take place.

It is because these entrepreneurs make profits that they are able to make losses. And because these profits and losses represent the actual conditions of the market, the entrepreneur knows when he is making an inefficient use of resources. The socialist expects to reap the same rewards borne from the free choice of capitalists by preventing them from choosing freely. Without profit, it is impossible for the central planning bureau to /deliberately/ choose efficient lines of production---they are left only with random guesswork pertaining to a process that no man could hope to understand.

It is only because of capitalism and the beauty of indirect exchange that we have such marvels as iPhones and rocket ships. We cannot get an effect without the cause. Let us not forget this.

* Footnotes

[fn:1]iPhone 16 Pro on the [[https://www.apple.com/us/shop/buy-iphone/iphone-16-pro][Apple Shop]] ([[https://archive.ph/IhGsI][archived]]).

[fn:2]Apollo 11 lasted 8 days, 3 hours, 18 minutes, and 35 seconds = 703 115 seconds
Apollo 11 computations = 0.043 * 10^6 / sec = 43 000 Hz
A18 Pro computations > 2.147 * 10^12 (GPU) + 16.88 * 10^9 (CPU) / sec ~= 2 000 000 000 000 Hz

700 000 * 43 000 = 30 100 000 000 total computations

A18 Pro   > 2000 billion computations in 1 sec
Apollo 11 \approx 30.1 billion total computations

So A18 Pro does about 66 times the number of computations in a single second than the total number of computations that could have happened in the entire Apollo 11 mission.

[fn:3]Estimate based on the reported transistor counts of previous chips as provided by Wikipedia: https://en.wikipedia.org/wiki/Apple_silicon#Comparison_of_A_series_processors

[fn:4]A18 Pro has 2 cores @ 4.04 GHz and 4 cores at 2.2GHz; 2 * 4.04 + 4 * 2.2 = 16.88 billion CPU computations. The A17 Pro GPU was clocked at 2.147 TFLOPS, presumably the A18 Pro would be even higher, https://www.cpu-monkey.com/en/cpu-apple_a17_pro

[fn:5]The A18 Pro is about 1cm^2. My thumbnail is about this size, so I assume the viewer's is too.

[fn:6]"One of the world's oldest products faces the digital future". /[[https://www.economist.com/science-and-technology/2017/10/12/one-of-the-worlds-oldest-products-faces-the-digital-future][The Economist]]/. 12 October 2017. [[https://web.archive.org/web/20171014001123/https://www.economist.com/news/science-and-technology/21730128-soon-gorilla-glass-and-its-descendants-will-be-everywhere-one-worlds][Archived]] from the original on 14 October 2017.

[fn:7]"Forget the iPhone: BlackBerry is still the one to beat". /[[https://fortune.com/2007/08/24/forget-the-iphone-blackberry-is-still-the-one-to-beat/][Fortune]]/. 24 August 2007. [[https://web.archive.org/web/20230831162228/https://fortune.com/2007/08/24/forget-the-iphone-blackberry-is-still-the-one-to-beat/][Archived]] from the original on 31 August 2023

[fn:8]"Apple Spent Over $150 Million To Create The Original iPhone," /[[https://www.businessinsider.com/apple-spent-over-150-million-to-create-the-original-iphone-2013-10][Business Insider]]/.

[fn:9]Fred Vogelstein, "And Then Steve Said, 'Let There Be an iPhone'," /The New York Times/, 2013-Oct-4
