#+TITLE: Open Borders is the Libertarian Position | [Dave Smith/Hoppe] and Border Socialism | Borders Should be Open

* Notes
** Dave Smith vs Spike Cohen https://www.youtube.com/watch?v=S2hcFxdae7M
+ prop:"Libertarians should demand that the government allow people to travel into and out of the United States as they wish in defiance of its attempts to use crises like COVID to restrict our freedom of association"
+ "open borders is not the correct libertarian position"
  + philosophical
  + practical
+ you cannot deduce from property rights that there should be complete free access to public possessions
+ "if somebody stole your wallet this doesnt mean that the wallet belongs to everybody in the world now"
+ "you dont get to the point where this property [public possessions] belongs to everyone in the world equally"
+ if youre talking about property where there are no rights to exclude people from it this is not libertarianism
+ "do we believe that public schools ought to let some random 55 year old man in who just wants to go into the girls locker room"
+ "should state schools offer a place to the dirtbag dropout equally to the valedictorian"
+ "it would be a disaster if we let it play out that way."
+ "its not libertarian to have open or closed borders -- the only answer is to privatise everything, but in the meantime do we have to support government opening the commons to everybody, closing completely would be a violation of NAP but opening completely would also be especially because the majority of americans do not support this"
+ welfare state argument
  + regulate food people eat because obease people require a lot of welfare
+ "you couldnt regulate food habits because that violates the NAP but you could have it that people cannot access property that doesnt belong to them"
+ "none of this is perfect when you have a government, but its not perfect either way --- closed or open"
+ "the idea that the libertarian position has to be that the borders are completely open, that the commons are completely open does not follow from the NAP"
+ "I don't support caging people or separating families but I don't support open borders"
+ "homeless people and drug addicts shouldnt be allowed on public playgrounds"
+ "idiot dropouts shouldnt be accepted by state universities the same as smart people"
  + disanalogy, this would be discussing how best to run a statist system, open borders is the position that the state has no business running the borders.
+ "in the meangime I would advocate for anything that is (1) consistent with libertarianism (2) actually would work"
+ "when 100k Hatians show up at the border nobody invited them onto their property"
+ "we can reasonably assume that the parents wouldnt want some 50 year old sex offender coming into the school"
+ "there are few issues the american public are more united on that not wanting open borders"
  + "im for legalising heroin, I'm fine with taking unpopular positions so long as they are the correct libertarian position and it will make the world a better place"
    + "open borders isnt the correct libertarian position and it will make the world a worse place"
+ "Cato are wrong in trying to predict that open borders would be great as they forget about human action"
  + then why can Dave predict that open borders would be bad?
+ "you are importing people into a white hot culture war with blah blah blah and this means you cant predict it well"
  + /importing/ is false, open borders is simply having it that the state doesnt stop them
+ "when Biden was coming in immigration surged because people had the perception that there would be lower restrictions which would be even worse if we said no restrictinos at all"
  + "what would the reaction to that be? I see sure disaster"
+ "if we have open borders there would be a lot more welfare"
  + send a rapist to prison and he will probably rape in there
+ "libertarianism says both people must consent but its overwhelmingly the case that the american people dont consent to open borders"
+ "is there any amount of immigrants who you knew would come if you pressed the button that would make you not press the button"
** REJOINDER TO HOPPE ON IMMIGRATION https://cdn.mises.org/22_1_38.pdf
+ contention is Hoppe says govt is justified in imposing limitations on immigration,[fn:1] Block says it is not.[fn:2]
*** Areas of Agreement
+ if a billion chinese or indians or africans were to suddenly immigrate to the US this would be an unmitigated disaster for american society. They would bring with them the culture that has lead their home societies to vast suffering.
  + under an open borders society it is extremely likely that a disasterous occurrence of this sort would befall us. International transportation is relatively cheap so the gains to those Chinese, Indians, or Africans would be enormous.
+ free international movement of (1) goods, (2) capital and (3) people are not at all on par. There is difference between the first two on one hand and the third on the other as a matter of libertarian law.
  + in the case of goods and capital there are clearly two parties, one exporter and one importer, however that is not necessarily the case for people.
*** Areas of Disagreement
** Information to include
+ as per my video on neo-prags, the debate is entirely up to what is the correct natural law position, as any rejection of natural law on pragmatic grounds is contradictory and thus objectively wrong
+ private borders /is/ open borders
  + "we want private borders not open state borders"
    + open state borders are literally just lines on a map, with 0 corresponding rights infringements
  + adherence to private property means the state has no right to exclude people from public possessions
+ "but what do in meantime"
  + what is legal now doesnt become illegal in the future, and what is illegal now doesnt become legal in the future. It is either the case that the correct answer to borders is open, or closed, it cannot be anything else. It cannot be that right now the correct answer is closed borders but in the nebulous /future/ natural law flips and it becomes the correct answer to have open borders.
  + "we dont live in the perfect libertarian society, we live in a statist society"
    + yes, so in the meantime we advocate that society be moved towards adherence to natural law
+ Ace's point of no chain of title transfer allowing for taxpayers to exclude people from public possessions
+ "run private land as close to how a private owner /would/ run it"
  + unknowable
  + "reasonably assumed that a private person wouldnt want blah blah"
    + well, it can be reasonably assumed that no private person would want the unvaxxed to be on their property, \therefore vax mandates
  + we dont want more efficient government, we want no government
+ "what about the welfare state"
  + prison rape analogy
+ order of operations argument
  + if you are surrounded north south east and west by people who hate you then you want closed borders
    + whether you want it is irrelevant to whether it is just
+ open vs closed borders is not a question of preference, it can be proven which one is correct
+ gradualism "do it in the right order though"
+ "what is the most libertarian way of managing govt possessions, if we could divert money from the ATF to government housing would we?"
  + this is disanalogous to open vs closed borders, diverting funds from the ATF is diverting funds from the states enforcement apparatus. Open vs closed borders is a question of whether the state is excluding people from public possessions, they have no right to so it is a crime for them to exclude people it isnt a crime for them not to. Only closed borders is criminal, open borders is not.
+ "whilst we have govt possessions we should look at what way of management is best and to what ends"
  + open borders is the explicit rejection of the state management of borders
+ consider a library, purpose of the building is for people to go in and read or take out books in silence. State claims library as a public good making it open to all. But there are two unequal groups --- (1) net tax payers, and (2) net tax consumers.
  + so it may be argued that (1) has a greater claim than (2), but that is not the borders debate. Open vs closed borders is not referencing a conflict between a tax payer and a tax consumer over the use of a public possession, its referencing the conflict between the state and someone else over the use of public possessions that the state has no just say to
    + but a homesteader has the greatest say
 + "taxpayers can 'within reason' exclude others from public possessions"
   + what counts as 'within reason' is entirely up to subjective preference, one may claim that its entirely within reason to exclude the unmasked or unvaxxed
+ "homesteading doesnt work because neither the state nor the hobo in the public park cares about homesteading, making it impractical under current circumstances"
  + which is irrelevant, 2+2 still makes 4 whether a single person is aware of this fact, and homesteading still appropriates unowned property whether a single person is aware of this fact. Moreover, the practicality or lackthereof of the homestead principle does not change its truth

* Seo Checklist
** Points to hit [0/14]
+ [ ] who's the character?
  + [ ] their want?
  + [ ] their need?
  + [ ] their flaw?
  + [ ] how do they grow?
  + what story/journey could the above create?
+ [ ] what's the desire/motivation of the story?
+ [ ] what's the obstacle?
+ [ ] what're the stakes --- why is it important?
+ [ ] make them care
  + [ ] show what you have so the audience feels the loss when you lose it
+ [ ] what's the resolution --- the one core idea that is the final message of the video that wraps everything up?
  + deliver on the title and thumbnail
+ [ ] storyboard it [0/3]
  + [ ] storylines you have
  + [ ] hook for each
  + [ ] different things that can happen
+ [ ] attach a story to every point I make and tell the story before I make that point
+ [ ] answer questions using spectacle
+ [ ] if things go static stories die, because life is never static.
+ [ ] drama is anticipation mingled with uncertainty
+ [ ] make comment goals (2 or 3)
+ [ ] cater to the archetypal viewer
+ [ ] reference popular media
** Questions to ask [0/11]
+ [ ] is there incentive to watch until the end?
+ [ ] can I add something?
+ [ ] what are the different loops that I can open?
+ [ ] what are the different questions that the viewer could ask themselves?
+ [ ] what's the hook?
+ [ ] what do viewers need to see in the first few seconds based on the title and thumbnail so that they feel like their click is worth it?
+ [ ] is there a way to make the viewer laugh or feel surprised or feel something in the first 10 seconds?
+ [ ] is there a way to have two storylines?
  + [ ] surface level story, and hidden stories (finding nemo is ostensably about finding nemo, but really about marlon addressing his insecurities as a father)
  + [ ] is there a way to build surface level and underlying tension in each story?
    + short term: will dory's short term memory make her forget what marlon told her, long term: will we find nemo?
+ [ ] am I giving them 4 or 2+2?
+ [ ] in doing X big thing [0/3]
  + [ ] what do I want?
  + [ ] what happens if I dont get what I want?
  + [ ] what will I do to get what I want?
** Editing [0/3]
+ [ ] Show where possible
+ [ ] if theres a bit of information where you can delete what is before and after it and it flows just as well, cut it
+ [ ] tell stories with B-roll

* Main Body

* Footnotes
[fn:2]Block, Walter. "Rejoinder to Hoppe on Immigration." /Journal of Libertarian Studies/ 22, No. 1 (2011): 771–792.

[fn:1]Hoppe, Hans-Hermann 2002. “Natural Order, the State, and the Immigration Problem.” /Journal of Libertarian Studies/, Vol. 16 No. 1, Winter, 75-97. http://www.mises.org/journals/jls/16_1/16_1_5.pdf
