#+title: 0 Course Outline

This document is part of a course which you can find [[https://liquidzulu.github.io/libertarian-ethics][here]]. I provide the textual version for free to the public to make people aware of the facts contained within and to (hopefully) convince people to purchase the video course. This course is intended primarily as a video experience, and that is where my focus will be in terms of quality, so I do encourage you to check it out if this content is at all interesting to you. The course is sold on a pay-what-you-want model and is copyleft, meaning other people have the right to re-publish it at will. I simply encourage anyone who appreciates the work put into this course to purchase it such that I may make more in the future, and if you do choose to republish any section, please credit me and extend to your audience my request to purchase.

* Missing info
+ custodianship---third party having custodial rights over a stolen property because they have a greater claim than the thief
  + There is a property X stolen from A by B, C takes the property from B. It is clear that C has a greater claim than B, but a lesser claim than A; ownership rights are ordinal in this sense the question is; is C's right in X one of custodianship, meaning does he have ownership if an insofar as A does not come to re-possess it, thus meaning C could consume it in the meantime. or is C's right one of guardianship, meaning he merely has the right to preserve the property for A?
    + custodianship makes sense because C has the greater claim than B, and guardianship is generally thought of as pertaining to children
    + but guardianship also makes sense because A still has the "real" ownership
+ trading retribution rights
