#+title: 4. Contract Theory
#+EXPORT_FILE_NAME: ./md/contract-theory.md
#+PROPERTY: header-args :tangle ./slides/contract-theory.md
#+OPTIONS: toc:nil
#+begin_export md
---
title: "Contract Theory"
description: "The proper theory of contracts deals with the question of when a given transfer of title to property is legitimate and thus justly enforceable. This theory illuminates the answer to certain pernicious questions such as: can a man sell himself into slavery? Is fractional reserve banking legitimate, or a form of fraud?"
n: 4
date: 2023-04-25
---
#+end_export
#+begin_export latex
\tableofcontents
#+end_export

#+begin_src md :exports none
---
marp: true
theme: uncover
class: invert
---

# 4. Contract Theory
#+end_src

#+begin_quote
The right of property implies the right to make contracts about that property: to give it away or to exchange titles of ownership for the property of another person. Unfortunately, many libertarians, devoted to the right to make contracts, hold the contract itself to be an absolute, and therefore maintain that any voluntary contract whatever must be legally enforceable in the free society.

---Murray Rothbard[fn:1]
#+end_quote
#+begin_src md :exports none
---

<!-- _footer: Murray Rothbard, *The Ethics of Liberty* -->

> The right of property implies the right to make contracts about that property: to give it away or to exchange titles of ownership for the property of another person. Unfortunately, many libertarians, devoted to the right to make contracts, hold the contract itself to be an absolute, and therefore maintain that any voluntary contract whatever must be legally enforceable in the free society.
#+end_src

This document is part of a course which you can find [[https://liquidzulu.github.io/libertarian-ethics][here]]. I provide the textual version for free to the public to make people aware of the facts contained within and to (hopefully) convince people to purchase the video course. This course is intended primarily as a video experience, and that is where my focus will be in terms of quality, so I do encourage you to check it out if this content is at all interesting to you. The course is sold on a pay-what-you-want model and is copyleft, meaning other people have the right to re-publish it at will. I simply encourage anyone who appreciates the work put into this course to purchase it such that I may make more in the future, and if you do choose to republish any section, please credit me and extend to your audience my request to purchase.

* The Title-Transfer Theory of Contracts
As stated in the opening quote, property theory lies antecedent to contract theory---that is, the right to make contracts is implied by the right to own property, and not the other way around. First, recall that property rights are conflict-avoiding norms, the owner is said to be the man who can justly control the resource in question. But these ownership rights are not set in stone, the owner of a property may abandon it or transfer title to it to someone else---consider Crusoe leaving his stick to rot after he has finished spear fishing, if he no longer considers it to be a good which he is acting with, Friday is capable of possessing it without there being any conflict. In other words, owning a thing involves actually possessing it along with the intent to direct the use of it, if you lose this intent you no longer own it. This is abandonment, where a property is simply ceded back to nature, ripe for someone to homestead it---recall that such abandonment must be objective and intersubjectively ascertainable. The latter case, of a man transferring title to someone else is the subject of the theory of contracts. The question of concern is what types of contracts are enforceable and why.

#+begin_src md :exports none
---

# The Title-Transfer Theory of Contracts

---

# The Title-Transfer Theory of Contracts
 ,* Property rights are conflict-avoiding norms
 ,* The owner is the one who justly controls a given resource
 ,* The owner can abandon the property or transfer title
 ,* Abandonment must be objective and intersubjectively ascertainable
#+end_src

Allow me to first construct the basic case of Crusoe transferring ownership of his stick to Friday. For this to be a transfer and not an abandonment, Crusoe must relinquish control at the same time that Friday takes up control, and each man must have the goal of the transfer going forth---that is to say, there exists no time between Crusoe and Fridays ownership where the stick was unowned. This means that a third man, Xury, could not come along and quickly swoop in on the property and thereby homestead it. It is clear that Friday now has title to the property. In short, a transfer of title to the stick from Crusoe to Friday involves Crusoe abandoning the stick at the same time that Friday homesteads it. What makes this transfer an enforceable contract, is that if Crusoe does not physically go through with giving the stick up he has implicitly committed theft---the stick belongs to Friday now and Crusoe is using it against Fridays consent. This is because Crusoes agreement to the contract is evidence that he wishes to relinquish control--to abandon the stick--he cannot deny this without contradiction.

#+begin_src md :exports none
---

## The Basic Contract

---

## The Basic Contract
 ,* For it to be a transfer, Crusoe must relinquish control at the same time that Friday takes up control
 ,* There is no time between Crusoe and Friday's ownership where the stick is unowned
 ,* A transfer of title to the stick involves Crusoe abandoning it at the same time that Friday homesteads it
 ,* If Crusoe does not relinquish the stick he has implicitly stolen it
#+end_src

It is therefore those contracts where defaulting would imply aggression that are enforceable. Consider a mere promise, say a woman agrees to marry her boyfriend but does not go through with it---she has gone back on her word, but she has not violated the boyfriends rights, therefore mere promises like this are not enforceable. A promise is only enforceable to the extent that it implies a transfer of property titles---in such a case the property may be re-possessed by its now-owner.

This theory of contract is called the “title-transfer” theory for this reason---to sum up, only those contracts which define the terms of the transfer of title to /alienable/ property are legitimate. Furthermore, /conditional/ transfers are also legitimate, say that Crusoe agrees to transfer title to the stick to Friday on the condition that Friday performs a dance. Upon Friday meeting the condition set forth by Crusoe, title to the stick is transferred to him---this is because the intention was made clear by both Crusoe and Friday that Friday is the just director of the use of the stick upon the condition being met. It will be seen in a later lesson why Crusoe would be "estopped" from challenging Fridays ownership---that is to say, Crusoe could not coherently deny that Friday owns the stick upon the condition being met. What is important is that on this theory a contract is not a piece of paper, the piece of paper is rather evidence of a contract existing, the contract can be verbal, agreed to via semaphore, or any manner of other methods of communication---all that a piece of signed paper can do is serve as evidence that a given contract was communicated and agreed upon by the parties in question.

#+begin_src md :exports none
---

## Conditional Transfers

---

## Conditional Transfers
 ,* Crusoe agrees to transfer title to the stick to Friday on the condition that Friday performs a dance
 ,* When Friday does the dance he owns the stick
 ,* Crusoe is "estopped"
 ,* A contract is not a piece of paper, the piece of paper is *evidence of* the contract
#+end_src

An interesting implication of this theory is that there isn’t really such a thing as “breaching” or “breaking” a contract. If $A$ and $B$ agree that $B$ will transfer to $A$ a sum of 10 ounces of silver on the condition that $A$ performs magic at $B$’s birthday party, $A$ has not violated $B$’s rights by not showing up, if $B$ wanted to encourage $A$ to go through with the deal he simply need bake in a penalty clause stating that $A$ transfers to $B$ a sum of 5 ounces of silver if he does not perform the magic. Still here, $A$ does not “breach” the contract by not showing up, he has simply engaged in an action which the contract covers. The aggression would only be if doesn’t perform and doesn’t hand over the 5 ounces, not because this would breach the terms of the contract, but because this would be a theft of 5 ounces of silver.

#+begin_src md :exports none
---

## Contracts Are Never Broken

---

## Contracts Are Never Broken
 ,* If $A$ and $B$ agree that $B$ will transfer to $A$ a sum of 10 ounces of silver on the condition that $A$ performs magic at $B$’s birthday party, $A$ has not violated $B$’s rights by not showing up
 ,* The only possible aggression with respect to contracts is theft of property retained
#+end_src

Consider further the case of Smith agreeing to pay 50 lbs of gold for Jones' car, Smith takes the car but refuses to hand over the 50 lbs of gold to Jones, has Smith stolen the car or the 50 lbs of gold? Well, if Smith actually has 50 lbs of gold then title to it was instantly transferred to Jones upon the contract being accepted, thus it is the gold that has been stolen. On the other hand if Smith does not have 50 lbs of gold then the condition for the transfer of the car has not been met, so Jones still owns the car and that is what Smith has stolen.

#+begin_src md :exports none
---

## A Final Example
 ,* Smith agrees to pay 50 lbs of gold for Jones' car
 ,* Smith takes the car but refuses to hand over the 50 lbs of gold
 ,* What has Smith stolen?
 ,* If Smith has 50 lbs he has stolen it
 ,* If Smith lacks 50 lbs he has stolen the car
#+end_src

* Fraud
Fraud can be defined as theft-by-trick, i.e. it is a theft performed by deceiving the victim. Consider the example where Crusoe has blunted the tip of his spear and that's why he wants to get rid of it, Crusoe lies to Friday and claims that the spear is as sharp as a razor, this is fraud---Crusoe has deceived Friday about the nature of the spear. This means that this was not a valid contract, Crusoe did not have the intention of transferring title to a sharp spear to Friday and therefore the contract is null. If Friday had given Crusoe some sea-shells in exchange, Crusoe has implicitly stolen those shells.

#+begin_src md :exports none
---

# Fraud
#+end_src

A particularly prevalent example of fraud is found in fractional reserve banking;[fn:2] the fractional reserve bank keeps only some fraction of the money deposited and loans out the rest. Consider a full reserve bank; various people come and deposit 100 ounces of gold, and the bank therefore gives these depositors in total certificates for 100 ounces of gold. Here there is a one-to-one correspondence between titles to the gold--evidenced by the certificates--and actual gold in the vault. Consider what would happen if this bank decided to implement an 80% reserve policy, and they therefore loan out 20 ounces of gold, this would mean that the bank has stolen that gold, because there was already a one-to-one correspondence between property titles in the gold held by depositors and actual gold in the vault---therefore the bank is committing fraud in deceiving people into the belief that they actually hold title to that gold. Perhaps instead of physically loaning out the gold they keep all the gold they have, but they give out 20 ounces worth of certificates for gold; this would also be fraud because there would be 120 ounces worth of titles to gold, but only 100 ounces of gold---more property titles than actual property implies that people are being deceived about the actual nature of the property in existence, which therefore means there must be fraud.

#+begin_src md :exports none
---

# FRB as Fraud

---

# FRB as Fraud
 ,* The FRB keeps only some fraction of the money
 ,* Under full reserve there is a one-to-one correspondence between money certificates and money
 ,* Under fractional reserve there are more certificates than actual money
 ,* More property titles than actual property implies fraud
#+end_src

Often, so-called “free-banking” supporters will hold that the right of people to make whatever contracts they expect to be advantageous means that such fractional reserve banks are not criminal institutions, but as we have seen these people are misunderstanding the nature of property and contracts. It is not the case that one is able to make whatever contract they want so long as everyone agrees to it, property theory lies antecedent to contract theory, therefore a contract which misrepresents the actual nature of property in existence is invalid. This is not to say that a fractional-reserve casino game is fraudulent, but representing this casino game as a bank is. A bank is a money-warehouse, not a casino game. Such a casino game would not involve people depositing /their/ money in /their/ account and retaining title as evidenced by money substitutes, such a game would involve people transferring their money /to the casino/ in order for the casino to engage in some gambling algorithm with it. So fractional reserve /banking/ is fraud, fractional reserve roulette is not---the definition of fraud in terms of deception is another concept that highlights the importance of communication to libertarian theory. Just as me loaning my friend 5 ounces of silver is not me depositing my money in an account held by my friend, it is me transferring that silver to him, so too is me placing a bet with a casino not me depositing money in an account, it is me transferring that bet to them.

#+begin_src md :exports none
---

# Against Free Bankers

---

# Against Free Bankers
 ,* Property theory lies antecedent to contract theory
 ,* A fractional reserve casino game is fine, a fractional reserve *bank* is not
#+end_src

* Debtors Prison
This concept of a loan is relevant to the question of debtors prison. The question is twofold; first if $A$ loans $B$ 1000 ounces of silver in exchange for 1050 ounces in one years time but $B$ defaults has he stolen from $A$, and second would $A$ be permitted to put $B$ to work in a debtors prison to pay off this stolen sum? For the former question, if it is the case that $B$ has stolen from $A$, /what/ has he stolen---the 1000 ounces or the 1050 ounces? He surely hasn't stolen the 1000 ounces because that money was transferred to him at the time of the contract such that he could invest it in his various projects, if it was not transferred there would be no loan in the first place. It also cannot be the case that it wasn't theft at the time but it is retroactively at the time when he defaults---a property theory must assign a definite owner to any scarce resource at all times, if retroactive theft is such a thing in your property theory there exists Schrödinger's property who's owner cannot be determined right here and now such that conflicts over its use may be avoided. Schrödinger's property must therefore be expelled from our rational theory and as such the notion of retroactive theft must also. The question here is who owns the 1000 ounces immediately after the contract is accepted, $A$ or $B$? If $A$ then $B$ has no right to invest these funds and there is no contract to speak of. If $B$ then it cannot be that $B$ has stolen the 1000 ounces because he had title to it.

#+begin_src md :exports none
---

# Debtors Prison

---

# Debtors Prison
 ,* If $A$ loans $B$ 1000oz silver in exchange for 1050oz in one years time but $B$ defaults has he stolen from $A$?
 ,* Would $A$ be permitted to put $B$ to work in a debtors prison to pay off this stolen sum?
 ,* If $B$ has stolen, *what* has he stolen? 1000oz or 1050oz?
 ,* Can't be 1000oz, as that was transferred to him
 ,* Can't be 1050oz either, because it doesn't exist
#+end_src

Furthermore, it also can't be said that $B$ has stolen the 1050 ounces, for if $B$ has defaulted that means he does not possess 1050 ounces of silver so how could he possibly have stolen it if it doesn't exist? Of course, if $B$ actually does possess said sum and simply refuses to hand it over, this is not strictly speaking a default on the loan, it is rather $B$ stealing that sum of money. These future-oriented contracts are called aleatory contracts, they have an implied clause of "unless its impossible," this is because the future is uncertain---just as you cannot contract to transfer title to a square circle, you cannot contract to transfer money that doesn't exist, so in such loan arrangements there must be an implicit condition that the funds actually exist on the due date. After all, what if $B$ was vapourised in a nuclear explosion along with the funds one week after the contract was accepted. Upon the money coming due has the now-dead $B$ robbed $A$ from beyond the grave? What if everyone except $A$ died in the explosion---if nobody else exists it is nonsensical to speak of anyone being criminal towards $A$.

In short its not theft unless something was stolen, and its not fraud unless there was deception---there is no deception in the case of an aleatory contract on the part of $B$ as he is not deceiving $A$ into thinking that he has what he does not. Everyone knows that the future is uncertain, $B$ has made no claims to the contrary.

Whilst it is not relevant to legal theory as such how $A$ can successfully get around this hurdle I think it is important to give some notion as to how future-oriented contracts are still possible and reasonable. First, $A$ need only bake in some interest clause, perhaps each month that passes $B$ owes $A$ a further 1% on top of the initial 1050 ounces such that when $B$ acquires the requisite sum of money title to it is immediately transferred to $A$. Furthermore, it is not the job of law to make sure that $A$ makes a profit on the loan, some loans go bad, it is an entrepreneurial activity and as such it is per se uncertain. The fact that the loan goes bad and $A$ doesn't make a return is not sufficient grounds to justify $A$ locking $B$ up in a prison and working him as a slave.

#+begin_src md :exports none
---

## How to Make Aleatory Contracts

---

## How to Make Aleatory Contracts
 ,* $A$ can bake in an interest clause
 ,* It is not the role of law to make sure $A$ makes a profit, some loans go bad
#+end_src

* Voluntary Slavery
With our solid understanding of contract theory, we can analyse the debate surrounding “voluntary slavery” and determine the correct answer. The debate essentially centres around whether a mans self-ownership is alienable or not, that is to say, the question is whether it is legitimate to transfer ownership of oneself to another person. the former view is most notably held by Walter Block, and it can be summed up as follows:[fn:3]

#+begin_src md :exports none
---

# Voluntary Slavery
#+end_src
#+begin_quote
The underlying point of the libertarian critique is that if I own something, I can sell it (and should be allowed by law to do so). If I can’t sell it, then, and to that extent, I really don’t own it. Take my own liberty as perhaps the paradigm case of the debate over inalienability. The claim is that if I really own my liberty, then I should be free to dispose of it as I please, even if, by so doing, I end up no longer owning it. Clearly, since I cannot own a square circle, I cannot sell it. If I can own my own ability to give true love, then I can sell it; if I logically cannot own this attribute, then, of course, I cannot give, barter, or sell it to anyone else.

My thesis: No law should be enacted prohibiting or even limiting in any way people’s rights to alienate those things they own. This is “full monte” alienability, or commodification.
#+end_quote

#+begin_src md :exports none
---

<!-- _footer: Walter Block, *Toward a Libertarian Theory of Inalienability: A Critique of Rothbard, Barnett, Smith, Kinsella, Gordon, and Epstein*. -->

> The underlying point of the libertarian critique is that if I own something, I can sell it (and should be allowed by law to do so). If I can’t sell it, then, and to that extent, I really don’t own it. Take my own liberty as perhaps the paradigm case of the debate over inalienability.

---

<!-- _footer: Walter Block, *Toward a Libertarian Theory of Inalienability: A Critique of Rothbard, Barnett, Smith, Kinsella, Gordon, and Epstein*. -->

> The claim is that if I really own my liberty, then I should be free to dispose of it as I please, even if, by so doing, I end up no longer owning it. Clearly, since I cannot own a square circle, I cannot sell it. If I can own my own ability to give true love, then I can sell it; if I logically cannot own this attribute, then, of course, I cannot give, barter, or sell it to anyone else.

---

<!-- _footer: Walter Block, *Toward a Libertarian Theory of Inalienability: A Critique of Rothbard, Barnett, Smith, Kinsella, Gordon, and Epstein*. -->

> My thesis: No law should be enacted prohibiting or even limiting in any way people’s rights to alienate those things they own. This is “full monte” alienability, or commodification.
#+end_src

So, for a voluntary slavery contract to be legitimate, (1) you must own yourself in the first place and (2) you must be able to sell yourself. Walters contention with other libertarians is that there does not exist objects which are ownable but not sellable---the standard example of a contract pertaining to the sale of a square circle is illegitimate because you can't own a square circle in the first place. This would imply that because people own themselves in the first place, they can therefore sell themselves.

#+begin_src md :exports none
---

## Prerequisites for Voluntary Slavery

---

## Prerequisites for Voluntary Slavery
 ,* You must be able to own yourself
 ,* You must be able to sell yourself
 ,* Block contends that nothing is ownable that is not also sellable
#+end_src

A prominent counter-argument to this thesis was forwarded by Rothbard in his /Ethics of Liberty/:[fn:4]
#+begin_quote
The distinction between a man’s alienable labor service and his inalienable will may be further explained; a man can alienate his labor service, but he cannot sell the capitalized future value of that service. In short, he cannot, in nature, sell himself into slavery and have this sale enforced—for this would mean that his future will over his own person was being surrendered in advance. In short, a man can naturally expend his labor currently for someone else’s benefit, but he cannot transfer himself, even if he wished, into another man’s permanent capital good. For he cannot rid himself of his own will, which may change in future years and repudiate the current arrangement. The concept of “voluntary slavery” is indeed a contradictory one, for so long as a laborer remains totally subservient to his master’s will voluntarily, he is not yet a slave since his submission is voluntary; whereas, if he later changed his mind and the master enforced his slavery by violence, the slavery would not then be voluntary.
#+end_quote

#+begin_src md :exports none
---

<!-- _footer: Murray Rothbard, *The Ethics of Liberty* -->

> The distinction between a man’s alienable labor service and his inalienable will may be further explained; a man can alienate his labor service, but he cannot sell the capitalized future value of that service. In short, he cannot, in nature, sell himself into slavery and have this sale enforced—for this would mean that his future will over his own person was being surrendered in advance.

---

<!-- _footer: Murray Rothbard, *The Ethics of Liberty* -->

> In short, a man can naturally expend his labor currently for someone else’s benefit, but he cannot transfer himself, even if he wished, into another man’s permanent capital good. For he cannot rid himself of his own will, which may change in future years and repudiate the current arrangement.

---

<!-- _footer: Murray Rothbard, *The Ethics of Liberty* -->

> The concept of “voluntary slavery” is indeed a contradictory one, for so long as a laborer remains totally subservient to his master’s will voluntarily, he is not yet a slave since his submission is voluntary; whereas, if he later changed his mind and the master enforced his slavery by violence, the slavery would not then be voluntary.
#+end_src

There are several ways a Blockean might respond to this attack, first they could point to the frontal lobotomy as a procedure which makes a person akin to an animal in terms of thinking. Perhaps there could be a pill or machine invented in the future which would nullify only those parts of a mans brain which are responsible for his conceptual abilities---surely a man who underwent a procedure such as these would have indeed--potentially permanently--subdued his will such that he may be more effectively directed by his enslaver. This would mean that voluntary slavery is not per se illegitimate, but rather is only illegitimate where men cannot figure out how to subdue the slaves will. Furthermore, it is not the will which is relevant to a voluntary slavery contract but the body, so even if it is logically impossible to transfer the will of person $A$ to person $B$, it may /not/ be the case that its impossible to transfer the body from $A$ to $B$. After all, both the supporters and rejectors of the right to make slave contracts agree that it is possible to have someone as your slave---that is to say its possible for $B$ to possess $A$, the question is whether it's possible for this to be a /just/ possession.

#+begin_src md :exports none
---

## The Blockean Response

---

## The Blockean Response
 ,* The frontal lobotomy as will-surrender
 ,* Voluntary slavery is a mere technological limitation, not a legal one
 ,* Will isn't relevant, its possible to have slaves
#+end_src

And on this note, let us recall the nature of a mans self-ownership. A body is necessarily and objectively linked to an acting man, and it is this link which imbues a man with ownership. Any time you argue with anyone you must assume the primacy of this link and its validity in making the other person own their body. It is the argument from argument, then, which demonstrates the inalienability of the self. That is to say, ownership is just control, which means /argumentatively justifiable/ control, and the very nature of argumentatively justifying anything implies a mutual recognition of self-ownership, therefore a master cannot justly possess his slave making voluntary slavery a contradiction in terms. Block rejects this notion of an objective-link establishing ownership, stating the following:[fn:5]

#+begin_src md :exports none
---

## The Blockean Mistake

---

## The Blockean Mistake
 ,* A human body is necessarily and objectively linked to an acting man
 ,* The nature of argumentation implies a mutual recognition of self-ownership
#+end_src
#+begin_quote
Let us posit you have a dog who is heart and soul with you. K9 dogs are said to have this sort of connection with their masters. According to Kinsella, not only would it be illegal to sell this dog [...] but, also, well-nigh logically impossible for this to occur. Just as we all “have the best link to my body”, you, too, have the best link to this dog. You snap your fingers, and the dog does your bidding, not that of the neighbor, to whom you have sold the dog. The point is, “the best link to, in terms of control,” is clearly way outside the bounds of libertarian homesteading and property rights theory. Merely because someone has “the best link” to something, does not mean he is necessarily the legitimate owner of it [...]
#+end_quote

#+begin_src md :exports none
---

<!-- _footer: Walter Block, *Rejoinder to Kinsella on Ownership* -->

> Let us posit you have a dog who is heart and soul with you. K9 dogs are said to have this sort of connection with their masters. According to Kinsella, not only would it be illegal to sell this dog [...] but, also, well-nigh logically impossible for this to occur. Just as we all “have the best link to my body”, you, too, have the best link to this dog.

---

<!-- _footer: Walter Block, *Rejoinder to Kinsella on Ownership* -->

> You snap your fingers, and the dog does your bidding, not that of the neighbor, to whom you have sold the dog. The point is, “the best link to, in terms of control,” is clearly way outside the bounds of libertarian homesteading and property rights theory. Merely because someone has “the best link” to something, does not mean he is necessarily the legitimate owner of it [...]
#+end_src

But the dog is clearly disanalogous to the human case---a dog is an external object, not a (human) body. What we have in the case of a dog that $A$ wants to sell to $B$ is a case of either $A$ or $B$ "coercing" the dog to do their bidding. The dog is analogous to a machine-gun that $A$ may well be more adept at using---the point is not over who is more scientifically capable of using the object for some end though. If the dog was capable of acting and arguing then indeed it would be a contradiction to assert that either $A$ or $B$ could own the dog, as they would have to recognise the dogs self-ownership. This is because the dog would then have an objective and undeniable link to his own dog-body. The dog has no such link in reality because he cannot act or argue---the dog is in the same legal category as a machine-gun. It may well be the case that $A$ is more capable of using the dog for certain ends, but this is not enough to demonstrate a link as strong as is between an actor-arguer and his own body.

#+begin_src md :exports none
---

## Block's Failure
 ,* Disanalogy!
 ,* The dog is an external object, not a (human) body
 ,* $A$ wants to sell a dog to $B$ is a case of either $A$ or $B$ "coercing" the dog to do their bidding
 ,* Selling requires abandonment
#+end_src

Moreover, a first-principles understanding of contract highlights the fact that for $A$ to transfer title of $\alpha$ to $B$, $A$ must relinquish control--i.e. abandon $\alpha$--at the same time that $B$ takes up control. You cannot abandon your body without making yourself braindead, so you cannot--whilst remaining an actor--transfer title to your body. After all, such abandonment of the property would have to be objective and intersubjectively ascertainable, merely decreeing that you no longer own yourself is not enough. What this means is that voluntary slavery is an impossibility, insofar as you do make yourself braindead and thus non-existent in the praxeologic sense you cannot be said to consent or not consent to anything. It is not proper to say that the stick I appropriate from nature is consenting or not consenting to be my slave---it is a stick, not a moral being capable of consent. Therefore, the closest one can get to voluntary slavery is to render the so-called "slave" incapable of action or argumentation, to completely destroy their will in Rothbardian terms, and thus make this person legally analogous to a corpse.

Rothbard therefore already had the shape of this idea in his mind, but spoke of it using the confusing terminology of will-transfer, as Block says, "will schmill!"[fn:6] Whether you can literally transfer or suppress the will of an acting being isn't relevant, what is relevant however, and what Rothbard was on the cusp of, is that consent does matter. Merely promising in the present that you will do whatever your master says, that you will be their slave, does not mean that they own you---mere promises do not establish this, you can always change your mind in future and revoke consent. Consider the case of your girlfriend agreeing to have sex with you tomorrow after dinner, the time comes and you are getting ready to do the deed but she changes her mind and tells you that she no longer wants to go forward with the arrangement. But is she not my slave for the purposes of this contract? She agreed before that she would obey my wishes on this matter, so am I permitted to have sex with her or would this be rape? Clearly the latter is true---just because she gave consent before does not imply that she cannot revoke said consent. The same is true for all voluntary slavery, merely agreeing now to always obey the masters wishes does not transfer ownership of anything. The Rothbardian analysis is also absolutely correct in that demolition of the will would allow a body to be owned by another, but only because this demolition of will would render the individual analogous to a corpse.

#+begin_src md :exports none
---

## Rothbard Vindicated

---

## Rothbard Vindicated
 ,* Whether you can literally transfer the will isn't directly relevant
 ,* Consent in the present does not imply consent in the future
 ,* Destroying the will would allow for body-transfer if it renders one braindead
#+end_src

It is therefore not all that surprising that one cannot sell their body (whilst remaining alive), after all as discussed earlier, the two methods of alienation are title-transfer and abandonment, we already accept that its not possible for an actor to abandon their body, what the above analysis shows is that it's also not possible to alienate your body through title-transfer either. Moreover, as discussed above, for title-transfer to be possible in the first place you have to be able to abandon the thing in question. If $A$ wants to transfer title of $\alpha$ to $B$, what $A$ must do is abandon title to $\alpha$ at the same time that $B$ takes up title to $\alpha$, this first step of abandonment cannot occur in bodies, and therefore ownership of bodies cannot be transferred. The only exception is when the person in question dies or is rendered braindead, at this point their body is indeed abandoned to nature and as such the only valid way to transfer title to your own body is by doing so in a last will and testament.

It is a mistake to see property in external objects as being equivalent to property in bodies and then using the fact that you can trade external objects to claim that you can also trade bodies---ownership is the right to control a scarce resource, it takes an additional step to say that you can give up that right or that other people could take it. The confusion on this matter is derived from a conflation between two different senses of the word "ownership." In this course great attention has been paid to the legal sense of this word, but there is also such a thing as catallactic ownership, which is the sense used by economists. This is why an economist may say something like, "$A$ sells his labour services for 5 ounces of gold to $B$," to the legal theorist such a sentence is incoherent, the labour isn't owned by anyone and thus it isn't being traded---it doesn't make sense to say that someone owns their labour, labour is something that you do with things that you own. After all, what would it mean to exclude someone from your labour? Thus in the legal sense this is clearly ludicrous, but the economist does not mean the same thing, what the economist means by ownership is more akin to possession, or control, as the economist is not concerned with whether said control or possession is just. $A$ certainly does control his labour, at least in the economic sense, he can choose to employ his labour for whatever line of production he sees fit, and in the economic sense it makes sense to speak of him trading this labour with other people, but one should not then bring such an analysis into legal matters, such would be a dreadful mistake. The voluntary slavery contract is the paramount example of this mistake, Blocks argument hinges on the notion that if you own something you can sell it and vice versa. But it is simply not the case that ownership implies selling or that selling implies ownership. I can sell a bitcoin, or an idea, or my labour, and yet I do not /own/ any of these things in the legal sense. Similarly owning something does not imply the right to sell it, as has been seen with the case of ones body.

#+begin_src md :exports none
---

## Ownership $\centernot\longrightarrow$ The Right to Sell

---

## Ownership $\centernot\longrightarrow$ The Right to Sell
 ,* Ownership is the right to control a scarce resource, it takes an additional step to say that you can give up that right
 ,* Conflation between legal and catallactic ownership
 ,* I can sell a bitcoin, or idea, or labour without owning these things
#+end_src

* The Last Will and Testament as a Contract
It is possible to alienate some parts or even all of your body though---consider Crusoe chopping off his arm. Upon chopping the arm off it is alienable, Crusoe is able to abandon or trade it at will, because he is no longer objectively and undeniably linked to his arm. A similar case exists with respect to ones entire body in the case of death. If Crusoe sets to paper that upon the condition that he dies, ownership of his body is transferred to Friday, then this is a legitimate contract. The instant the condition is met Crusoes body becomes alienable just as surely as a stick or a sea-shell. There could be no remaining objective link between Crusoe and his body at this point because Crusoe has perished---he no longer possesses the potential to engage in any form of argumentation, and as such third parties are not in contradiction by claiming to own him. This highlights why a last will and testament is a legitimate contract in general---simply set the condition for whatever title-transfers the will defines to be the death of the owner. Should a man die who has no inheritors his property--including his body--becomes instantly ceded to nature, ready for someone to homestead it. Therefore if a man wishes his corpse be treated in a certain way he must transfer title to it to trusted family or a funeral home.

#+begin_src md :exports none
---

# The Last Will and Testament as a Contract
#+end_src

* Related Reading
+ Łukasz Dominiak and Tate Fegley, /Contract Theory, Title Transfer, and Libertarianism/
+ N. Stephan Kinsella, /A Libertarian Theory of Contract: Title Transfer, Binding Promises, Inalienability/

#+begin_src md :exports none
---

# Related Reading
+ Łukasz Dominiak and Tate Fegley, *Contract Theory, Title Transfer, and Libertarianism*
+ N. Stephan Kinsella, *A Libertarian Theory of Contract: Title Transfer, Binding Promises, Inalienability*
#+end_src

* Footnotes

[fn:1]Murray Rothbard, “Property Rights and the Theory of Contracts,” p. 133, in idem. /The Ethics of Liberty/.

[fn:2]On this, see Hans-Hermann Hoppe, Jörg Guido Hülsmann, Walter Block, /Against Fiduciary Media/; see also MRH Legacy, /From Barter To Bitcoin: A Theory of Money/, https://www.youtube.com/watch?v=RZdJdfXL6K4

[fn:3]Walter Block (2014), /Toward a Libertarian Theory of Inalienability: A Critique of Rothbard, Barnett, Smith, Kinsella, Gordon, and Epstein/.

[fn:4]Murray Rothbard, “Interpersonal Relations: Voluntary Exchange,” pp. 40-41, in idem. /The Ethics of Liberty/.

[fn:5]Walter Block, "Rejoinder to Kinsella on Ownership", /MEST Journal/ Vol. 11 No.1, pp. 1-8

[fn:6]ibid.
