#+TITLE: Why "Opt-Out" Organ Donation is Theft
#+AUTHOR: LiquidZulu
#+EMAIL: liquidzulu@pm.me

* Introduction
Hello, I am currently working on a /massive/ video on the topic of Libertarian Environmentalism which I hope will come out some time in March, in the meantime I am going to do a quickie on the topic of opt-out organ donation and why I think it's theft. This was prompted by a letter I received from NHS Scotland informing me of a change to this system; so strap in and enjoy.

* The Argument
Every man, woman, and child own themselves and all the organs in their body --- it is abhorrent to suggest that you may assume someones consent to make use of their property towards any end you may desire. To assume consent in the case of organ donation is logically equivalent to assuming a persons consent in sex. To say that you may implement an opt out for giving your organs to a person is to say that you may implement an opt out for people consenting to have sex with you.

* Counterarguments
** People will die without those organs
This is similar to Vaush's famous coconut analogy against voluntaryism --- 2 people, A and B, are on an island, one night A collects all of the coconuts and tells B he must work for him if he wants to eat. The idea being that A should be obliged to give B coconuts and to not do this is coercive. But if we imagine a separate but also logically similar analogy we can see the flaw of this thinking --- imagine that a person C has a disease where they will die if a woman does not have sex with them and no woman wants to. If Vaush is correct that A may be compelled to give B his coconuts then it must also be correct that C may oblige any woman he meets to have intersourse with him. The structure is identical after all; "Feed me or I die" vs "Fuck me or I die", in both cases someone advocating a free society whould be against the non-consenting action.

The hypothetical can be further generalised as Person 1 may compel Person 2 to perform an action if the performing of this action would stop something that 1 does not want to happen. This obviously cannot be applied universally or else 2 may simply compel 1 to not compel 2 as this would be something 2 does not want --- we may continue this ad infinitum, forever, never resolving to whether the action should happen or not. Only in thinking some deserve more rights than others may you resolve this conundrum.

** It doesn't affect you, unlike rape, as you will be dead
One may protest that my prior argument that it is the same as rape doesnt hold as your organs are taken post mortem, so you are unaffected, whereas rape happens very much pre mortem. Ok, lets try to adjust our scenario to take this into account; it doesnt affect you to have a necrophile engage in intercourse with your corpse after your death, and if we make them pay money to charity for this then we can even help save the whales or african children or whatever charity you like. In fact we should engage in an opt out system where a person must opt out from this great necrophile program --- to draw your attention to how bad this is imagine how many children might have the wherewithall to opt out, heck we could probably charge extra to the paedophile necrophile market, and it keeps them from raping any alive toddlers. God bless our NHS --- our Necrophile Helping Service.

Moreover, to suggest that a dead persons consent does not matter is to abandon the entire institution of wills --- to say that the instant a man dies his neighbors may walk in and take his house, as it would instantly revert to nature sans a last will and testement.

** Well where else will we get all the organs from?
Good question, markets. We simply allow people to sell their organs and you will instantly see a boost in supply --- the reason few donate is that there is little they get from it, if I could get a few hundred thousand from my corpse to leave to my family I sure as hell would allow everything to be taken, I think most would. Organ donation is a classic distribution problem, some have a massive oversupply of organs, namely the dead, and some have a massive under supply. If we are to stop this amazing opportunity to acquire new organs /with/ full consent for puritan reasons that some feel it bad to sell ones organs is it better than the peoples organs are simply taken without payment? how does that address ones concern over an organ trade?
