#+title: Min Wage

* Main Body
The minimum wage is an apocalyptic policy. Consider John who is paid $3/hour to sweep floors and clean toilets. His boss would like to pay him less, ideally nothing, but he cannot do this, because John's boss is in competition with other capitalists who have bid up John's wage to $3/hour, which sets a lower limit on how much John can be paid.

There is also an upper limit, set by how much extra revenue a capitalist can make by hiring John, perhaps John produces only $4/hour for a capitalist, thus the capitalist would not be willing to pay any more than this. Therefore if a minimum wage of $9/hour is set, John will not be able to find a job, thus encouraging capitalists who would like to hire John to automate or ship his job overseas. After all, if a minimum wage of say $15/hour was good why not $80, or $1 million, or set the minimum wage to be the entire quantity of gold ever mined by humanity. After all, pieces of paper cannot make humanity richer, so if a minimum wage works it must work on a gold standard.

What this all means is that a minimum wage implies that capital will be shifted away from that optimal arrangement that the market tends towards and raises time preferences in the process, which means that saving is reduced. Therefore a minimum wage is destructive of current capital and a hampering force against the development of future capital, which means that... [The minimum wage is an apocalyptic policy.]
