#+title: Parody Presidential Announcement

Hello, the least principled motherfucker you know here. I am announcing my candidacy for president on behalf of the Libertarian Party. I love democracy and want your voice to be heard, or maybe I am a paleo and think that Disney should be taxed into bankruptcy. Either way, I am speaking the libertarian message. We libertarians want there to be less government control, unless that government control gives us what we want. I am going to spout some generic populist talking points now. Gun control, freedom, America, school choice, woke corporations.

What are my principles? America. And thats why you should vote for me---I am different from the Democrats and Republicans, because there is an L next to my name.

I pledge to increase the ICE budget, so that we can track down and get rid of those greedy immigrants, because Hoppe said something about immigration at some point, and I zoned out whilst reading it but thats the gist of it anyway.

Libertarians are not opposed to the largest institution of aggression ever to exist, you see: the state is a necessary evil. I pledge to expand the necessity of this evil and to show those silly anarchists that state central planning can work, just so long as we pull ourselves up by the bootsraps, and put in the hard work---we can do this America!

I'm not a politician, I'm just your everyday dude! I go to the gym, I have a family, I don't like things that are bad, and I like things that are good!

+ "It is time for us grifters to stand up, and fight the profitable fight! Did you know that 73% of the top 1000 libertarian accounts on twitter, are grifters just like you and me? If we band together, we can take our message straight to Washington, where I'm sure we will be treated to delicious luncheons by the uniparty."

[This message is approved by the grifter for president committee, principles not guaranteed, send me money, send me money please]
