#+TITLE: Why is Taxation Theft? #Shorts

* What is theft
Theft, as defined by the legal dictionary, is /A criminal act in which property belonging to another is taken without that person's consent/.[0]

* Applied to taxation
Taxation fits this definition to a T, if you choose to not give over your taxes then you are kidnapped and forced to pay even more, this is not consent.

* Social contract
Already you may have a counterpoint; that it isnt aggressive kidnapping when the state arrests non-taxpayers because they agree to abide the social contract by living in the country.

This begs the question of whether the state owns the land rightfully though. If the state simply claimed to own the land without ever building anything there or purchasing it off someone who has then I may claim to own the moon and tax anyone who steps foot on its surface.

* Taxes provide services
>but taxes provide public services that help people
ok, lets accept that taxes do provide services, could people not simply pay for these services willingly rather than being forced? Can the state spend your money better than you can? And in any case this doesnt make it not theft per our definition; if I rob you and give that money to a homeless man I have still robbed you.

* Sign off
Thank you for watching and dont forget to like and subscribe, if you have any arguments make them in the comments and ill respond. A more in depth video by bitbutter on this topic can be found in the description.

* bib
[0] https://legal-dictionary.thefreedictionary.com/theft
