#+TITLE: Georgism

* Notes
** BritMonkey https://www.youtube.com/watch?v=Li_MGFRNqOE
+ "nobody should have to pay for air because nobody invented air... so why cant the same be said for land?"
  + "yadda yadda owning land is like owning a patch of air"
+ "surely because nobody invented land it should belong equally to all members of society, like air"
+ "if you want to wall off your land and live on it you should expect the rest of society to respect that therefore you should pay a tax on the value of the land to pay for that protection from society. Because other people now dont have access to the land, they should be compensated for it"
** Primo Radical https://www.youtube.com/watch?v=VJzY--edzqM
+ what gives a person a right to draw a line around a piece of property and claim ownership?
** GeoAnarchism https://old.reddit.com/r/Geoanarchism/comments/m8gfci/what_is_geoanarchism/
+ Start by considering where rights come from and who or what possesses them
  1. all individuals have rights
  2. only individuals have rights
  3. These rights are identical
     + [Not sure what this means, different men certainly have different property rights]
+ "On one hand, propertarian anarchists will contend that self-ownership necessarily implies private property."
  + thats what "ownership" means.
+ "some degree of control over land is implied by human rights given that land always houses the labor produces by individuals. The labor itself, the transformation of land, is rightfully the exclusive property of the individual that created it because it is an 'an emanation from his being'."
  + relies on a faulty labour theory of property
* Main Body
** Introduction
Georgism is an ideology that advocates a tax on the unimproved value of all land, land in this context meaning any natural resource. The Georgist justifications for this tax range from commie reeing over the big mean landlords, to the assertion that land is jointly owned by every man, making homesteading a form of aggression. Here I shall be primarily attacking the latter stance as it is the only reasonable formulation of the Georgist ethic.

** What are Property Rights?
First and foremost it must be discussed what exactly it means to have a property right over a given item. Now, many see property rights as some sort of spook, or something only those nasty right wingers care about, but in reality, whenever one proposes any ethic pertaining to law (i.e. any ethic pertaining to the just way to deal with conflicts) that ethic implies a certain theory of property rights and a corressponding system of property rights assignments. In general in a given conflict, conflict here meaning when multiple people are trying to implement the same scarce means towards contradictory ends, the property right is assigned to the party who under the specific legal theory is denoted as the just victor to the conflict. i.e. if legal theory X assigned that in a conflict between A and B over \alpha, A has the property right, then under that legal theory B would be the criminal and A the victim.

Rothbardian Natural Law Theory assignes property rights based upon the ethic of the non-aggression principle, aggression being defined as the initiation of conflict. Essentially this can be framed as saying that the purpose of property rights under Rothbardian NLT is to avoid conflicts. So in any given conflict, to determine who has the property right and therefore which party is acting criminally, one need only determine who has initiated the conflict. I wont go into immense detail on how exactly to do that in this video as it is not particularly relevant, but I do have plans to make a full course on libertarian ethics that will go in-depth on the topic, so if you are visiting from the future be sure to check the description and if the course is done it will be the first link.

I will however give an example as a demonstration of this; say Crusoe and Friday are on a desert island together. One day Crusoe happens upon a stick poking out of a tree, and he appropriates this stick from nature, fashioning it into a spear which he plans to use for spear-fishing. On his way to the ocean, however, Friday sees the same stick and wants to use it to instead stoke his fire. Now, Crusoe cannot use the stick to spearfish at the same time that Friday stokes his fire, so if Friday were to attempt to use the stick in his preferred way we would have a conflict---two men (Crusoe and Friday) are attempting to use the same scarce means (the stick), towards two contradictory ends (fishing and the stoking of a fire). Here one need only consider the causal chain to see that it is Friday who has initiated the conflict, making Friday the criminal.

Kinsella notes[fn:1] that it is only the Rothbardian theory of property rights that makes any sense, as it is pre-supposed by any who would engage in a dispute over a property claim, no matter what property theory they claim to personally hold:
#+begin_quote
But what is implied in the idea that the right to possess—ownership, that is—is distinct from mere possession? It means that if there is any ownership at all—and those who quarrel over things are all asserting different ownership claims and thus presupposing ownership and its distinction from possession—then /it does not accrue merely to those who take things from others/. That is, if B takes a thing by force from A, this cannot in and of itself make B the owner. Why? Because if it did, it means that C could take it from B, and thereby become owner. But this just means there is no such thing as ownership; there is only possession. "Might makes right," so to speak. But this contradicts the presumption that ownership and possession are different. From this very simple idea, we see that the entire Lockean idea of first-use, first-own, follows. Why? Because if taking some good by force from its previous [possessor] is not sufficient to ground an ownership claim, then by Misesian-style "regression" it becomes obvious that only the first possessor/user can have an ownership claim. Every other person takes it from a previous possessor, and is thus a /mere possessor/—not an owner. The first possessor—the person who plucks the resource from its unowned state out of the commons—is the only possessor who does not take it from someone else; /this/ is why /first/ possession imbues the homesteader with the unique status of ownership.

I.e., the first user and possessor of a good is either its owner or he is not. If he is not, then who is? The person who takes it from him by force? If forcefully taking possession from a prior owner entitles the new possessor to the thing, then /there is no such thing as ownership/, but only mere possession. But such a rule — that a later user may acquire something by taking it from the previous owner — does not avoid conflicts, it rather authorizes them.
#+end_quote

** Problems With Georgist Property Theory
I will now take a more in-depth look at the specific problems with the Georgist property theory, that claims it to be a criminal action to take from the commons. To make this claim is to imply that there must already be a property right over nature-given goods, as no other could legally object to a person taking something except the owner of that thing.

But who exactly is this property right afforded to? Either we decide that the property right is assigned to some arbitrary individual who has nothing to do with the good in question, or we take some non-unitary supset of all other individuals and suppose that they equally co-own the good in question.

The first obviously falls on the grounds of being an arbitrary ethic--and therefore not one based upon conflict-avoidance--and the second has two problems; first, it falls on the grounds of all group ownership in that it cannot possibly solve conflicts between people within the group. Suppose that a set of people A through Z commonly own a stick, what is to be done about a dispute over the stick between members in this set? Say that A wants to use the stick to spearfish but B does not want the stick used in this way. Under the assumption that they both own it, they should both justly win the dispute, so the spearfishing is simultaneously just and unjust---a contradiction. Some advocates of group ownership attempt to side-step this by having some sort of a group decision-making process over the use of the stick, say that all members take a vote and the majority decide that the stick should be used to spearfish. This would imply that anyone who lost the vote did not own the stick, as they were determined to be the just losers in the conflict over its use. But to say that they do not own the stick contradicts the assumption that all members of the set own the stick. There exists no way out of this; group ownership simply cannot solve for conflicts between group members---this observation holds irrespective of what property system you adhere to, as you will notice I made no reference to the property system actually needing to be derived from the root of conflict-avoidance.

Second, such an ethic supposes that late-comers have just as much of a right as the first-comer, in addition to the above Kinsella excerpt I quote Hans-Hermann Hoppe:[fn:2]
#+begin_quote
What is wrong with this idea of dropping the prior-later distinction as morally irrelevant? First, if the late-comers, i.e., those who did not in fact do something with some scarce goods, had indeed as much of a right to them as the first-comers, i.e., those who did do something with the scarce goods, then literally no one would be allowed to do anything with anything, as one would have to have all of the late-comers' consent prior to doing whatever one wanted to do. Indeed, as posterity would include one's children's children—people, that is, who come so late that one could never possibly ask them—advocating a legal system that does not make use of the prior-later distinction as part of its underlying property theory is simply absurd in that it implies advocating death but must presuppose life to advocate any thing. Neither we, our forefathers, nor our progeny could, do, or will survive and say or argue anything if one were to follow this rule. In order for any person—past, present, or future—to argue anything it must be possible to survive now. Nobody can wait and suspend acting until everyone of an indeterminate class of late-comers happens to appear and agree to what one wants to do. Rather, insofar as a person finds himself alone, he must be able to act, to use, produce, consume goods straightaway, prior to any agreement with people who are simply not around yet (and perhaps never will be). And insofar as a person finds himself in the company of others and there is conflict over how to use a given scarce resource, he must be able to resolve the problem at a definite point in time with a definite number of people instead of having to wait unspecified periods of time for unspecified numbers of people. Simply in order to survive, then, which is a prerequisite to arguing in favor of or against anything, property rights cannot be conceived of as being timeless and nonspecific regarding the number of people concerned. Rather, they must necessarily be thought of as originating through acting at definite points in time for definite acting individuals.
#+end_quote

** The GeoAnarchist Justification
One alternative justification, and in my view the only justification that is at all reasonable, comes from my friend Axel_Haestrod of the geoanarchism subreddit. The justification goes as follows; every man has a right to engage in human action, therefore anyone who interferes with this right has committed a crime. Under this system of law anyone who appropriates anything from the commons has performed a criminal action unto everyone who is now unable to do so. (how does this interfere with their non-criminal action though? As the only thing it interferes with is their ability to appropriate)

There are a few problems here, first if it is the case that appropriating anything is criminal this would make every person a criminal by virtue of acting---action requires that man appropriates scarce means, at the very least some standing room to act in. Therefore we have a contradiction where each man has a right to act, and yet he is a criminal for doing so. The GeoAnarchist may attempt to sidestep this by drawing some sort of a line /beyond/ mere standing room at which appropriation becomes unjust, but any line drawn on what means are just to appropriate beyond standing room will necessarily be arbitrary---making this not a rational system of law, and therefore a system of law which could not avoid conflicts. Furthermore, such an ethic cannot make for a human ethic, that is without action--i.e. without the ability to appropriate scarce means--no man could survive, therefore the anti-homestead ethic cannot assure the survival of mankind. But without any humans there is no point in concerning oneself with what an ethic for humanity should be, therefore an anti-human ethic of any sort is absurd on its face.

Second, we shall expand on the inability to deal with conflicts; conflicts, as described above, are when two men are attempting to implement a given means towards contradictory ends. But that requires that the item in question even be a means in the first place, which requires that someone appropriate said means. But this appropriator is considered to be a criminal in his appropriation, therefore providing that late-comers have an equal claim to this means as does he, which is not a conflict-avoiding ethic as I described earlier.

Third, if the justification that appropriation is criminal because it is interfering with the actions of others, this leaves us in a strange double-bind. We have before us a scenario where neither party was allowed to appropriate a given means in the first place, because to appropriate it would prevent the other from appropriating it, but then you are only preventing other parties from doing something that they weren't allowed to do in the first place!

The final failing, which relates to the first, is that the GeoAnarchist ethic falls on the grounds of its very proposal. Argumentation is not simply free-floating propositions, rather it is a human action requiring that each party appropriate scarce means, at the very least standing room, in order to argue in the first place. Therefore anyone who argues implicitly pre-supposes the homestead principle in the very act of argumentation, making any ethic that explicitly proposes an anti-homestead principle falsified via the law of non-contradiction.

A particularly astute geoanarchist may attempt to sidestep these issues by asserting that it isn't at the point of appropriation that one is acting criminally, but only when the man attempts to exclude others from his appropriated means. This sidestep, however, still fails to make a rational geoist legal system.

** Counterarguments
*** "But a bunch of land claims came from conquest!!"
Fred Foldvary states the following with respect to homesteading:[fn:3]
#+begin_quote
Those who advocate homesteading rules have to confront the fact that almost all [of] the land title[s] today originate in conquest.  The view that the current occupant is the homesteader if there are no heirs of the original owner is in effect a rule that favors the status quo.  By that rule, if one murders the current occupants and they have no heirs, the conqueror has proper possession.  It is also arbitrary how much area, how much time, and what kinds of uses constitute rightful homesteading.
#+end_quote

This sentiment is repeatedly expressed by Georgists, and stems from a misunderstanding of the homestead ethic. If person A homesteads a property X then he is the owner of this property; this could not have come about as the result of conquest. Homesteading is specifically that establishment of a property right over land, i.e. those nature-given means that are not owned by anyone. Now, we suppose that X is stolen from A by B in an act of conquest---A still owns X. Even if centuries pass, the descendants of A, namely the descendant who the chain of heirship grants the property right over X to, still owns X, even though the descendants of B possess X. Those titles always /have to/ lie with the owner, by the definition of a title to property.

In short; adherents of the homestead principle do not claim that it is the current occupant of some land that is the just owner, this would be a ludicrous theory of property, as detailed above. Rather, we say that the title of ownership is not affected by any possession by others---such possession of a means by someone other than the owner of said means against the owners will is a criminal action.

As for the case of a murderer killing a man who has no heirs, we say that he definitely does not have a just claim to the property, any third party would have a superior claim to him as they did not initiate a conflict over its use. This implies that the title is "up for grabs" so to speak.

[explain homestead theory and why its not arbitrary.]

*** "WAA WAA IM A BABY AND I AM UPSET THAT RICH PEOPLE EXIST"[fn:4]

* Footnotes

[fn:1]Stephan Kinsella, /[[https://mises.org/wire/thoughts-latecomer-and-homesteading-ideas-or-why-very-idea-ownership-implies-only-libertarian][Thoughts on the Latecomer and Homesteading Ideas; or, why the very idea of "ownership" implies that only libertarian principles are justifiable]]/

[fn:2]Hans-Hermann Hoppe, /A Theory of Socialism and Capitalism/, pp. 141--42

[fn:3]Fred Foldvary, "The Geolibertarian Ethics of Land Rent," https://bleedingheartlibertarians.com/2012/04/the-geolibertarian-ethics-of-land-rent/

[fn:4]https://youtu.be/Li_MGFRNqOE?t=84, https://youtu.be/Li_MGFRNqOE?t=121, https://youtu.be/Li_MGFRNqOE?t=160
