#+TITLE: Georgism

* Notes
** BritMonkey https://www.youtube.com/watch?v=Li_MGFRNqOE
+ "nobody should have to pay for air because nobody invented air... so why cant the same be said for land?"
  + "yadda yadda owning land is like owning a patch of air"
+ "surely because nobody invented land it should belong equally to all members of society, like air"
+ "if you want to wall off your land and live on it you should expect the rest of society to respect that therefore you should pay a tax on the value of the land to pay for that protection from society. Because other people now dont have access to the land, they should be compensated for it"
** Primo Radical https://www.youtube.com/watch?v=VJzY--edzqM
+ what gives a person a right to draw a line around a piece of property and claim ownership?
* Main Body
** Introduction
Georgism is an ideology that advocates a tax on the unimproved value of all land, land in this context meaning any natural resource. The Georgist justifications for this tax range from commie reeing over the big mean landlords, to the assertion that land is jointly owned by every man, making homesteading a form of aggression. Here I shall be attacking the latter stance as it is the only reasonable formulation of the Georgist ethic.

** What are Property Rights?
First and foremost it must be discussed what exactly it means to have a property right over a given item. Now, many see property rights as some sort of spook, or something only those nasty right wingers care about, but in reality, whenever one proposes any ethic pertaining to law (i.e. any ethic pertaining to the just way to deal with conflicts) that ethic implies a certain theory of property rights and a corressponding system of property rights assignments. In general in a given conflict, conflict here meaning when multiple people are trying to implement the same scarce means towards contradictory ends, the property right is assigned to the party who under the specific legal theory is denoted as the just victor to the conflict. i.e. if legal theory X assigned that in a conflict between A and B over \alpha, A has the property right, then under that legal theory B would be the criminal and A the victim.

Rothbardian Natural Law Theory assignes property rights based upon the ethic of the non-aggression principle, aggression being defined as the initiation of conflict. Essentially this can be framed as saying that the purpose of property rights under Rothbardian NLT is to avoid conflicts. So in any given conflict, to determine who has the property right and therefore which party is acting criminally, one need only determine who has initiated the conflict. I wont go into immense detail on how exactly to do that in this video as it is not particularly relevant, but I do have plans to make a full course on libertarian ethics that will go in-depth on the topic, so if you are visiting from the future be sure to check the description and if the course is done it will be the first link.

I will however give an example as a demonstration of this; say Crusoe and Friday are on a desert island together. One day Crusoe happens upon a stick poking out of a tree, and he appropriates this stick from nature, fashioning it into a spear which he plans to use for spear-fishing. On his way to the ocean, however, Friday sees the same stick and wants to use it to instead stoke his fire. Now, Crusoe cannot use the stick to spearfish at the same time that Friday stokes his fire, so if Friday were to attempt to use the stick in his preferred way we would have a conflict---two men (Crusoe and Friday) are attempting to use the same scarce means (the stick), towards two contradictory ends (fishing and the stoking of a fire). Here one need only consider the causal chain to see that it is Friday who has initiated the conflict here, making Friday the criminal.

Kinsella notes[fn:1] that it is only the Rothbardian theory of property rights that makes any sense, as it is pre-supposed by any who would engage in a dispute over a property claim, no matter what property theory they claim to personally hold:
#+begin_quote
But what is implied in the idea that the right to possess—ownership, that is—is distinct from mere possession? It means that if there is any ownership at all—and those who quarrel over things are all asserting different ownership claims and thus presupposing ownership and its distinction from possession—then /it does not accrue merely to those who take things from others/. That is, if B takes a thing by force from A, this cannot in and of itself make B the owner. Why? Because if it did, it means that C could take it from B, and thereby become owner. But this just means there is no such thing as ownership; there is only possession. "Might makes right," so to speak. But this contradicts the presumption that ownership and possession are different. From this very simple idea, we see that the entire Lockean idea of first-use, first-own, follows. Why? Because if taking some good by force from its previous [possessor] is not sufficient to ground an ownership claim, then by Misesian-style "regression" it becomes obvious that only the first possessor/user can have an ownership claim. Every other person takes it from a previous possessor, and is thus a /mere possessor/—not an owner. The first possessor—the person who plucks the resource from its unowned state out of the commons—is the only possessor who does not take it from someone else; /this/ is why /first/ possession imbues the homesteader with the unique status of ownership.

I.e., the first user and possessor of a good is either its owner or he is not. If he is not, then who is? The person who takes it from him by force? If forcefully taking possession from a prior owner entitles the new possessor to the thing, then /there is no such thing as ownership/, but only mere possession. But such a rule — that a later user may acquire something by taking it from the previous owner — does not avoid conflicts, it rather authorizes them.
#+end_quote

** Problems With Georgist Property Theory
I will now take a more in-depth look at the specific problems with the Georgist property theory, that claims it to be a criminal action to take from the commons. To make this claim is to imply that there must already be a property right over nature-given goods, as no other could possibly object to a person taking something except the owner of that thing.

But this has two problems; first, it falls on the grounds of all group ownership in that it cannot possibly solve conflicts between people within the group. Suppose that a set of people A through Z commonly own a stick, what is to be done about a dispute over the stick between members in this set? Say that A wants to use the stick to spearfish but B does not want the stick used in this way? Under the assumption that they both own it, they should both justly win the dispute, so the spearfishing is simultaneously just and unjust---a contradiction. Some advocates of group ownership attempt to side-step this by having some sort of a group decision-making process over the use of the stick, say that all members take a vote and the majority decide that the stick should be used to spearfish. This would imply that anyone who lost the vote did not own the stick, as they were determined to be the just losers in the conflict over its use. But to say that they do not own the stick contradicts the assumption that all members of the set own the stick. There exists no way out of this; group ownership simply cannot solve for conflicts between group members---this observation holds irrespective of what property system you hold, as you will notice I made no reference to the property system actually needing to solve conflicts.

Second, it supposes that late-comers have just as much of a right as the first-comer, in addition to the above Kinsella excerpt I quote Hans-Hermann Hoppe:[fn:2]
#+begin_quote
What is wrong with this idea of dropping the prior-later distinction as morally irrelevant? First, if the late-comers, i.e., those who did not in fact do something with some scarce goods, had indeed as much of a right to them as the first-comers, i.e., those who did do something with the scarce goods, then literally no one would be allowed to do anything with anything, as one would have to have all of the late-comers' consent prior to doing whatever one wanted to do. Indeed, as posterity would include one's children's children—people, that is, who come so late that one could never possibly ask them—advocating a legal system that does not make use of the prior-later distinction as part of its underlying property theory is simply absurd in that it implies advocating death but must presuppose life to advocate any thing. Neither we, our forefathers, nor our progeny could, do, or will survive and say or argue anything if one were to follow this rule. In order for any person—past, present, or future—to argue anything it must be possible to survive now. Nobody can wait and suspend acting until everyone of an indeterminate class of late-comers happens to appear and agree to what one wants to do. Rather, insofar as a person finds himself alone, he must be able to act, to use, produce, consume goods straightaway, prior to any agreement with people who are simply not around yet (and perhaps never will be). And insofar as a person finds himself in the company of others and there is conflict over how to use a given scarce resource, he must be able to resolve the problem at a definite point in time with a definite number of people instead of having to wait unspecified periods of time for unspecified numbers of people. Simply in order to survive, then, which is a prerequisite to arguing in favor of or against anything, property rights cannot be conceived of as being timeless and nonspecific regarding the number of people concerned. Rather, they must necessarily be thought of as originating through acting at definite points in time for definite acting individuals.
#+end_quote

** Other Justifications
One alternative justification, and in my view the only justification that is at all reasonable, comes from my friend Axel_Haestrod of the geoanarchism subreddit.
*** Foldvarian
+ premise of equality implies that the benefits of natural resources be shared equally

** "But a bunch of land claims came from conquest!!"
#+begin_quote
Those who advocate homesteading rules have to confront the fact that almost all the land title today originate in conquest.  The view that the current occupant is the homesteader if there are no heirs of the original owner is in effect a rule that favors the status quo.  By that rule, if one murders the current occupants and they have no heirs, the conqueror has proper possession.  It is also arbitrary how much area, how much time, and what kinds of uses constitute rightful homesteading.
#+end_quote

* Footnotes
[fn:2]Hans-Hermann Hoppe, /A Theory of Socialism and Capitalism/, pp. 141--42

[fn:1]Stephan Kinsella, /[[https://mises.org/wire/thoughts-latecomer-and-homesteading-ideas-or-why-very-idea-ownership-implies-only-libertarian][Thoughts on the Latecomer and Homesteading Ideas; or, why the very idea of "ownership" implies that only libertarian principles are justifiable]]/
