#+TITLE: The Truth About David Friedman | David Friedman is Not An Ancap

* Notes
** David Friedman on Property Rights, http://www.daviddfriedman.com/Academic/Property/Property.html
+ He lays forth two types of rights:
  + Moral: "The fact that I have a right to do something is an argument, although not necessarily a sufficient argument, that someone who prevents me from doing it is acting wrongly."
  + (Positive) Legal: From the legal standpoint, rights are a description either of what the law says or of how it is enforced. On the latter interpretation, "I have a right to do X" translates as something like "If I do X the police will not arrest me; if someone tries to stop me from doing X the police will arrest him."
+ He says these are not the correct way to think about rights, "We frequently observe behavior which looks like the claiming of rights and the recognition of rights in contexts where neither a moral nor a legal account seems relevant."
  + For this he cites Great Britain's "right" to control Hong Kong, "It is difficult to explain Communist China's willingness to respect that right on legal grounds, given that, from the Maoist standpoint, neither the government of Britain nor previous, non-communist governments with which it had signed agreements were entities entitled to any moral respect. It seems equally difficult to explain it on legal grounds, given the general weakness of international law and the fact that for part of the period in question Great Britain (as a member state of the United Nations) was at war with China. An alternative explanation—that the Chinese government believed that British occupation of Hong Kong was in its own interest—seems inconsistent with the Chinese failure to renew the lease on the New Territories, due to expire in 1997."
+ "A further difficulty with moral accounts of rights, in particular of property rights, is the degree to which the property rights that people actually respect seem to depend on facts that are morally irrelevant. This difficulty presents itself in libertarian accounts of property as the problem of initial acquisition. It is far from clear even in principle how unowned resources such as land can become private property. Even if one accepts an account, such as that of Locke, of how initial acquisition might justly have occurred, that account provides little justification for the existing pattern of property rights, given the high probability that any piece of property has been unjustly seized at least once since it was first cleared. Yet billions of people, now and in the past, base much of their behavior on respect for property claims that seem either morally arbitrary or clearly unjust."
+ "For all of these reasons, I believe it is worth attempting a positive account of rights—an account which is both amoral and alegal. In part I of this essay I present such an account—one in which rights, in particular property rights, are a consequence of strategic behavior and may exist with no moral or legal support."
  + he is not providing any legal ethic, rather just describing a sort of game theoretic description of when people aggress and when they dont, sans any underlying property theory to even understand what is aggression and what isnt

#+begin_quote
In thinking about issues of rights, I find myself playing two quite different roles. As a human being and (like all human beings) an amateur philosopher, I have moral intuitions; from that standpoint, the question is "why ought one not to steal" and the answer is "because it is wicked." As an economist I ask and answer different questions. One is "what are the consequences of people being free to steal." Much of the economic analysis of law is devoted to answering questions of that sort. Another is "why do people (often) not steal?"

This essay is an attempt to answer that final sort of question. I have tried to answer the economist's question about rights rather than the philosopher's not because economics is more important than moral philosophy but because I am more confident in my ability to use economics to produce answers.[21] I have been encouraged in this policy by a curious and convenient coincidence: in most cases, the rules I conclude to be efficient are also the rules I believe to be just.
#+end_quote
+ so there is no david friedmanite legal philosophy, which he fully accepts, therefore it is odd when people take these analyses and apply them to ethical discussions.
  + on a related note, as there is no david friedmanite legal philosophy, there can be no corressponding position on anarchism vs statism, as the question of anarchism vs statism is not a positive one, but a normative one---we must analyse the anarchist as opposed to the statist ethic, rather than analysing the positive effects of these systems. This is because even if we do all the hard work at demonstrating that an unhampered market leads to a greater standard of living in the long run, we lack any corresponding reason as to why this makes it better, not only will this be entirely unconvincing to the high time preference man (https://mises.org/library/duty-natural-outlaws-shut), but even to low time preference people who would therefore have to prefer anarchism to statism we fail to demonstrate that we /should/ be anarchists as opposed to statists. Rather we have retreated into legal whim-worshipping---that our argument is of the form "you should be an anarchist because you would prefer it." But the fact that some set of people would prefer it does not imply that they should be anarchists, it may well be the case that John would prefer to rape Jane than to not rape her, but this does not imply that he /should/ rape her, it is in fact the case that he /should not/ rape her.

** last_username vs PF Jung
