#+title: Anatomy of the Celebritarian

* Notes
** Dave Smith
+ Dave smith not a libertarian: send entire US military to secure the border, secure the border "by any means necessary."
  + this means:
    + the entire 100-mile exclusion zone around the US will be under martial law
    + the US government will be the ones to regulate what is "necessary" and so will have sole discression to turn off the constitution for literally anyone and will have the military to back it up
  + Dave understands that these are the practical implications of his proposal, he has been talking about this shit for years---this means he knows what he is asking for, knows that it is anti-liberty, and still wants it. He is not a libertarian.
  + the people who are a problem, the west-haters as against the hard-working mexicans, are brought in by the US on planes. These would be exempt from his proposed solution. The cartels were caused by the US government in the first place---deal with them by invading mexico.
+ says RFK is not a libertarian: https://youtu.be/Xr_xTRQLSLw?t=1354, "Dave Smith | A Response to James Lindsay | Part Of The Problem 1198"
  + "this is the shit im talking about where people have this calcification of pattern recognition where everyone dissenting against you are among the same groups you got tired of years ago even where they're all different and even 95% on your side about amost everything else and you just throw your hands up and mock them bc they dont do anything bc theyre not in the party."
+ Dave Smith passes ideas through a social acceptability filter: https://youtu.be/wKIPQXw_m4g?t=1213
  + "Despite being so immensely popular, Dave posts Cole [coal] because he's ashamed of being a libertarian." - Harrison
