#+title: The Anti-Environment Manifesto | Environmentalism and the Worship of Poverty | Environmentalism and the Hatred of Humanity | The Environment is Bad, Actually

+ scientism article and atlas shrugged writing of presenting points in sequence "they tell us there are no absolutes, how do you know that it is bad to destroy the environment, etc."

What is the environment? The face of a virgin mountain?---that is the environment. That same mountain-face torn apart and set into the shape of a wall?---that is not the environment. What is it that separates these two forms of stone? In the case of our wall, that stone has been blasted apart, hewn into the shape of bricks, transported to the construction site, and affixed into its proper place---all by the conscious effort of man. In the case of our virgin mountainside, this has not occurred.

It is the motive power of man's mind, his destruction and reformation of what nature provides him with which is the fundamental difference between the natural and the unnatural. What, then, is it that the environmentalist advocates for? He advocates that the environment--that collection of dirt, and stone, and bugs--be protected from the gaze of man---that it be left untouched, undisturbed, by any conscious attempt to reform it into a shape which is more suitable for the attainment of the goals of thinking men.

They tell us that greed is destroying the Earth, and that greed is therefore the root of all evil. But what is the root of greed? If greed is this desire to take from nature for the betterment of man, then the root of greed is the sustenance of mankind.

They cry out that they do not wish to destroy man to aid the environment; they just want mankind to live in harmony with the environment. What, then, does it mean for mankind to live in harmony with the environment? A man fracking oil to fuel his automobile? "No!---That is destructive of the natural environment!" A man farming cows to fuel his body? "No!---That would disrupt the proper functioning of the soil!" A man mining copper to build his computers? "No!---The explosives would scare off migratory birds!" A man plucking an apple from a tree to feed his starving body? "No!---The tree needs those fruits to be eaten by grazing animals which then spread the seeds and thus continue the circle of life!"
