#+title: Zombie Objectivism

* notes
** things to include
+ https://www.youtube.com/watch?v=s1YnAtQtueg
+ Zombie objectivism—much like real zombies they are a plague, an infection, a poison to the movement
+ their arguments in law always end up with "but Ayn Rand said so!"
+ James Valliant "if you initiate physical force against someone you're not an objectivist" in "What is Objectivism? Who are Objectivists? With James Stevens Valliant" by Liebowitz; t. ~24:00
  + contradicts this at like 43 min
** self-zombie, self-randroid? EU
+ EU is an inverse Randroid, a Randroid who worships himself,rather than rand
  + he is a narcissist zombie, the oroborous of zombie objectivism
+ re: his legal nonsense
  + legal positivists might try to pin the law down to some specific ritual. Perhaps it must be written down in a book, then have a judge place his hand on it and sing three hail Marys before it becomes law. But objectivists recognise this as completely arbitrary. Thus the only reasonable positivist position is that the law is whatever is enforced. Such that if I mug someone of their walled and am caught 3 months later that during the mugging, and the entire time I was able to keep the wallet, the law on this matter must be that I get the persons wallet. When I am caught and brought to justice, the law is that the police man gets my wallet. A year or so down the line when the bureaucracy catches up, the law is that the victim gets the wallet. If these are the alternatives that objectivists see, it is no wander that they call for someone to "make the law objective."
* main body
** Why They Won't Debate Me
Despite presenting themselves as intellectual heavyweights and freethinkers extraordinaire; not one of these cowards have the balls to come on and debate me. I have been called a rationalist, a mystic, a religious thinker, every possible smear one might come up with---and yet despite their painting of me as not understanding a single thing I talk about, they are simultaneously adamant in their refusal to ever debate me. Why might this be? Why would you turn down a debate that you claim to be easy to win?

They have their various copes to go along with their cowardice. The most common being that I am simply a dishonest individual, and they refuse to debate dishonest individuals. Of course, this has the added benefit of me being incapable of attacking the very claim that I am dishonest in a debate, because it is already a foregone conclusion. After all, it cannot be possible to be both an anarchist and an Objectivist without being dishonest. This is the fatwa as passed down by Ayn Rand PBUH. Thus the cult is eternally insulated against any internal critiques or advancements; if you wish to question some one area, you are forced into an entirely new philosophy of one. Thus the zombie-philosophy may continue limping along and eating up many more brains in its path.

Of course, these are /only/ copes, nothing more. At no point prior to learning of my disagreement with Rand on legal matters do these types detect any level of dishonesty in me. Yet the instant this topic is broached, I am suddenly irredeemable and incapable of speaking intelligently on /any/ topic. I have become an evader to my core ex post. All of my previous points must be disregarded or claimed to be not quite understanding Rand's point correctly. Then why did none of them point out that it was incorrect at the time? Blank out.

In reality the reason not one of these Randroids agrees to debate me is quite simple: to debate me is to reveal their philosophy as laughably flawed and thus to alienate themselves from the cult. If one were to debate me on the topic, they would surely lose; if any are listening and disagree with my assessment on that front, they should feel free to prove it by debating me! Upon losing, there is now a concrete demonstration of just how uninformed and stupid these people are. This /heavily/ limits the effectiveness of any future cult activities. Prospective worshippers can be immunised against the mind virus by seeing its fruits and being utterly unimpressed. The cult is capable of indoctrinating young, impressionable advocates of freedom and reality by presenting their chosen priest class as being beyond reproach. It is only in appearing to be highly intelligent super-thinkers that they can herd their flock. If a single chink--or great gash--is found in the armour of one's shepherd, the spell is instantly broken.

The result of this is that the zombie which chose to be a man and stand up for what he believes in outside of the designated echo chamber, must be subtly pushed out of the cult. This comes from the fact that the most effective form of cope in the face of the devastating loss in debate, is to claim that the debater on their side didn't know what he was talking about. He was inexperienced, and low-hanging fruit. If that big nasty LiquidZulu were to have debated an experienced adherent of the most truthful doctrines of Ayn Rand, he would have lost. But of course any priest who points this out must be quick to add that they would never bother to debate me because it would simply be too easy for them; or they refuse to talk to dishonest people; or I'm not relevant enough to bother with. Regardless of any previous praise the priest class might have had for their fallen soldier, the new reality has been decreed: this is an individual who doesn't know what he is talking about, and everyone has always known this. We have always been at war with Eastasia, and you better not say otherwise. He who controls the past controls the future. So if the priestly class can maintain just this one avenue of evasion within the Objectivist movement, they can keep the corpse of Ayn Rand propped up to give out whatever new decrees they may come up with.
