#+TITLE: Why Drunk Driving Should Not Be a Crime
#+AUTHOR: LiquidZulu
#+EMAIL: liquidzulu@pm.me
#+STARTUP: latexpreview
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[style=verbose,backend=bibtex]{biblatex}
#+LATEX_HEADER: \bibliography{references}
#+BIBLIOGRAPHY: references plain

#+LATEX:\newpage
* Introduction
If you were to ask a member of the National Socialist German Workers' Party whether it was unjust to enforce racially-homogenous teachings; the answer would be obvious to him -- that such teachings were necessary to ensure order.

If you were to ask your average member of modern society whether it was unjust to enforce what a person may do with their own property on the basis of an arbitrary chemical signal, such as blood alcohol content; the answer would be obvious to him -- that such regulation is necessary to ensure order.


* What is Being Criminalised

A more fundamental question lies obfuscated in many discussions over drunk driving, ensuring a homogenous opinion of all participants --- what precisely is being criminalised?

Its not bad driving, it isn't destruction of property, nor the taking of or reckless endangerment of life. All these acts could easily be directly targeted. No, none of these are what you are charged for, you are a lifelong criminal for the single fact of having the wrong substance in your blood --- yet it is perfectly possible for this to be the case without committing any of the aforementioned crimes.

And what is the effect of allowing government to criminalise the content of ones blood alone, where no untoward action may be ocurring? We have given them the power to make the application of the law arbitrary, capricious, and contingent on the judgement of whatever police officer happens to be having a bad mood that day. Indeed, without the governments breathalyser there is no way to tell that a person is committing this crime. How can it be that you could say someone is acting criminally when it is impossible to determine this without medical test, clearly nobody is being injured or in any way maligned.

To take this further, how is the supposed criminal to know whether they are committing this crime? They can perform informal calculations in their head based on their mass and how many units of alcohol they have consumed, but until a police officer suspects that they are guilty and administers their fallable test you are in the state of performing a shrodingers crime --- that is that you do not know if you are doing what is deemed illegal.


* Arguments and Counterarguments

** The Probability of an Accident Increases

Now, the immediate response goes this way: drunk driving has to be illegal because the probability of causing an accident rises dramatically when you drink --- ignoring the people who drive better after a few due to being more attentive of safety, of course. Indeed, though this seems like a solid defense on the face a simple /reducto ad absurdum/ reveals that criminalising probabilities rather than action is an obviously tyrannical method of law enforcement --- we need look no further than the famous 13/50 and 6/50 meme stats to demonstrate this. If black people are more likely to commit a crime the same logic applied to criminalise drunk driving would imply we may place arbitrary restrictions on people due to skin colour.

#+BEGIN_QUOTE
"But that stat is missleading", one may protest, "it isn't the fact that they are black that they are more likely to be criminal there are other causaul factors, namely poverty caused by systemic racism."
#+END_QUOTE

Ok, let's accept that it is poverty that causes one to commit a crime, would that not lead to an equally tyrannical system, where the poor in society face increased restrictions in a minority report style prediction that they will commit a crime?

In a truly free society -- which I would hope all would desire -- it is not the job of law enforcement to criminalise possible future action, they should focus only on what a person is doing or has done, not what someone thinks they may do. It is the job of voluntary insurance and licensing firms to deal in what a person is probable to do.


** A Family Member/Relative of Mine Died Due to a Drunk Driver

As sad as that is it amounts to nothing more than an appeal to emotions --- the fact that something bad happened to you does not justify any arbitrary restriction on others. Indeed just criminalising the reckless driving there would surely have the same effect, what does adding on a charge for the content of ones blood change?


** Drunk Driving Laws Discourage Drunk Driving

To demonstrate the unjust nature of deterrence as a standard for justice I borrow a quote from Murray Rothbard, he writes;

#+BEGIN_QUOTE
"If there were no punishment for crime at all, a great number of people would commit petty theft, such as stealing fruit from a fruit-stand. On the other hand, most people have a far greater built-in inner objection to themselves committing murder than they have to petty shoplifting, and would be far less apt to commit the grosser crime. Therefore, if the object of punishment is to deter from crime, then a far greater punishment would be required for preventing shoplifting than for preventing murder, a system that goes against most people's ethical standards. As a result, with deterrence as the criterion there would have to be stringent capital punishment for petty thievery--for the theft of bubble gum--while murderers might only incur the penalty of a few months in jail."[0, p.93]
#+END_QUOTE

and further that;

#+BEGIN_QUOTE
"A classic critique of the deterrence principle is that, if deterrence were our sole criterion, it would be perfectly proper for the police or courts to execute publicly for a crime someone whom they know to be innocent, but whom they had convinced the public was guilty. The knowing execution of an innocent man--provided, of course, that the knowledge can be kept secret--would exert a deterrence effect just as fully as the execution of the guilty."[0, p.93]
#+END_QUOTE


** Drunk Driving /is/ Reckless Driving

This argument can be more effectively stated as the following[1];

#+begin_quote
Drunk driving is similar in premise to: It should be legal to fire a gun in public.

If I'm in public and just firing a gun as I walk down main street, it should only become a crime when I hit someone right? The problem is that the behavior itself is so inherently dangerous that doing so is criminally reckless.

Same for drinking and driving. You don't have to wait for an accident to happen. Drinking and driving is inherently reckless. It's reckless driving and that's a crime.
#+end_quote

If it was the case that drunk driving is necessarily paramount to reckless behaviour then you would not need to criminalise being drunk separately from driving dangerously --- the very fact that drunk driving is a crime is an admission by the state that there are drunk people who do not drive dangerously.


* Further Notes

** Sobriety Checkpoints

If it wasn't clear enough at this point that it is blood alcohol that is being criminalised in and of itself rather than any perverse outcome we need look no further than sobriety checkpoints. These blockades stop and test drivers for being in the wrong place at the wrong time with no evidence or suspicion of driving dangerously at all --- this /clearly/ demonstrates that it cannot possibly be bad driving that is illegal here but the chemical composition of a persons blood, a person who has by definition done nothing dangerous.


** Other Factors that Increase Risk

It is also pertinent to note that it is not only alcohol that increases ones risk of being involved in an accident, indeed there are a multitude of different factors that may negatively impact ones driving ability. Perhaps you have sore muscles after going to the gym, you could be tired, or in a bad mood. Should the government now be allowed to test for soreness, or fatigue, or mood?


* Closing Remarks

Bank robbers may tend to wear masks, but the crime they commit has nothing to do with the mask. In the same way, drunk drivers cause accidents but so do sober drivers, and many drunk drivers cause no accidents at all. The law should focus on violations of person and property, not scientific oddities like blood content.

To allow such an application of the law is to allow any arbitrary action the state may wish to commit --- to allow laws against drunk driving is to allow tyranny.


Thank you for watching to this point, this video was based on an article by Llewellyn H. Rockwell, Jr which you can find in the description along with the script to this video, if you have any questions or arguments you should leave them in the comments or ask me on discord, and if you haven't already subscribe to the channel.



* Bibliography

[0] /The Ethics of Liberty/ by Murray Rothbard $\newline$
[1] Pallad#4587, playing devils advocate
