#+TITLE: Introduction To Go

* Liberties
Go is played on a grid where each player takes turns placing on the intersections of said grid, with blacku placing first. [black stone placed on middle] here this black is touching 4 empty spaces, these empty spaces are like sources of oxygen for this black stone and they are called liberties. If white covers up all of these liberties the black stone dies, as it has no more oxygen to breathe from. [black in middle connected to a group] here we have a scenario where there are two connected black stones, stones that are connected like this share oxygen, so if white covers up the direct liberties of the first stone it survives as it breathes through its neighbor, meaning white must suffocate the entire group of stones to kill it off. [black stones placed in a diagonal] note here that groups are only formed when the stones are directly touching, so these two black stones do not form a group, meaning one can be suffocated, leaving the other alive.

[black stone in atari] This stone has only one liberty remaining, we say that this stone is in atari, to get out of atari, the black player must extend the source of oxygen out to allow his stone to continue breathing. A second important arrangement is found when a stone has only two liberties, we say that this stone is in shortage, shortage is also important because it takes only a single move for white to put black into atari.

* Board Priority
[stones blocking off territory] The goal of Go is to surround more territory than your opponent, at this point here if you follow the grid lines you can only reach black stones, so this point is said to be blacks territory, its trivial to see that this is the case for all of these points. Similarly here you can only reach white stones, so this is whites territory. However, in this section you can reach both black and white stones, making it a no mans land where neither white nor black owns the territory.

[stones covering a middle spot, a wall spot, and a corner spot] Here we can see three sets of stones each covering a single piece of territory,[fn:1] we notice that in the middle it takes 4 stones to get the territory, on the wall it takes 3, and in the corner it takes only 2. This is where our first principle, board priority, comes into play. Other things being equal, it is easier to get territory in the corners than it is to get it along the walls, and it is easier to get territory along the walls than it is to get it in the middle.

* Line Height
[Stones in lines aiming at wall territory] Here we see four separate black groups, and because we know that its easier to get territory along the walls of the board than it is to get it in the middle, we can imagine that they will be aiming to get the wall territory, but clearly to different degrees. This group gets one territory for every stone, this one gets two for every stone, three here, and four here. We notice that you get more territory per stone the further from the wall you go. But, there is a tradeoff to playing high; for the first group white has basically no shot at invasion, black can trivially block any attempt by just placing a stone, in the second group its a little easier but still very hard, black can probably stop any invasion attempt. If we go to our last group white can very easily get in under it, cutting it off from that ever-so-sweet wall territory that it was aiming at.

So, we need to find a good middle-ground between playing far enough away from the walls that you are getting a good amount of territory per stone, but not so far that the enemy can trivially snatch it away from you. This middle ground is on the third line, you have a two-for-one deal with each stone and there is still basically no way that white can invade you. [diagram showing the ground and space etc] We can picture the Go board like a halo ring world, the ground is on the third line, you want to start building on the ground before you go anywhere else, if someone tries to invade your territory, you hunker down and dig out some trenches. On the other hand, when you have some nice structures on the ground you can think about expanding out into the sky, once you have done that, only then should you think about trying to master space-flight. This is our second principle, line height, start on the ground, dig down where needed, and expand out when you have the structures to support it.

* Speed vs Strength
Imagine a situation, Buggs Bunny and Daffy Duck are neighbors and they hate each other, so they both move out. In their new homes they make themselves some morning coffee and step out onto their lawns, then they have a terrible realisation, they are neighbors yet again, and whats worse is they share a lawn. They look at each other, and they look at the lawn, they look back at each other and quickly rush inside to get materials for building a fence. "My lawn!" says Daffy, "No my lawn!" says Buggs. "My Lawn!" "No mine!" We can see that they are adopting two different strategies here, on the one hand Daffy is being super slow, but super safe. There is no way that Buggs is going to get Daffy's corner, but also Buggs is aiming at way more territory than Daffy, he is being way faster at cordoning off the lawn, we can squint and maybe estimate that Buggs is trying to get the entire bottom and left walls, which would suck for Buggs because the name of the game is to get more territory than your opponent.

Both of these strategies are flawed, Buggs is not getting all that much territory for his work, he doesnt need to play this safe, he can place his fence posts further apart and fill in where he needs to; Daffy on the other hand, in his super fast play is leaving wide open gaps for Buggs to come in and invade him. We can picture an analogy of trying to build a wall in front of an approaching army, you can put down little sections of wall spaced apart and only fill in where the army actually tries approaching. The solution here is to find a middle-ground between these strategies---you want to play fast, but not too fast, again there are tradeoffs in Go. This is our third principle, speed vs strength.

* Life and Death
[black eye in the corner] Black has here a structure we call an eye, it is some piece of territory surrounded by stones. Unfortunately for black he is completely surrounded by white stones, so all white has to do to take his group is to poke out his eye like so. Consider instead this scenario, where black has two connected eyes, what strategy could white adopt to kill this group? He has two options, he can try to poke out the top eye or he can try the bottom one. If he tries to poke the top eye the black group would still be alive as it still has that second eye, making this an impossible move for white as he is unable to place a stone into suicide like this---the stone would be instantly suffocated. But the same issue faces white in the secon eye, he cant poke that one out either---so we conclude that this black group is immortal, there is no way for white to poke out both eyes at once because he can only place a single stone per turn. This is the principle of life and death---two eyes make life.

[black stones in an arrangement to maybe make two eyes] Now, bearing this in mind, what strategy might white implement to try and kill these black stones? White knows that if black gives this group two eyes then it will be immortal, so what can white do? Well, let's just consider where black would have to place in order to make those eyes. He would clearly have to place here, anywhere else and he hasnt made two eyes, so what if white pre-empts black and places there before him? Seems black has no recourse, if he kills the white stone then he can no longer make two eyes, and a few turns later white can successfully poke out his last remaining eye, killing the group. Bear this in mind when making groups, you want to try and make sure that you can connect groups with two eyes up so that any expansion off of this meta-group will be immortal. The point that black must take in order to ensure that he can make two eyes is called a critical point, and some more complex strucutres may have multiple critical points that black can choose between, the simplest example is to simply stretch the black group out like so, here black may choose any of the spots marked with an X to make two eyes and thus make the group immortal.

* Conclusion
So, lets remember our principles;
1. board priority---corners, then walls, then middle
2. line height---focus your efforts on placing stones on the ground before you dig in deep or go off into space
3. speed vs strength---both Daffy and Buggs have flaws in their strategy, you want to play fast, but not so fast that it becomes easy to invade you.
4. life and death---two eyes makes life

* CTA
With that said if you enjoyed this video you have to watch this one where I apply these principles to determine what the best beginner starting moves are.

* Footnotes

[fn:1]hopefully they wont be pedants and point out that you can only get to black from anywhere.
