export { default as bagOfMoney } from "./bag of money.png";
export { default as beanBagChair } from "./bean bag chair.png";
export { default as bindle } from "./bindle.png";
export { default as camera } from "./camera.png";
export { default as deskFan } from "./desk fan.png";
export { default as dirtyDishes } from "./dirty dishes.png";
export { default as dreamMan } from "./dream man.png";
export { default as dremel } from "./dremel.png";
export { default as fortuneCookie } from "./fortune cookie.png";
export { default as friedChicken } from "./fried chicken.png";
export { default as gunSafe } from "./gun safe.png";
export { default as hangGlider } from "./hang glider.png";
export { default as laptop } from "./laptop.png";
export { default as mayo } from "./mayo.png";
export { default as mic } from "./mic.png";
export { default as mug } from "./mug.png";
export { default as nailClippers } from "./nail clippers.png";
export { default as pencil } from "./pencil.png";
export { default as pickaxe } from "./pickaxe.png";
export { default as refridgerator } from "./refridgerator.png";
export { default as rock } from "./rock.png";
export { default as rope } from "./rope.png";
export { default as subway } from "./subway.png";
export { default as tea } from "./tea.png";
export { default as toilet } from "./toilet.png";
export { default as vendingMachine } from "./vending machine.png";
export { default as weldingMask } from "./welding mask.png";
export { default as whisky } from "./whisky.png";
