#+title: Mad Lads

* Notes
** Absolute Mad Lads - Ted Kaczynski, https://www.youtube.com/watch?v=EE-dAerfrWk&t=2252
+ Ted's message is flawed, not something to be supported by libertarians
+ "Ted argues that technological process strips us of our basic liberty and has made us subservient to the technological system itself by reducing us to mere cogs in the machine that maintains it. Which has lead to the rise of both big governments and corporations, in addition to many of the social ills that plague our society today."
+ "This subservience is caused by the fact that as technology progresses, the system based around it increases in scope which has moulded society around supporting its growth"
  + cashless society example---the fault of central banking, not development
+ "how does the system get away with the wanton erosion of our liberties like this?"
  + "system distracts us by providing increasingly impotent populations with the feeling of security, through fulfilling their physical needs for them as it takes away their freedom."
+ power process---"the gameplay loop of human life, we make a goal and then put in effort to attain it. The most important part is having the autonomy to do so however we wish, even if the method we choose should fail. Ted argues that technological society has robbed us of this power process because the things we need to survive are all practically handed to us on a silver platter, and we dont need to put in any /real/ effort to attain them. Which means that basic human needs just arent as fulfilling as they used to be."
  + "which is more satisfying, applying your own knowledge and ability to build a hut etc, or signing a lease and going down to tesco"
+ "efficient attainment of ends is a coping mechanism, less efficient is better"
+ "these ends are less satisfying because they do not fulfil our biological needs"
+ "technology causes a destruction of the environment which is bad "
  + "replacement with trees and grass with steel and concrete"
    + "Ted says shrinking of the domain of nature is bad"
+ acknowledges the contradiction at the end
* Response Comment
Your analysis of Ted's message being based is deeply flawed---primitivism is false and evil to its core and not something to be supported by libertarians. I will rely solely on your framing of Teds primitivism to demonstrate this, as there are minor differences between primitivists, and I want to particularly attack the kind that you see as valid.

You begin by pointing out that Ted argues that technological development tends people towards becoming mere cogs in the machine, which then causes the rise of many social ills such as statism. However, this argument is odd, in that statism itself implies the destruction of civilisation, as Hoppe has shown in DTGTF section 1, "On Time Preference, Government, and the Process of Decivilization," because you yourself have recommended DTGTF, I shall forego re-stating this argument here. What this leaves us with is a contradiction, the development of civilisation is also the regression of civilisation---as we know, contradictions are falsehoods, therefore this thesis cannot possibly be correct, however tempting it may seem.

You go on to state that subservience is caused by the fact that as technology progresses, the system based around it increases in scope which moulds society around supporting its growth. What is of note here is that the "it" which is growing--the system based around technological progression--is the division of labour. An increase in the scope of and a tendency for society to support the growth of the division of labour is a very good thing---this is anti-apocalypse. Your example of this growth being a bad thing--the march towards a cashless society--is flawed in that such a march is occurring due to state interference in the monetary system through the use of central banking. We see here that the true issue is statism, not technology. This is a common flaw in primitivist thinking, they attribute flaws where they do not belong.

We again must return to DTGTF, in response to your citing of the system distracting us by providing impotent populations with the feeling of security, through fulfilling their basic needs as the cause of people ignoring the wanton erosion of our liberties. It is clear to me that such an ignorance is the result of democracy, not of technology.

Furthermore such a disparagement of having our basic needs met is absurd. Man is faced with scarce means that must be economised towards the attainment of numerable ends, if he is more able to meet the ends of getting water and food, he can re-allocate those scarce means towards the attainment of other ends. Anything short of this is an advocacy of subsistence living, which is a performative contradiction when such an advocacy is done by anyone who chooses to not live like this---including Ted. Moving on, the further assertion that a more efficient allocation of means is less fulfilling as it is not in mere service of survival lacks any scientific rigour. If a man chooses the more efficient path--as he invariably will--he is demonstrating that he himself expects this path to satisfy him more than the alternative. In short, asserting that this man is living a less satisfying life is an inter-personal comparison of utility. To escape this, the primitivist requires some objective theory of ethical value, or we are stuck with plain old utility.

Now, on the environmentalist point, that the shrinking of the domain of nature is bad. This is flawed in that it is nakedly anti-human, the very purpose of action is that it shrinks the domain of nature, warping those nature given goods into forms that are better suited for mans satisfaction.

Lastly, you acknowledge that you are in contradiction, by recognising the hypocrisy in saying that Ted was right over the internet. Unfortunately, such a recognition of hypocrisy does not resolve the contradiction, and thus you remain in falsehood.
