#+TITLE: The Moral Case For Open Borders
#+OPTIONS: toc:nil
#+begin_export md
---
title: "The Moral Case For Open Borders"
description: "The open borders argument has been unfairly maligned as either an insane leftist talking point or a grift forwarded by big business to destroy local cultures and depreciate wages. In reality borders are a moral evil that should be immediately abolished. Here's why."
date: 2023-05-16
---
#+end_export

This document is the script for a video which you can find [[https://youtu.be/I3sa7J-i8ZY][here]]. Due to it being intended as a video experience, it may not read well in certain parts, but regardless I provide this script for your enjoyment or for reading the footnotes and reference material.

* SEO Checklist :noexport:
** Points to hit [0/16]
+ [ ] who's the character?
  + [ ] their want?
  + [ ] their need?
  + [ ] their flaw?
  + [ ] how do they grow?
  + what story/journey could the above create?
+ [ ] what's the desire/motivation of the story?
+ [ ] what's the obstacle?
+ [ ] what're the stakes --- why is it important?
+ [ ] make them care
  + [ ] show what you have so the audience feels the loss when you lose it
+ [ ] what's the resolution --- the one core idea that is the final message of the video that wraps everything up?
  + deliver on the title and thumbnail
+ [ ] storyboard it [0/3]
  + [ ] storylines you have
  + [ ] hook for each
  + [ ] different things that can happen
+ [ ] attach a story to every point I make and tell the story before I make that point
+ [ ] answer questions using spectacle
+ [ ] if things go static stories die, because life is never static.
+ [ ] drama is anticipation mingled with uncertainty
+ [ ] make comment goals (2 or 3)
+ [ ] cater to the archetypal viewer
+ [ ] reference popular media
+ [ ] Make an audience proxy (state things the viewer is thinking)
+ [ ] Problem every 2 minutes
** Intro [0/4]
+ [ ] 8 words right at the start explaining the concept
+ [ ] Personal (character) motivation
+ [ ] Create an enemy
** Questions to ask [0/11]
+ [ ] is there incentive to watch until the end?
+ [ ] can I add something?
+ [ ] what are the different loops that I can open?
+ [ ] what are the different questions that the viewer could ask themselves?
+ [ ] what's the hook?
+ [ ] what do viewers need to see in the first few seconds based on the title and thumbnail so that they feel like their click is worth it?
+ [ ] is there a way to make the viewer laugh or feel surprised or feel something in the first 10 seconds?
+ [ ] is there a way to have two storylines?
  + [ ] surface level story, and hidden stories (finding nemo is ostensably about finding nemo, but really about marlon addressing his insecurities as a father)
  + [ ] is there a way to build surface level and underlying tension in each story?
    + short term: will dory's short term memory make her forget what marlon told her, long term: will we find nemo?
+ [ ] am I giving them 4 or 2+2?
  + https://www.youtube.com/watch?v=KxDwieKpawg
+ [ ] in doing X big thing [0/3]
  + [ ] what do I want?
  + [ ] what happens if I dont get what I want?
  + [ ] what will I do to get what I want?
** Editing [0/5]
+ [ ] Show where possible
+ [ ] if theres a bit of information where you can delete what is before and after it and it flows just as well, cut it
+ [ ] tell stories with B-roll
+ [ ] Keep pace as fast as humanely possible, without impacting the pacing
+ [ ] add breather moments to allow for the pace to not feel too fast https://www.youtube.com/watch?v=o8ZbGnwXjj4
** How to keep people watching [0/23]
+ [ ] deliver on title and thumbnail (video "I ate 100 bananas" shouldnt start with people eating apples or you buying bananas)
+ [ ] /exceed/ the expectations made by the thumbnail
+ [ ] instantly explain the payoff
+ [ ] tell them why to watch
+ [ ] get right into content after delivering
+ [ ] remove every dull moment
+ [ ] find 10 most critical people you know to roast your video
+ [ ] payoff at the end
+ [ ] you can make anything work but it has to be interesting to the audience, original, and good
+ [ ] big stunts
+ [ ] the title should be "bananas are the best food on the planet" rather than "I like bananas"
+ [ ] consider what the experience will be for people in the video, if they liked it they might want to watch more of your videos.
+ [ ] viewers can tell when you are half-assing
+ [ ] (storyline) have an objective
+ [ ] stay on topic
+ [ ] no filler, only content that is neccesary to the narrative and meets the expectations
+ [ ] for payoff have the clear goal that is teased throughout the video
+ [ ] build anticipation to the payoff
+ [ ] wait until the very end to give the payoff
+ [ ] watchtime is not created equal, engagement and viewer surveys will differentiate between a good 25min video and a great one
+ [ ] Signal to the viewer early on that you know something that they dont, e.g. "I've uncovered something about Elon Musk that nobody is talking about."
+ [ ] Get rid of signposting, e.g. over-explaining and ‘telling’ the viewer what's about to happen instead of ‘showing’ them.
+ [ ] subtly re-introduce the hook at several points in the video, most viewers forget what the incentive to watch is 5 or 6 minutes in
** Thumbnail
+ concept more important than aestethics
+ borrow from other successful videos (yoink and twist)
+ make the dominant subject someone people know (so not me when starting off)
+ provide action
+ portray the story of the video
+ other parts of the image shouldnt take focus away from the important, clickable, elements
+ confusion doesnt make people want to click, curiosity \ne confusion
+ should be accurate in the most visually applealing way
+ should be simple and clear
+ colourful and bright
+ have 2-3 different versions of the thumbnail to A/B test
+ check how they look across youtube (thumbsup.tv)
+ recognisable figures improve CTR
+ you probably only want 1 person in your thumbnail (obviously just a rule of thumb)
+ spike their curiosity so much that they will wonder what happened if they dont click
** Title
+ "and this happened" is better than "what happens next will shock you"
+ a good title says what it needs to say in as few characters as possible
** End Screen
+ Next logical step
+ What do the avatars care about?
+ Make people want to know what happens next.
+ be persuasive
  + mention the avatars desire
  + point out what more there is for them to do
    + use "have to"
  + describe the result of them doing that.
+ be confident that the linked video is good
** In-Video CTA
+ Course, subscription etc
  + make CTA right after doing something great in the video
    + best tip
    + laughter
    + clear effort (near end maybe)
    + video climax
  + DONT make it generic
    + remind audience how simple the action is and how much it means to you
    + demonstrate value
* Main Body
** Intro
The open borders argument has been unfairly maligned as either an insane leftist talking point or a grift forwarded by big business to destroy local cultures and depreciate wages. In reality borders are a moral evil that should be immediately abolished. Here's why.

** The Moral Case for Open Borders
The waters are muddied on this issue by arguments analysing whether or not open borders "work" and whether they maximise some definition of economic goodies which the author cares about. I will not be making such an argument, my argument will be a moral one, not one based upon some arbitrarily selected effects that open borders will have.[fn:1] In short, open borders aren't good because they work, they work because they are good. The reason for this is quite simply that the state does not own the land which it rules over, and thus it has no right to decide who is allowed to enter or not.

Consider Crusoe and Friday on a desert island, how is it that either man can come to own land? There are two basic theories we might adopt here; either (1) they can come to own land via original appropriation, that is the Lockean idea of "mixing labour," described more precisely in terms of initially taking possession of some scarce good,[fn:2] or (2) men come to own things in nature by mere verbal declaration or decree. The problem with this second option is that it implies an arbitrary and impossible to follow system of property rights, this is because a mere verbal declaration does not and cannot establish an objective property border that all can see such that conflicts may be avoided. Consider if Crusoe decided that he wanted to own a hill on the island, so he simply shouts to the forest that he now owns this hill. If Friday comes along later he has no means of ascertaining Crusoe's supposed-property right in this hill, therefore this property right does not exist as conflicts over the use of the hill cannot be avoided. I go over this point more heavily in my course on libertarian ethics,[fn:3] which you can read for free, but in short the very purpose of law is to determine an arrangement of property rights, where property rights are conflict avoiding norms, and a conflict is defined as contradictory actions. So if Crusoe is using a stick then Friday tries to use that same stick for something else there is a conflict over the use of the stick---thus law must assign a property right denoting who has the right to control the stick and exclude others from doing so.

We have seen that assigning property right via mere verbal decree cannot avoid conflicts so we are left only with the option that the property right is assigned to the first man who appropriated the good from nature. The state performed no such appropriation. There are vast swathes of many countries that are completely untouched by man; surely if a martian were to fly his ship and touch down in rural Siberia, there are many locations he could do so where no man had ever stepped foot before. Yet, the Russian government would claim that he is trespassing on their land---thus states assert that they gain property right by fiat--by merely declaring to the world that they own a given thing--rather than by actually going out and appropriating goods from nature.

Thus the open borders stance, which can also be called a free-immigration stance, which holds that the state does not have a right to prevent any immigration is correct. Some will take umbrage with the nomenclature, claiming that the correct stance is not one of open state borders but of closed (restricted) private property borders. These people are simply confused; the open borders stance /is/ the one that respects private property. Nobody thinks that open borders means that trespassing on your neighbours lawn is no longer a crime, this is a strawman argument against open borders. Thus I am fundamentally an advocate of open borders or free immigration, I will not slink away from this stance nor will I adjust my speech to say, "umm actually, I support private borders."

** The Social Contract
There are a number of potential counters to my thesis here, the first of which is that there is such a thing as a "social contract," which all men agree to as part of their participation in society, and this contract grants the state the right to exclude people from the communally held land on the citizens' behalf. Such a notion is ludicrous at every level of analysis.

First, I recall signing no such contract, nor does anyone else, and this point is not rescued by any notion of "implicit" consent either, because we know that there are a group of people called anarchists who explicitly /don't/ consent to the actions the state takes "on their behalf." If a man is explicitly /not/ consenting, how could it possibly be that he is implicitly consenting?

Second, a contract defines a set of transfers of title to property,[fn:4] if nobody owned the land in the middle of rural Siberia in the first place, how could title to it possibly be transferred to the state or to anyone else? Moreover, even if this social contract is thought of not as a regular contract but as a method of the citizens "delegating rights" to the state this point is not saved, for none of the citizens had the right to exclude people from entering or appropriating the land in rural Siberia as none owned this land.

Third, this social contract requires a notion of group property, but group property implies a contradiction. To demonstrate why I quote from my course on the matter, which you can read in full for free:
#+begin_quote
Now that we have a theory of property that accounts for both self-ownership and external ownership, we can begin to address some implications of this theory, the first of which is that ownership is necessarily individual---that is, group ownership is strictly impossible. Consider a set of people, $\{A,\cdots,Z\}$, who each commonly own a stick. What is to be done about a conflict over the use of this stick between $A$ and $B$? There are two possibilities, either $A$ is said to be the just victor, or $B$ is. If $A$, then he owns the stick and $B$ does not, if $B$ then he owns the stick, and $A$ does not. But both options contradict the presumption that every member in the set owned the stick, therefore group ownership simply cannot occur.[fn:5]
#+end_quote
There are some supposed-counterexamples to this thesis, but I demonstrate the falsehood of each in my course, so I will not go over any of them here.

** The Hoppean Argument
So the notion of a social contract cannot serve to justify any manner of immigration restrictions enforced by the state, but there is a purported natural rights defense of restricted borders forwarded by Hans-Hermann Hoppe:
#+begin_quote
The phenomena of trade and immigration are different in a fundamental respect, and the meaning of “free” and “restricted” in conjunction with both terms is categorically different. People can move and migrate; goods and services, of themselves, cannot.

Put differently, while someone can migrate from one place to another without anyone else wanting him to do so, goods and services cannot be shipped from place to place unless both sender and receiver agree. Trivial as this distinction may appear, it has momentous consequences. For free in conjunction with trade then means trade by invitation of private households and firms only; and restricted trade does not mean protection of households and firms from uninvited goods or services, but invasion and abrogation of the right of private households and firms to extend or deny invitations to their own property. In contrast, free in conjunction with immigration does not mean immigration by invitation of individual households and firms, but unwanted invasion or forced integration; and restricted immigration actually means, or at least can mean, the protection of private households and firms from unwanted invasion and forced integration. Hence, in advocating free trade and restricted immigration, one follows the same principle: requiring an invitation for people as for goods and services.[fn:6]
#+end_quote

But this invitation requirement certainly does not apply to that unowned land in rural Siberia---nobody owns it and as such the Martians or other immigrants require nobody else's permission or invitation to go there. It is certainly the case, however, that invitation or permission is required when going onto the actual property of others, but this is not in dispute by anyone---it has never been forwarded by any open-borders advocate that open borders means that trespass is no longer a crime. Rather open borders specifically means the position that the government should not be permitted to restrict immigration from outside of the country to inside of that country. Block highlights the position by analogising this to domestic migration:
#+begin_quote
I shall contend that emigration, migration, and immigration all fall under the rubric of “victimless crime.” That is, not a one of these three per se violates the non-aggression axiom. Therefore, at least for the libertarian, no restrictions or prohibitions whatsoever should be placed in the path of these essentially peaceful activities.

Immigration across national boundaries should be analyzed in an identical manner to that migration which takes place within a country. If it is non-invasive for Jones to change his locale from one place in Misesania to another in that country, then it cannot be invasive for him to move from Rothbardania to Misesania. Alternatively, if migration across international borders is somehow illegitimate, this should apply to the domestic variety as well. As long as the immigrant moves to a piece of private property whose owner is willing to take him in (maybe for a fee), there can be nothing untoward about such a transaction. This, along with all other capitalist acts between consenting adults, must be considered valid in the libertarian world. Note that there is no freedom of movement of the person per se. This is always subject to the willingness of property owners in the host nation to accept the immigrant onto their land.[fn:7]
#+end_quote

** The Motte and Bailey of Immigration Restrictions
So if the Hoppean stance is taken to mean /only/ that borders are restricted to the extent that is desired by /individual/ property owners it is fine, but this unobjectionable thesis has been used to spiral out far beyond this point:
#+begin_quote
Moreover, hand in hand with the institution of a government comes the institution of public property and goods, that is, of property and goods owned collectively by all domestic residents and controlled and administered by the government. The larger or smaller the amount of public-government ownership, the greater or lesser will be the potential problem of forced integration.

[...] in non-socialist countries such as the U.S., Switzerland, and the Federal Republic of Germany, which are favorite immigration destinations, a government-admitted immigrant could not move just anywhere. The immigrant’s freedom of movement would be severely restricted by the extent of private property, and private land ownership in particular. Yet, by proceeding on public roads, or with public means of transportation, and in staying on public land and in public parks and buildings, an immigrant can potentially cross every domestic resident’s path, even move into anyone’s immediate neighborhood and practically land on his very doorsteps. The smaller the quantity of public property, the less acute the problem will be. But as long as there exists any public property, it cannot be entirely escaped.[fn:8]
#+end_quote

So here we see that Hoppe is not classing "forced integration" as /merely/ those instances where an immigrant literally trespasses on some private property, but also those situations where an immigrant "crosses the path" of a private property owner via some public possession that the owner is situated near. But this does not imply that the immigrant has violated the rights of the private property owners around the roads that he is using. After all, is it a criminal act by a man from Michigan to use the roads in Indiana or Ohio? Clearly not, there is no such thing as collective property rights, it is not the case that the taxpaying collective come to acquire a collective property right in those resources produced by the stolen tax funds. There simply does not exist a chain of title transfer linking the roads and libraries and other public institutions to a taxpaying collective, nor could there be any such chain. This is because public ownership implies a contradiction, as explained earlier.

It is pointed out also by Hoppe that due to the differing meanings of free-trade and free-immigration, it might be the case that immigration is not mutually beneficial. But whether immigration is mutually beneficial or whether some random third party is upset by the immigration is entirely irrelevant. The same is true, after all, for free-trade. That some random third party is pissed off about John and Sarah trading fish does not imply that this third parties rights are being violated---similarly, some third party being pissed off about a Pakistani or Mexican moving to rural Siberia has absolutely no bearing on the issue of the rights of the case. Law and legal analysis is concerned only with those situations where there is conflict,[fn:9] nobody owns rural Siberia and thus there can be no conflicts over its use. Hoppe presents his argument as follows:
#+begin_quote
There can be shipments (immigrants) without willing domestic recipients. In this case, immigrants are foreign invaders, and immigration represents an act of invasion. Surely, a government’s basic protective function includes the prevention of foreign invasions and the expulsion of foreign invaders.

[...]

Now, if the government excludes a person while there exists a domestic resident who wants to admit this very person onto his property, the result is forced exclusion; and if the government admits a person while there exists no domestic resident who wants to have this person on his property, the result is forced integration.[fn:10]
#+end_quote

But the question must be asked of exactly who this invasion is against---the taxpaying collective? There is no such thing as a collective property right, accordingly an immigrant using public roads and parks is not per se invading against any individual taxpayers. There is also the easy counterexample of an immigrant going to virgin land such as the rural Siberia example mentioned previously---such an immigrant needs no invitation from anyone, as nobody owns those barren wastes.

Moreover, if "restricted" immigration is to be used as a label for free-immigration sans those immigrations which are aggressive then we must also apply "restricted" immigration to the question of murder, or rape. On this view to be anti-rape or murder is to be in favour of closed, or at least restricted, borders---it is the claim that me moving my knife from outside of your body to inside of it without your consent makes me rightly classed as an illegal alien, or immigrant. This is clearly well outside of the normal understanding of what a national border consists of, and forms nothing more than a motte to the bailey of taxpayer socialism.

** The Homeless Question
This bailey is highlighted specifically in what Anglo Libertarian dubs the "Homeless Question." Consider Dave Smith taking his children to the local state-run park and there he sees that a bum has homesteaded one of the climbing frames as a nice platform to consume his narcotics. It is assumed for this scenario that the bum does not pay any taxes towards the upkeep of the park and that Dave Smith does. The question is; does Dave Smith have a right to exclude the bum from using the park?[fn:11] Those in the taxpayer socialism camp claim that Dave Smith has a greater claim to the park than the bum because of the taxes he has paid towards the construction and upkeep of the park. But surely this cannot be the case, for as was explained there is no chain of title transfer that denotes Dave Smith as the owner of the park, and further he could not communally own it with every other taxpayer. The taxes were robbed from him, this does not transfer titles. Moreover, surely his claim is better than the one the government has, but not better than the bum who has actually homesteaded part of that park; homesteaders have the property right rather than any random latecomer. If Dave Smith doesn't own the park and neither does the state, then our theory must treat the park as being unowned until such a time as someone comes along and homesteads part or all of it; the homeless bum has done just that.

Allow me to analyse this claim more broadly, the taxpayer socialist says not only that taxpayers have a superior claim to non-taxpayers, but that "in the meantime" those tax-funded public possessions ought be run as if they were privately owned. Any argument about what the solution is "in the meantime" is flawed, for what is legal now does not become illegal in the future, and what is illegal now doesnt become legal in the future. It is either the case that the correct answer is that immigration is free or restricted, it cannot be anything else. It cannot be that right now the correct answer is closed borders but in the nebulous /future/ natural law flips and it becomes the correct answer to have open borders. It is pointed out in this discussion by those in the Hoppe camp that we don't live in a perfect libertarian society, we live in a statist one, as if this observation is of any substance or changes anything about the argument. Indeed, we do not live in that libertarian society, so we should be advocating that society is shifted into one of strict adherence to natural law; closed borders and restricted immigration are criminal and thus must be strongly opposed.

With that in mind Anglo presents the argument that "in the meantime" public possessions ought be run as if they were privately owned as follows:
#+begin_quote
I am going to defend the view of Hans-Hermann Hoppe, that this property can be justly steered towards emulating the likely management which would occur if it was held privately--as opposed to being left entirely up to the discretion of petty local council politicians--that the ends it should be steered towards are that of a low time preference libertarian social order and away from a hedonistic leftist egalitarian one. And that the ones to do the steering are [the] taxpayers who by their position of having their money forcibly taken to maintain this illegitimately held property they have preference in its use and management over those who do not have money forcibly taken for it.[fn:12]
#+end_quote

But this thesis is a complete non-starter, because it is literally impossible to determine what the taxpaying collective wants to do with the park. Mises showed us this with his impossibility thesis against socialism. The only viable method I see would be to survey the entire taxpaying collective and to attempt to achieve a unanimous opinion on how the specific public possession is to be run. Insofar as there is any disagreement, no matter how small, on what is to be done with the park between even two taxpaying funders of this park then all that can be done is to make a completely arbitrary choice over who is to win this conflict. This is nothing more than legal positivism, it is a complete abandonment of the naturalistic thesis which it is presented as. For this reason a taxpaying collective simply cannot naturally come to acquire a collective property right in anything, and thus the correct answer to this homeless question is that the homeless bum who has committed the heroic act of wrestling control of this socialist possession away from the state is the one who is to be considered its proper owner, nothing else will do.

After all, it could very well be the case that every single taxpayer who has funded a given local park is in fact an egalitarian leftist, you can imagine such a scenario arising in various suburbs in San Francisco and other Democrat strongholds. In such a scenario would the Hoppean maintain that the possession should be steered towards low time preference? This would contradict the starting point that it should be up to the taxpaying collective how it is to be run. What we come to on this point is Hoppeans supporting Democracy: The God That Works Only In This Case.[fn:13] Per Hoppe we know that any democratically run institution will tend to high time preference,[fn:14] thus if the taxpaying collective is to decide their will via democratic means the Hoppean must respect this will by respecting a tendency towards the high time preference socialist egalitarian society that they so desperately despise. If we are to instead take the stance that we must run public possessions as we can "reasonably assume" a private owner would this justifies all manner of violent and evil restrictions done by the state. There was a great deal of time during which most private citizens would absolutely despise having an unvaccinated or unmasked person on their private property; can the state then assume that public vaccine and mask mandates are justified? Most private property owners would not allow you to smoke cigarettes or shoot up heroin on their property; can the state then use this to justify a ban of cigarettes or heroin? Heck, most private property owners wouldn't even want people to possess various hard drugs on their property, thus may the state ban possession of such drugs on public possessions? This would in effect ban said drugs outright.

The only alternative to the taxpaying collective demonstrating their will via democratic vote is to have some arbitrary individual assert what this collective wants without any reference to their actual stated opinions on the matter. This is a complete rejection of the premise that these possessions ought be run as the taxpayer collective wants. The correct solution, again, is that these possessions ought be brought under the exclusive control of heroic homesteaders, such as the drunk bum who uses the park for his own purposes. Anglo rejects this application of homesteading, stating the following:
#+begin_quote
Acknowledging that state property does not actually have a legitimate owner, it could be considered exactly the same as abandoned property. At that point it can be homesteaded by the first person who gets there and wants to claim it. So if a hobo sleeps in a state-owned kids playground they have homesteaded the available property and become the rightful owner. But here's a problem with that as a solution: the government does not give a shit about [the] rightful homestead principle and to be honest neither does the hobo. It's quite absurd to imagine walking up to a drug-addled half-conscious homeless person and saying to them, "how do you do fellow libertarian? I see you've done a mighty fine job homesteading this vacant property, would you like to trade my pen for one of your cigarette's?" and then getting an intelligible response back from them.

Then after that, the government would just enforce its illegitimate claim and kick them out anyway and you've achieved nothing. My point there doesn't refute the homestead principle theory, it only calls it impractical and useless under current conditions. But the homestead principle also does not refute my point that a taxpayer has a greater claim than a non-taxpayer. While the government does enforce its illegitimate claims this emulation is the best way to start working towards creating a society where the homestead principle is actually used and respected. If we don't take these steps then it will remain useless and these steps are supported by the just principle of differing strength's in property rights claims.[fn:15]
#+end_quote

First, whether the government or the hobo understands the homestead principle in explicit terms is entirely irrelevant to the rights of the case. Surely our property theory extends to those who do not yet understand it, as these people can still have conflicts. So the homeless bum may not be intellectually capable of explicating the non-aggression principle or explaining the praxeologic foundations of law, but nevertheless he still has a property right in those goods which he initially possesses from the state of nature, in the exact same way that 2 and 2 make 4 whether any individual is aware of this or not. Also whether the government will end up enforcing their illegitimate claim after your respecting of the homeless persons claim is irrelevant to the question of whether the homeless persons claim was legitimate or not. The question is this: would some random taxpayer have the right to exclude this homeless person from the park? If they do have this right then this random taxpayer (who is a latecomer to the park) is said to be the proper owner of the park and nobody else is. We see here the problem with Anglo's analysis, he says that his point is not a refutation of the homestead principle and that the homestead principle is not a refutation of his point, but clearly these two principles are completely incompatible. Either the homesteader is said to be the owner or some random taxpayer is. It is also not made clear by Anglo or anyone else to my knowledge how exactly the taxpayers have a greater claim to the public park than people who have not paid these taxes. This may seem like an intuitive solution, but a first principles derivation must be able to be provided if it is to be included in any rational theory of property. Nothing less will do.

It is also worth attacking the strategic point made by Hoppeans, Anglo included:
#+begin_quote
If you had a button in front of you and every time you pressed it $1 million were diverted from the ATF's budget to fund government housing what would you do? If you wouldn't press it or at least press it as many times as it took so that all the computers, AC, vehicles, and police equipment in all ATF offices across the US had to be removed leaving the agency completely unable to function then quite frankly you are useless to the libertarian cause and unless you removed every single dollar from the ATF's budget you're hardly much use at all.

[...]

If we don't do this then we are a movement that will never actually do any moving until our objectives are already achieved. How do you achieve your objective when you refuse to move towards it? That's anyone's guess. We can ponder as much as we like about the perfect way that things should be done, but we can fall into the trap of only doing this rather than also looking outside at the imperfect world and trying to make it better. If something can be done with government property whilst it is illegitimately held we need to explore what is preferable and to what ends.[fn:16]
#+end_quote

This point fails on the grounds that it is a disanalogy, pressing the button which diverts funding from the ATF does not cause any extra aggressions to be performed, having the Hoppean management of public possessions does cause such extra aggressions to be performed when contrasted with the open borders lack of management. This is a fundamental misunderstanding of strategy often seen in neo-prags,[fn:17] the principle is that it is the role of strategy and planning to denote which goals are more urgent to be achieved---that is, which aggressions must more urgently be stopped. This presumes that the goal is the stopping of aggression, not the implementation of more aggression. Such an implementation of additional aggression is completely counterproductive in pushing for the very thing that the libertarian is trying to destroy. We are and must be libertarians, not liberty-utilitarians, the difference is subtle but dire. The liberty-utilitarian destroys the cause of liberty in his warping of it, this completely undermines the strategic goal of pushing a hardline natural rights philosophy onto the public consciousness. As Rothbard has pointed out, such individuals have a duty on their own premises to shut up and to pretend to be full adherents of non-aggression.[fn:18]

** Welfare and Immigration
There is also the argument that welfare programs make a free immigration policy untenable, as explained by Hoppe:
#+begin_quote
According to proponents of unconditional free immigration, the U.S. qua high-wage area would invariably benefit from free immigration; hence, it should enact a policy of open borders, regardless of any existing conditions, i.e., even if the U.S. were ensnarled in protectionism and domestic welfare. Yet surely, such a proposal strikes a reasonable person as fantastic. Assume that the U.S., or better still Switzerland, declared that there would no longer be any border controls, that anyone who could pay the fare might enter the country, and, as a resident then be entitled to every “normal” domestic welfare provision. Can there be any doubt how disastrous such an experiment would turn out in the present world?. The U.S., and Switzerland even faster, would be overrun by millions of third-world immigrants, because life on and off American and Swiss public streets is comfortable compared to life in many areas of the third world. Welfare costs would skyrocket, and the strangled economy disintegrate and collapse, as the subsistence fund—the stock of capital accumulated in and inherited from the past—was plundered. Civilization in the U.S. and Switzerland would vanish, just as it once did from Rome and Greece.

Since unconditional free immigration must be regarded as a prescription for national suicide, the typical position among free traders is the alternative of conditional free immigration. According to this view, the U.S. and Switzerland would have to first return to unrestricted free trade and abolish all tax-funded welfare programs, and only then should they open their borders to everyone who wanted to come. In the meantime, while the welfare state is still in place, immigration would have to be made subject to the condition that immigrants are excluded from domestic welfare entitlements.
#+end_quote

But such an argument applies equally to children who can be viewed as immigrants from Storkistan. It is surely abhorrent to advocate that the state impose restrictions on births until such a time that welfare is abolished. We must, as legal scholars, separate the crime of taxing citizens for welfare and the crime of restricting immigration. It may well be strategically beneficial to focus your efforts on removing the welfare first, but it is not legally justifiable to keep the immigration restrictions in place until this goal is achieved. Moreover, if the Hoppean is to be annoyed by the presence of non-taxpaying foreigners and bums in the country, is it not proper for him to endorse a stance that tax-evasion is criminal? If it is the taxpaying-collective that jointly owns the land in the United States for instance, does the Hoppean advocate a policy of deporting tax evaders, or children, or the homeless? This example makes it clear that the Hoppean places blame on those heroic enough to violate state edicts, which is a strange stance for supposed-anarchists, as anarchists we must adopt a hardline natural rights philosophy, and to learn such a philosophy you have to watch this video where I explain that anarcho-capitalism is the solution to law.

* References
+ Ace Archist, /Immigration, Privatization, and Ownership in The Statist Commonwealth/.
+ Anglo Libertarian, "The Homeless Question," https://www.youtube.com/watch?v=jiP_1gAbApA
+ Block, Walter. "Rejoinder to Hoppe on Immigration," /Journal of Libertarian Studies/ 22, No. 1 (2011): 771–792.
+ Christopher Chase Rachels, "The Libertarian Case Against Open Borders," in idem. /White, Right, and Libertarian/
+ Jeff Deist, "Immigration Roundtable," https://mises.org/library/immigration-roundtable
+ Springtime of Nations, "Hoppe's Worst Idea," https://www.youtube.com/watch?v=NO7G2oc4bPU
+ Stephan Kinsella, "I'm Pro-Immigration and Pro-Open Borders," https://www.stephankinsella.com/2010/04/im-pro-immigration-and-pro-open-borders/
+ Walter Block, "A Libertarian Case for Free Immigration," /Journal of Libertarian Studies/ 13:2 (Summer 1998): 167-186

* Footnotes

[fn:1]For an economic/utilitarian analysis of open borders see Ludwig von Mises, "Freedom of Movement," in idem., /Liberalism/.

[fn:2]See LiquidZulu, "Homesteading and Property Rights," in idem., /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/homesteading-and-property-rights/

[fn:3]LiquidZulu, /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/libertarian-ethics/

[fn:4]See LiquidZulu, "Contract Theory," in idem., /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/contract-theory/

[fn:5]LiquidZulu, "On the Impossibility of Group Ownership," in idem. /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/homesteading-and-property-rights/#on-the-impossibility-of-group-ownership

[fn:6]Hans-Hermann Hoppe, "The Case for Free Trade and Restricted Immigration," /Journal of Libertarian Studies/ 13:2 (Summer 1998): 221-233

[fn:7]Walter Block, "A Libertarian Case for Free Immigration," /Journal of Libertarian Studies/ 13:2 (Summer 1998): 167-186

[fn:8]Hans-Hermann Hoppe, "The Case for Free Trade and Restricted Immigration," /Journal of Libertarian Studies/ 13:2 (Summer 1998): 221-233

[fn:9]See LiquidZulu, "The Nature of Law," in idem. /The Fundamentals of Libertarian Ethics/, https://liquidzulu.github.io/the-nature-of-law

[fn:10]Hans-Hermann Hoppe, "The Case for Free Trade and Restricted Immigration," /Journal of Libertarian Studies/ 13:2 (Summer 1998): 221-233

[fn:11]If he does have such a right, he would be allowed to exclude non-taxpaying children from using the park to play on for him to take drugs.

[fn:12]Anglo Libertarian, /The Homeless Question/, t. 5:35

[fn:13]See @JackalopeRider1, https://twitter.com/JackalopeRider1/status/1600492099136376832 ([[https://archive.ph/eZNAj][archived]]).

[fn:14]Hans-Hermann Hoppe, "On Time Preference, Government, and the Process of Decivilization," in idem., /Democracy: The God That Failed/.

[fn:15]Anglo Libertarian, /The Homeless Question/, t. 16:10

[fn:16]Anglo Libertarian, /The Homeless Question/, t. 3:48

[fn:17]See LiquidZulu, /These People are Destroying Libertarianism/, https://www.youtube.com/watch?v=064I02yeLhg

[fn:18]Murray Rothbard, /On The Duty of Natural Outlaws to Shut Up/
